/* Broadcast presentation and real-time controls. Pitch speed/break are game tuning,
   not asserted Statcast measurements. Repertoires are documented in PITCHERS. */
const PITCHERS = [
 {name:'魏碩成',hand:'L',style:'over',pitches:['四縫線','指叉球'],speed:143,source:'https://blog.rebas.tw/articles/3853'},
 {name:'林詔恩',hand:'L',style:'over',pitches:['四縫線','滑球'],speed:143,source:'https://blog.rebas.tw/articles/3853'},
 {name:'威能帝',hand:'R',style:'over',pitches:['四縫線','滑球','變速球'],speed:149,source:'https://blog.rebas.tw/articles/3294'},
 {name:'李東洺',hand:'R',style:'over',pitches:['四縫線','卡特球'],speed:145,source:'https://blog.rebas.tw/articles/3853'},
 {name:'鋼龍',hand:'R',style:'over',pitches:['四縫線','伸卡球','滑球'],speed:148,source:'https://blog.rebas.tw/articles/3281'},
 {name:'黃子鵬',hand:'R',style:'side',pitches:['四縫線','伸卡球','滑球'],speed:133,source:'https://www.redbull.com/tw-zh/猛虎出手：黄子鵬的投球秘技'}
];
const EXTRA_PITCHER={name:'曾家輝',hand:'R',style:'over',pitches:['四縫線','滑球','變速球','卡特球'],speed:146,source:'https://blog.rebas.tw/articles/3964'};
// Remove known transferred players from the former demonstration lineup.
PLAYERS[0]=['王威晨','岳政華','詹子賢','許基宏','陳俊秀','江坤宇','岳東華','高宇杰','張志豪'];
PLAYERS[2]=['陳晨威','林立','梁家榮','廖健富','成晉','林承飛','陳俊宇','嚴宏鈞','余德龍'];
PLAYERS[4]=['李凱威','郭天信','朱育賢','劉基鴻','吉力吉撈・鞏冠','陳子豪','張祐銘','蔣少宏','林孝程'];
const tv={phase:'ready',start:0,aim:{x:0,y:0},pitchIndex:0,power:false,paused:false,flight:null,hit:null,call:'',callUntil:0,swung:false,connected:false,lastButtons:[],keys:new Set(),musicKey:'',pitchCount:[0,0],pitchers:[],stats:{},strategy:'normal',selectedMenu:0};
const stage=document.createElement('div');stage.className='broadcast-stage';
stage.innerHTML='<canvas id="broadcastCanvas" width="1280" height="720" aria-label="即時棒球投打畫面"></canvas><div class="tv-hud" id="tvCount"></div><div class="tv-live"><em>●</em> CPBL LIVE</div><div class="duel-hud" id="tvDuel"></div><div class="call-hud" id="tvCall"></div>';
$('.field-panel').append(stage);
const deck=document.createElement('div');deck.className='control-deck';deck.innerHTML='<div class="pitch-carousel" id="tvPitches"></div><button id="tvAction" class="primary-control">A 投球</button><button id="tvPower">X 強振</button><button id="tvCoach">Y 調度</button><button id="tvMusic">♪ 音樂</button><button id="tvPause">Ⅱ 暫停</button>';
stage.append(deck);$('#tvMusic').hidden=true;$('#tvCoach').hidden=true;$('.topbar').append($('#tvPause'));$('#tvPause').className='header-menu';
stage.append($('#newGame'));$('#newGame').classList.add('field-exit');
$('#newGame').onclick=()=>leaveGame();
const help=document.createElement('div');help.className='input-help';help.innerHTML='<span>左搖桿／方向鍵：瞄準　A／空白：投球・揮棒　LB/RB／Q/E：球種　X／Shift：強振　Y／C：調度　Start／Esc：暫停</span><span class="music-info" id="musicInfo">音樂關閉</span>';
$('#gameScreen').append(help);
const status=document.createElement('div');status.className='controller-status';status.id='controllerStatus';$('#gameScreen').append(status);
const canvas=$('#broadcastCanvas'),ctx=canvas.getContext('2d');
const origStart=startGame,origRender=render,origShowSetup=showSetup,origShowSeason=showSeason;
pitcherName=()=>activePitcher().name;
function activePitcher(){return tv.pitchers[fieldingTeam()]||PITCHERS[fieldingTeam()?state.homeIndex:state.awayIndex]}
startGame=function(team){audioUnlock();tv.phase='ready';tv.flight=null;tv.hit=null;tv.paused=false;tv.pitchIndex=0;tv.aim={x:0,y:0};tv.stats={};tv.pitchCount=[0,0];tv.strategy='normal';origStart(team);tv.pitchers=[PITCHERS[state.awayIndex],PITCHERS[state.homeIndex]];if(state.mode==='season'){state.awayIndex=(team+1+state.season.game%5)%6;tv.pitchers[0]=PITCHERS[state.awayIndex]}render();musicUpdate()};
render=function(){origRender();const p=activePitcher();$('#tvCount').innerHTML='<b>'+state.balls+' B　'+state.strikes+' S　'+state.outs+' O</b><span class="base-diamond">'+state.bases.map(b=>'<i class="'+(b?'on':'')+'"></i>').join('')+'</span><span>'+state.inning+' '+(state.half==='top'?'▲':'▼')+'</span>';
 $('#tvDuel').innerHTML='<div><small>PITCHER · '+p.hand+'HP</small><strong>'+p.name+'</strong><p>'+tv.pitchCount[fieldingTeam()]+' 球 · '+(tv.flight?tv.flight.speed+' km/h':'球速為遊戲參數')+'</p></div><div><small>BATTER · 第 '+(state.orders[battingTeam()]%9+1)+' 棒</small><strong>'+batterName()+'</strong><p>'+ (playerBatting()?'玩家進攻':'玩家守備')+'</p></div>';
 $('#tvAction').textContent=state.over?'A 返回':tv.phase==='pitch'?(playerBatting()?'A 揮棒！':'投球中'):tv.phase==='charge'?'放開出手':!playerBatting()?'A 按住投球':'A 準備打擊';
 $('#tvPower').hidden=!playerBatting();$('#tvPause').hidden=$('#gameScreen').classList.contains('hidden');$('#tvPower').textContent=tv.power?'X 強振 ON':'X 一般打擊';
 $('#tvPitches').innerHTML=!playerBatting()?p.pitches.map((n,i)=>'<button class="'+(i===tv.pitchIndex?'selected':'')+'" data-pitch="'+i+'">'+(i+1)+' '+n+'</button>').join(''):'<span>準備後投手自動出手・球飛來時按 A 揮棒</span>';
 $('#tvPitches').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(tv.phase==='ready'){tv.pitchIndex=+b.dataset.pitch;render()}});musicUpdate();};
announce=function(text){tv.call=text;tv.callUntil=performance.now()+2200};
say=function(text){$('#coachMessage').textContent=text};
renderActions=function(){};
function controlDown(){audioUnlock();if(!$('#modalRoot').innerHTML&&!$('#gameScreen').classList.contains('hidden')){if(state.over){leaveGame();return}if(tv.paused)return;if(tv.phase==='ready'){if(!playerBatting()){tv.phase='charge';tv.start=performance.now();render()}else{tv.phase='windup';tv.start=performance.now();tv.swung=false;render()}}else if(tv.phase==='pitch'&&playerBatting()&&!tv.swung){tv.swung=true;tv.swingTime=(performance.now()-tv.start)/tv.flight.duration;tv.swingStart=performance.now();tv.swingAim={...tv.aim};sfx(180,.06)}}else if($('#modalRoot').innerHTML){const opts=[...$('#modalRoot').querySelectorAll('button.roster-option')];opts[tv.selectedMenu%opts.length]?.click()}else if(!$('#setupScreen').classList.contains('hidden'))launchFromSetup();else if(!$('#seasonScreen').classList.contains('hidden')&&!$('#nextSeasonGame').disabled)$('#nextSeasonGame').click()}
function controlUp(){if(tv.phase==='charge'&&!tv.paused){const q=(performance.now()-tv.start)/1000;const accuracy=1-Math.min(1,Math.abs((q%1.5)-.8)/.8);beginPitch(accuracy)}}
function beginPitch(accuracy=1){const p=activePitcher(),cpu=playerBatting();const type=p.pitches[cpu?Math.floor(Math.random()*p.pitches.length):tv.pitchIndex%p.pitches.length];const speeds={'四縫線':0,'滑球':-14,'變速球':-20,'指叉球':-12,'卡特球':-7,'伸卡球':-4,'曲球':-24,'二縫線':-3,'橫掃球':-17,'掌心球':-25,'蝴蝶球':-35};const speed=p.speed+(speeds[type]??-16)+Math.round(Math.random()*4-2);const scatter=cpu?.75:(1-accuracy)*1.2+.13;
 tv.flight={type,speed,x:(cpu?(Math.random()-.5)*2.7:tv.aim.x)+(Math.random()-.5)*scatter,y:(cpu?(Math.random()-.5)*2.6:tv.aim.y)+(Math.random()-.5)*scatter,duration:1000*149/speed};tv.flight.cpuSwing=Math.random()<(Math.abs(tv.flight.x)<=1&&Math.abs(tv.flight.y)<=1?.68:.2);tv.pitchCount[fieldingTeam()]++;tv.phase='pitch';tv.start=performance.now();tv.swung=false;state.busy=true;tv.pitchActor=fieldingTeam();tv.batActor=battingTeam();render();sfx(90,.1)}
function finishPitch(){const f=tv.flight;const strike=Math.abs(f.x)<=1&&Math.abs(f.y)<=1;const cpu=!playerBatting();const swung=cpu?f.cpuSwing:tv.swung;
 const timing=cpu?Math.random()*.36:Math.abs((tv.swingTime||0)-.86);const aim=tv.swingAim||tv.aim,dx=Math.abs(aim.x-f.x),dy=Math.abs(aim.y-f.y);const spatial=cpu?.35:tv.power?Math.hypot(dx,dy):Math.hypot(Math.max(0,dx-.85),dy);tv.contactAim=aim;if(swung&&timing<.22&&spatial<(tv.power?1.2:1.65)){if(timing>.16||spatial>1.1){contactSound('bat');tv.phase='result';tv.start=performance.now();foul();announce('FOUL · 界外球');state.busy=false;render();return}beginHit(Math.max(.1,1-timing*3-spatial*.25));return}
 contactSound('glove');tv.phase='result';tv.start=performance.now();state.busy=false;const text=swung?'揮棒落空':strike?'好球':'壞球';if(swung||strike)applyStrike(text,text);else applyBall(text,text);sfx(swung?170:360,.08);render();}
function beginHit(quality){contactSound('bat');tv.phase='hit';tv.start=performance.now();const power=!playerBatting()?Math.random()<.3:tv.power;const r=Math.random();let type=quality>.8&&power&&r>.45?'HR':r<.24+(tv.strategy==='deep'?.1:0)?'OUT':quality>.66&&power?'2B':'1B';tv.hit={type,x:200+Math.random()*880,y:type==='HR'?160:230+Math.random()*230,quality,runners:state.bases.slice(),batter:batterName(),fielder:[340,235],batSide:battingTeam()};tv.hit.fielder=[tv.hit.x<640?300:980,260];announce(type==='HR'?'深遠飛球！':'擊球！');sfx(700,.07);}
function resultReset(){tv.phase='ready';state.busy=false;tv.flight=null;tv.hit=null;tv.swung=false;tv.swingAim=null;tv.aim={x:0,y:0};tv.pitchIndex%=activePitcher().pitches.length;render()}
const origApplyHit=applyHit;
applyHit=function(type){origApplyHit(type);checkWalkoff();};
const origWalk=walk;walk=function(){origWalk();checkWalkoff()};
function checkWalkoff(){if(!state.over&&state.half==='bottom'&&state.inning>=9&&state.runs[1]>state.runs[0]){state.over=true;finishGame()}}
endHalf=function(){resetCount();state.outs=0;state.bases=[null,null,null];if(state.half==='top'){if(state.inning>=9&&state.runs[1]>state.runs[0]){state.over=true;finishGame();return}state.half='bottom'}else{if(state.inning>=9&&state.runs[0]!==state.runs[1]||state.inning>=12){state.over=true;finishGame();return}state.inning++;state.half='top'}if(state.inning>=10){const i=battingTeam(),team=i?state.homeIndex:state.awayIndex;state.bases[1]=PLAYERS[team][(state.orders[i]+8)%9]}tv.strategy='normal';say('換邊・'+state.inning+' 局'+(state.half==='top'?'上':'下'))};
const origLeave=leaveGame;leaveGame=function(){tv.phase='ready';tv.flight=null;tv.hit=null;$('#tvPause').hidden=true;musicStop();origLeave()};
function pause(){if($('#gameScreen').classList.contains('hidden'))return;if(!tv.paused){tv.paused=true;tv.pauseAt=performance.now();announce('PAUSED')}else{const dt=performance.now()-tv.pauseAt;tv.start+=dt;tv.swingStart=(tv.swingStart||0)+dt;tv.paused=false;tv.callUntil=0}$('#tvPause').textContent=tv.paused?'☰ 選單':'☰ 暫停';if(tv.paused)musicStop();else musicUpdate()}
function cyclePitch(dir){if(tv.phase!=='ready')return;tv.pitchIndex=(tv.pitchIndex+dir+activePitcher().pitches.length)%activePitcher().pitches.length;render()}
$('#tvAction').onpointerdown=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);controlDown()};$('#tvAction').onpointerup=controlUp;$('#tvAction').onpointercancel=controlUp;
$('#tvPower').onclick=()=>{tv.power=!tv.power;render()};$('#tvPause').onclick=openPauseMenu;$('#tvCoach').onclick=()=>{audioUnlock();openCoach()};$('#tvMusic').onclick=openMusic;
const resumeButton=document.createElement('button');resumeButton.className='resume-game';resumeButton.textContent='▶ 點此繼續比賽';resumeButton.onclick=()=>{if(tv.paused)pause()};stage.append(resumeButton);
function openPauseMenu(){
 if($('#gameScreen').classList.contains('hidden'))return;
 modal('比賽暫停','繼續比賽、教練調度與設定','<button class="roster-option" id="menuResume"><strong>▶ 繼續比賽</strong></button><button class="roster-option" id="menuCoach" '+(tv.phase!=='ready'||state.over?'disabled':'')+'><strong>教練調度</strong><small>換投、代打、盜壘、守備佈陣 · 打席間可用</small></button><button class="roster-option" id="menuSettings"><strong>遊戲設定</strong></button><button class="roster-option" id="menuExit"><strong>離開比賽</strong></button>');
 $('#menuResume').onclick=()=>{closeModal();if(tv.paused)pause()};$('#menuCoach').onclick=openCoach;$('#menuSettings').onclick=openMusic;$('#menuExit').onclick=()=>{closeModal();leaveGame();$('#tvPause').hidden=true};$('.modal .cancel-button').textContent='繼續比賽';
}
$('#tvPause').textContent='☰ 暫停';$('#tvPause').hidden=true;
const baseModal=modal,baseCloseModal=closeModal;let modalPausedGame=false;
modal=function(...args){if(!$('#gameScreen').classList.contains('hidden')&&!tv.paused){pause();modalPausedGame=true}baseModal(...args)};
closeModal=function(){baseCloseModal();if(modalPausedGame){modalPausedGame=false;if(tv.paused)pause()}};
canvas.onpointerdown=e=>{const b=canvas.getBoundingClientRect();tv.aim.x=Math.max(-1.6,Math.min(1.6,((e.clientX-b.left)/b.width*1280-640)/35));tv.aim.y=Math.max(-1.6,Math.min(1.6,((e.clientY-b.top)/b.height*720-340)/40))};
function inputAction(code){if(code==='Space')controlDown();if(code==='KeyQ')cyclePitch(-1);if(code==='KeyE')cyclePitch(1);if((code==='ShiftLeft'||code==='ShiftRight')&&playerBatting()){tv.power=!tv.power;render()}if(code==='KeyC')openPauseMenu();if(code==='Escape'){if($('#modalRoot').innerHTML)closeModal();else openPauseMenu()}}
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!e.repeat)inputAction(e.code);tv.keys.add(e.code);if(!$('#setupScreen').classList.contains('hidden')&&['ArrowLeft','ArrowRight'].includes(e.code))chooseTeam(e.code==='ArrowLeft'?-1:1)});
window.addEventListener('keyup',e=>{tv.keys.delete(e.code);if(e.code==='Space')controlUp()});
// Pause only when the document is hidden.
window.addEventListener('blur',()=>tv.keys.clear());
document.addEventListener('visibilitychange',()=>{tv.keys.clear();if(document.hidden&&!$('#gameScreen').classList.contains('hidden')&&!tv.paused)pause()});
function chooseTeam(d){$('#teamSelect').value=(+$('#teamSelect').value+d+6)%6;updateOpponent();$('#teamChoice').textContent=TEAMS[+$('#teamSelect').value].name}
const picker=document.createElement('div');picker.className='team-picker';picker.innerHTML='<button id="teamPrev" aria-label="上一隊">◀</button><strong id="teamChoice">味全龍</strong><button id="teamNext" aria-label="下一隊">▶</button>';$('.select-wrap').after(picker);$('.select-wrap').style.display='none';$('#teamPrev').onclick=()=>chooseTeam(-1);$('#teamNext').onclick=()=>chooseTeam(1);$('#teamSelect').addEventListener('change',()=>$('#teamChoice').textContent=TEAMS[+$('#teamSelect').value].name);
$('.hero-copy h1').innerHTML='進場。<br><em>下一球，由你。</em>';$('.hero-copy p').textContent='轉播視角・即時投打・搖桿操作';$('.rules-note p').textContent='遊戲版九局制，十二局上限。六隊代表投手與示範打線；賽季為 20 場自訂賽程。';
function openCoach(){if(tv.phase!=='ready'||state.over)return;tv.selectedMenu=0;const pitches=!playerBatting()?'<button class="roster-option" id="coachPitch"><strong>換投：曾家輝</strong><small>四縫線・滑球・變速球・卡特球</small></button>':'';modal('教練暫停','搖桿上下選擇，A 確認，B 返回。',((state.homeIndex===2&&!playerBatting()&&activePitcher().name!=='曾家輝')?pitches:'')+'<button class="roster-option" id="coachSteal"><strong>盜壘</strong><small>玩家進攻、一壘有人且二壘空時可用</small></button><button class="roster-option" id="coachDefense"><strong>外野後退 / 標準</strong><small>後退提高長飛球接殺機會</small></button><button class="roster-option" id="coachPinch"><strong>代打：下一棒</strong><small>交換本打席與下一棒順序（本場）</small></button>');$('#coachPitch')?.addEventListener('click',()=>{tv.pitchers[1]=EXTRA_PITCHER;tv.pitchIndex=0;closeModal();render();announce('換投 · 曾家輝')});$('#coachSteal').onclick=()=>{if(playerBatting()&&state.bases[0]&&!state.bases[1]){closeModal();steal();render()}else announce('沒有可盜二壘的跑者')};$('#coachDefense').onclick=()=>{tv.strategy=tv.strategy==='deep'?'normal':'deep';closeModal();announce(tv.strategy==='deep'?'外野後退':'標準守備')};$('#coachPinch').onclick=()=>{if(!playerBatting()){announce('玩家進攻時才能代打');return}const a=state.orders[1]%9,b=(a+1)%9;[PLAYERS[state.homeIndex][a],PLAYERS[state.homeIndex][b]]=[PLAYERS[state.homeIndex][b],PLAYERS[state.homeIndex][a]];closeModal();render();announce('打序調整')};}
// Persisted compact season: three games per round; each team's wins balance opponents' losses.
newSeason=team=>({team,game:0,total:20,standings:TEAMS.map((_,i)=>({w:0,l:0,t:0,i})),results:[]});
try{const saved=JSON.parse(localStorage.getItem('cpbl-season-broadcast'));if(saved&&saved.standings?.length===6)state.season=saved}catch(e){}
recordSeasonGame=function(){const s=state.season,opp=state.awayIndex;function credit(a,b,ra,rb){if(ra===rb){s.standings[a].t++;s.standings[b].t++}else{s.standings[ra>rb?a:b].w++;s.standings[ra>rb?b:a].l++}}credit(s.team,opp,state.runs[1],state.runs[0]);const rest=TEAMS.map((_,i)=>i).filter(i=>i!==s.team&&i!==opp);credit(rest[0],rest[1],Math.floor(Math.random()*8),Math.floor(Math.random()*8));credit(rest[2],rest[3],Math.floor(Math.random()*8),Math.floor(Math.random()*8));s.results.push({opponent:opp,runs:state.runs.slice()});s.game++;localStorage.setItem('cpbl-season-broadcast',JSON.stringify(s))};
const oldSeasonRender=renderSeason;renderSeason=function(){oldSeasonRender();const s=state.season;if(!s)return;const sorted=[...s.standings].sort((a,b)=>(b.w/(b.w+b.l||1))-(a.w/(a.w+a.l||1)));$('#standingsTable').innerHTML='<div class="stand-row"><b>#</b><b>球隊</b><b>勝–敗–和</b><b>勝率</b></div>'+sorted.map((r,i)=>'<div class="stand-row '+(r.i===s.team?'me':'')+'"><span>'+(i+1)+'</span><span>'+TEAMS[r.i].name+'</span><span>'+r.w+'–'+r.l+'–'+r.t+'</span><span>'+(r.w/(r.w+r.l||1)).toFixed(3)+'</span></div>').join('');$('#scheduleList').innerHTML=Array.from({length:Math.min(5,s.total-s.game)},(_,i)=>'<div class="schedule-item">第 '+(s.game+i+1)+' 場 <b>'+TEAMS[(s.team+1+(s.game+i)%5)%6].name+'</b></div>').join('')||'賽季完成';};
// Audio effects use a short noise transient and resonant body, independent of music.
let audioCtx,musicEnabled=true,effectsEnabled=true;
function audioUnlock(){if(!audioCtx){try{audioCtx=new (window.AudioContext||window.webkitAudioContext)()}catch(e){return}}if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{})}
function sfx(){ /* Interface actions stay quiet. */ }
function contactSound(kind){
 if(!effectsEnabled||masterMuted)return;audioUnlock();if(!audioCtx||audioCtx.state!=='running')return;
 const bat=kind==='bat',duration=bat?.13:.19,time=audioCtx.currentTime;
 const buffer=audioCtx.createBuffer(1,Math.ceil(audioCtx.sampleRate*duration),audioCtx.sampleRate),data=buffer.getChannelData(0);
 for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/(audioCtx.sampleRate*(bat?.014:.035)));
 const source=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),gain=audioCtx.createGain();source.buffer=buffer;filter.type=bat?'highpass':'lowpass';filter.frequency.value=bat?1100:900;gain.gain.value=bat?.55:.7;source.connect(filter).connect(gain).connect(audioCtx.destination);source.start(time);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect()};
 const tone=audioCtx.createOscillator(),body=audioCtx.createGain();tone.type='triangle';tone.frequency.setValueAtTime(bat?950:180,time);tone.frequency.exponentialRampToValueAtTime(bat?330:65,time+.07);body.gain.setValueAtTime(bat?.18:.28,time);body.gain.exponentialRampToValueAtTime(.001,time+duration);tone.connect(body).connect(audioCtx.destination);tone.start(time);tone.stop(time+duration);tone.onended=()=>{tone.disconnect();body.disconnect()};
}
function musicStop(){tv.musicKey=''}
function musicUpdate(){}
function openMusic(){}
let masterMuted=false;$('#soundToggle').onclick=()=>{audioUnlock();masterMuted=!masterMuted;$('#soundToggle').classList.toggle('muted',masterMuted);$('#soundToggle').textContent=masterMuted?'🔇':'♪';$('#soundToggle').setAttribute('aria-label',masterMuted?'取消靜音':'靜音');musicUpdate()};
// Canvas scene. Coordinates are a center-field TV camera, then an elevated tracking camera.
function line(x1,y1,x2,y2,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fill()}
function oval(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function person(x,y,size,color,pose=0,kind='field',left=false){
 ctx.save();ctx.translate(x,y);ctx.scale(size*(left?-1:1),size);oval(2,4,26,6,'#0005');
 const crouch=kind==='catch',delivery=kind==='pitch',bat=kind==='bat',hip=crouch?-30:-51,shoulder=crouch?-57:-94;
 const step=delivery?pose*20:bat?Math.sin(pose*Math.PI)*10:0,lx=-15+step,rx=18-step;
 const knee=crouch?[-29,-14]:[-10+step*.4,-27],rk=crouch?[28,-12]:[13-step*.5,-23];
 function limb(a,b,c,width,shade){line(...a,...b,'#b8bbba',width+2);line(...b,...c,'#b8bbba',width+1);line(a[0]-2,a[1],b[0]-2,b[1],shade,width-2);line(b[0]-2,b[1],c[0]-2,c[1],shade,width-3)}
 limb([-8,hip],knee,[lx,-3],13,'#f2f0df');limb([8,hip],rk,[rx,0],13,'#e0e2d9');line(lx,-9,lx,-2,color,6);line(rx,-7,rx,0,color,6);oval(lx-3,0,10,3,'#111c29');oval(rx+4,2,11,3,'#111c29');line(lx-8,-1,lx+3,-1,'#89949b',1);line(rx-1,0,rx+9,0,'#89949b',1);
 const jersey=ctx.createLinearGradient(-18,0,18,0);jersey.addColorStop(0,'#152c3a');jersey.addColorStop(.3,color);jersey.addColorStop(.8,color);jersey.addColorStop(1,'#132637');ctx.fillStyle=jersey;ctx.beginPath();ctx.moveTo(-9,shoulder-3);ctx.quadraticCurveTo(-23,shoulder,-17,shoulder+20);ctx.lineTo(-11,hip);ctx.quadraticCurveTo(0,hip+4,12,hip);ctx.lineTo(17,shoulder+16);ctx.quadraticCurveTo(22,shoulder,-9,shoulder-3);ctx.fill();line(-11,hip,12,hip,'#15232d',4);oval(1,hip,2,2,'#bead83');line(-9,shoulder+17,-8,hip-7,'#ffffff22',1);line(8,shoulder+15,6,hip-9,'#0003',1);line(-9,hip-9,-2,hip-11,'#fff3',1);
 const side=delivery&&activePitcher().style==='side',ax=delivery?22+pose*(side?34:20):bat?19+Math.sin(pose*Math.PI)*26:25,ay=delivery?shoulder+(side?18:-19)+pose*(side?5:43):bat?shoulder+3:shoulder+24;
 const elbow=[delivery?24+pose*4:21,shoulder+12];line(12,shoulder+5,...elbow,color,12);line(...elbow,ax,ay,'#ae7953',7);line(elbow[0]-1,elbow[1],ax-1,ay,'#d0a27e',4);oval(ax,ay,5,4,'#c99b78');const gloveX=delivery?-22+pose*8:-27,gloveY=shoulder+24;
 line(-13,shoulder+5,gloveX,gloveY,color,11);oval(gloveX,gloveY,9,11,'#654122');oval(gloveX-2,gloveY-2,6,8,'#9b6a34');for(let i=0;i<3;i++)line(gloveX-5+i*4,gloveY-8,gloveX-6+i*4,gloveY+3,'#cfab75',1);
 line(0,shoulder-3,0,shoulder-10,'#be8b65',8);oval(0,shoulder-18,9,12,'#c49671');oval(5,shoulder-17,3,6,'#e0b08b');line(6,shoulder-18,11,shoulder-16,'#a77351',2);if(!delivery){oval(5,shoulder-20,1,1,'#28302f')}
 oval(-1,shoulder-27,11,6,color);poly([[-12,shoulder-25],[-9,shoulder-33],[5,shoulder-33],[10,shoulder-25]],color);line(4,shoulder-26,16,shoulder-25,color,4);line(-8,shoulder-31,3,shoulder-32,'#ffffff44',1);
 if(delivery){ctx.save();if(left)ctx.scale(-1,1);ctx.fillStyle='#f7f3e2';ctx.font='bold 15px system-ui';ctx.textAlign='center';ctx.fillText('P',0,shoulder+28);ctx.restore()}
 if(bat){const bx=ax+Math.cos(pose*Math.PI*1.4)*47,by=ay-67+Math.sin(pose*Math.PI*1.4)*55;line(ax,ay,bx,by,'#7d582f',6);line(ax-1,ay,bx-1,by,'#dec087',3);line(ax,ay,ax+(bx-ax)*.2,ay+(by-ay)*.2,'#242a2d',4);oval(ax-3,ay+2,4,3,'#f1e9d9');}
 if(crouch){poly([[-13,shoulder+3],[13,shoulder+3],[10,hip-3],[-10,hip-3]],'#23394e');for(let i=0;i<4;i++)line(-10,shoulder+10+i*5,10,shoulder+10+i*5,'#506276',2);line(-28,-20,-17,-8,'#304a61',9);line(27,-18,rx,-2,'#304a61',9);ctx.strokeStyle='#8695a0';ctx.lineWidth=1.5;ctx.strokeRect(-8,shoulder-27,19,22);line(-7,shoulder-17,10,shoulder-17,'#8695a0',1);line(-7,shoulder-10,10,shoulder-10,'#8695a0',1)}ctx.restore();
}
function stadium(){const g=ctx.createLinearGradient(0,0,0,260);g.addColorStop(0,'#172b40');g.addColorStop(1,'#3f6370');ctx.fillStyle=g;ctx.fillRect(0,0,1280,720);ctx.fillStyle='#1d2e3d';ctx.fillRect(0,65,1280,205);for(let row=0;row<9;row++){for(let col=0;col<70;col++){const x=col*19+row%2*7,y=72+row*18;ctx.fillStyle=['#bec3b0','#a33737','#f0cb77','#628092','#d7dfcd'][(row*71+col*3)%5];ctx.fillRect(x,y,5,5);ctx.fillStyle='#345063';ctx.fillRect(x-2,y+6,11,6)}}ctx.fillStyle='#142c33';ctx.fillRect(0,236,1280,60);ctx.font='bold 27px system-ui';ctx.textAlign='center';ctx.fillStyle='#e6efe7';for(let i=0;i<4;i++){ctx.fillText(['CPBL BASEBALL','PLAY YOUR GAME','TAIWAN · 2026','THE NEXT PITCH'][i],160+i*320,274)}for(let x=0;x<1280;x+=50)line(x,235,x+18,310,'#b9c4cb22',1)}
function drawPitchScene(now){stadium();ctx.fillStyle='#4d7037';ctx.fillRect(0,296,1280,424);for(let i=0;i<8;i++)poly([[i*190-120,296],[i*190+10,296],[i*240+100,720],[i*240-70,720]],i%2?'#557c3e':'#4a7338');poly([[290,296],[990,296],[1190,720],[90,720]],'#b6895e');oval(640,602,188,80,'#b68a60');poly([[625,357],[655,357],[659,365],[640,378],[621,365]],'#f2efe4');line(566,340,565,403,'#eee8d8',3);line(713,340,714,403,'#eee8d8',3);line(565,403,599,404,'#eee8d8',3);line(681,404,714,403,'#eee8d8',3);poly([[629,590],[668,590],[666,596],[632,596]],'#e9e7d4');
 const elapsed=now-tv.start,wind=tv.phase==='windup'?Math.min(1,elapsed/900):tv.phase==='charge'?Math.sin(elapsed/300)*.2:tv.phase==='pitch'?Math.min(1,elapsed/180):0;const fs=tv.phase==='hit'?tv.pitchActor:fieldingTeam(),bs=1-fs;person(580,614,2.15,teamFor(fs).color,wind,'pitch',activePitcher().hand==='L');person(645,390,1.12,'#171f2a',0,'catch');person(663,346,1.05,'#303640',0,'catch');const swing=tv.swung?Math.min(1,(now-(tv.swingStart||now))/220):0;person(553,403,1.42,teamFor(bs).color,swing,'bat');
 // Strike zone stays in the actual plate plane; reticle moves with stick input.
 ctx.strokeStyle='#fff8';ctx.lineWidth=1;ctx.strokeRect(605,301,70,80);for(let i=1;i<3;i++){line(605+i*70/3,301,605+i*70/3,381,'#fff3',1);line(605,301+i*80/3,675,301+i*80/3,'#fff3',1)}const battingAim=tv.swung?(tv.swingAim||tv.aim):tv.aim,ax=640+battingAim.x*35,ay=341+battingAim.y*40;ctx.strokeStyle='#f8cd63';ctx.lineWidth=2;ctx.beginPath();ctx.arc(ax,ay,10,0,Math.PI*2);if(!playerBatting()||tv.power){ctx.stroke();line(ax-15,ay,ax-5,ay,'#f8cd63');line(ax+5,ay,ax+15,ay,'#f8cd63')}else{ctx.save();ctx.translate(ax,ay);ctx.rotate(tv.swung?-.75+swing*1.5:0);line(-40,0,40,0,'#eccb88',8);line(-40,0,-18,0,'#3d3430',5);ctx.restore();if(tv.swung){ctx.strokeStyle='#ffe8a788';ctx.beginPath();ctx.ellipse(ax,ay,60,24,swing*Math.PI,0,Math.PI);ctx.stroke()}}
 if(tv.phase==='charge'){ctx.fillStyle='#081722cc';ctx.fillRect(920,500,240,55);const q=(elapsed/1000)%1.5/1.5;ctx.fillStyle='#67849a';ctx.fillRect(940,519,200,9);ctx.fillStyle='#efc95c';ctx.fillRect(1038,515,17,17);ctx.fillStyle='white';ctx.fillRect(940+q*200,514,4,20);ctx.font='14px system-ui';ctx.fillText('在金色區放開 A',1040,552)}
 if(tv.phase==='pitch'){const f=tv.flight,t=Math.max(0,Math.min(1,elapsed/f.duration));const breakX={'滑球':45,'卡特球':16,'伸卡球':-23,'變速球':-10,'指叉球':2,'曲球':-12,'二縫線':-20,'橫掃球':58,'四縫線':0}[f.type]||0;const breakY={'滑球':15,'卡特球':7,'伸卡球':21,'變速球':28,'指叉球':38,'曲球':65,'二縫線':16,'橫掃球':18,'四縫線':-4}[f.type]||0;const side=activePitcher().style==='side',originX=side?690:620,originY=side?500:430;const x=originX+(640+f.x*35-originX)*t+Math.sin(t*Math.PI)*breakX,y=originY+(341+f.y*40-originY)*t-Math.sin(t*Math.PI)*breakY;oval(x,y,Math.max(3,8-t*4),Math.max(3,8-t*4),'#fff9df');if(t>.85){ctx.fillStyle='#fff';ctx.font='bold 16px system-ui';ctx.fillText(f.speed+' km/h',785,437)}}
 ctx.textAlign='left';ctx.font='13px system-ui';ctx.fillStyle='#ffffffa0';ctx.fillText('CENTER FIELD CAM',20,690);ctx.textAlign='center';}
function fieldPoint(base){return [[940,490],[640,333],[340,490],[640,653]][base]}
function drawHitScene(now){stadium();ctx.fillStyle='#426d3c';ctx.fillRect(0,290,1280,430);for(let i=0;i<8;i++)poly([[i*170,290],[i*170+85,290],[i*210+110,720],[i*210,720]],'#507c43');poly([[640,312],[955,487],[640,665],[325,487]],'#b98d63');poly([[640,350],[888,487],[640,625],[392,487]],'#4f743c');line(640,653,0,294,'#fff8',2);line(640,653,1280,294,'#fff8',2);for(let i=0;i<4;i++){const [x,y]=fieldPoint(i);poly([[x-7,y],[x,y-4],[x+7,y],[x,y+4]],'#fff8df')}
 const h=tv.hit,t=Math.min(1,(now-tv.start)/2000);const x=640+(h.x-640)*t,y=645+(h.y-645)*t-Math.sin(t*Math.PI)*160;const ft=Math.min(1,t*1.15),fx=h.fielder[0]+(h.x-h.fielder[0])*ft,fy=h.fielder[1]+(h.y-h.fielder[1])*ft;const fs=1-h.batSide;person(fx,fy,.75,teamFor(fs).color,Math.sin(t*35)*.1);[[920,480],[350,475],[600,414],[725,434]].forEach(p=>person(p[0],p[1],.64,teamFor(fs).color));oval(640,530,45,16,'#b98d63');person(640,530,.7,teamFor(fs).color);oval(640+(h.x-640)*t,645+(h.y-645)*t,7,3,'#0004');oval(x,y,6,6,'#fff');ctx.strokeStyle='#f5cf6c';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.ellipse(h.x,h.y,21,9,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);if(t>.9){ctx.fillStyle='#f9dc86';ctx.font='bold 14px system-ui';ctx.fillText(h.type==='HR'?'飛越全壘打牆':'落點',h.x,h.y-25)}
 const advance=h.type==='HR'?4:h.type==='2B'?2:h.type==='OUT'?0:1;function runner(from,steps){const progress=Math.min(steps,t*steps);const k=Math.floor(progress),frac=progress-k;const a=fieldPoint((from+k)%4),b=fieldPoint((from+k+1)%4);person(a[0]+(b[0]-a[0])*frac,a[1]+(b[1]-a[1])*frac,.6,teamFor(h.batSide).color)}runner(3,advance);h.runners.forEach((r,i)=>{if(r)runner(i,Math.min(advance,3-i))});ctx.fillStyle='#fffe';ctx.font='13px system-ui';ctx.textAlign='left';ctx.fillText('BALL TRACKING CAM · 擊球後追球鏡頭',20,690);ctx.textAlign='center';}
let lastFrame=performance.now();
function loop(now){requestAnimationFrame(loop);if(document.hidden||$('#gameScreen').classList.contains('hidden')){lastFrame=now;return}try{const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;const pads=navigator.getGamepads?navigator.getGamepads():[];const pad=Array.from(pads).find(p=>p&&p.connected);tv.connected=!!pad;$('#controllerStatus').textContent=pad?'● 搖桿已連線 · '+pad.id:'○ 鍵盤 / 觸控模式 · 接上搖桿後按任一鍵啟用';
 if(pad){const down=pad.buttons.map(b=>b.pressed);function pressed(i){return down[i]&&!tv.lastButtons[i]}if(pressed(0))controlDown();if(!down[0]&&tv.lastButtons[0])controlUp();if(pressed(1))closeModal();if(pressed(2)&&playerBatting()){tv.power=!tv.power;render()}if(pressed(3))openPauseMenu();if(pressed(4))cyclePitch(-1);if(pressed(5))cyclePitch(1);if(pressed(9))openPauseMenu();if(!$('#setupScreen').classList.contains('hidden')){if(pressed(14))chooseTeam(-1);if(pressed(15))chooseTeam(1);if(pressed(12)||pressed(13))setMode(state.mode==='single'?'season':'single')}if($('#modalRoot').innerHTML){const opts=[...$('#modalRoot').querySelectorAll('.roster-option')];if(pressed(12))tv.selectedMenu=(tv.selectedMenu-1+opts.length)%opts.length;if(pressed(13))tv.selectedMenu=(tv.selectedMenu+1)%opts.length;opts.forEach((b,i)=>b.style.borderColor=i===tv.selectedMenu?'#ffd465':'#527087')}if(!tv.paused&&pad.axes){tv.aim.x=Math.max(-1.6,Math.min(1.6,tv.aim.x+(Math.abs(pad.axes[0])>.16?pad.axes[0]:0)*dt*2.5));tv.aim.y=Math.max(-1.6,Math.min(1.6,tv.aim.y+(Math.abs(pad.axes[1])>.16?pad.axes[1]:0)*dt*2.5))}tv.lastButtons=down}
 if(!tv.paused){tv.aim.x=Math.max(-1.6,Math.min(1.6,tv.aim.x+((tv.keys.has('ArrowRight')?1:0)-(tv.keys.has('ArrowLeft')?1:0))*dt*2));tv.aim.y=Math.max(-1.6,Math.min(1.6,tv.aim.y+((tv.keys.has('ArrowDown')?1:0)-(tv.keys.has('ArrowUp')?1:0))*dt*2));if(tv.phase==='windup'&&now-tv.start>900)beginPitch();if(tv.phase==='pitch'&&!playerBatting()&&tv.flight.cpuSwing&&!tv.swung&&now-tv.start>tv.flight.duration*.84){tv.swung=true;tv.swingStart=now}if(tv.phase==='pitch'&&now-tv.start>tv.flight.duration)finishPitch();if(tv.phase==='hit'&&now-tv.start>2600){const type=tv.hit.type;tv.phase='result';tv.start=now;applyHit(type)}if(tv.phase==='result'&&now-tv.start>1500&&!state.over)resultReset()}
 if(tv.phase==='hit'&&tv.hit)drawHitScene(tv.paused?tv.pauseAt:now);else drawPitchScene(tv.paused?tv.pauseAt:now);$('#tvPause').textContent=tv.paused?'☰ 選單':'☰ 暫停';$('#tvCall').textContent=tv.paused?'PAUSED':now<tv.callUntil?tv.call:'';stage.classList.toggle('is-paused',tv.paused);stage.classList.toggle('is-batting',playerBatting());}catch(error){console.error('Game frame',error);tv.phase='ready';tv.flight=null;tv.hit=null;state.busy=false;tv.paused=true;tv.pauseAt=now;$('#tvPause').textContent='繼續';announce('請按繼續');}}
requestAnimationFrame(loop);
