/* Official roster snapshots, game selections and online cheer-song bindings. */
const rosterState={data:window.CPBL_ROSTER,selectedStarters:{},squads:null,used:[new Set(),new Set()],syncing:false};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const verifiedPitchers=new Map(PITCHERS.concat(EXTRA_PITCHER).map(p=>[p.name,p]));
function rosterTeam(index){return rosterState.data?.teams.find(t=>t.index===index)}
function rosterPlayers(index){return rosterTeam(index)?.players||[]}
function pitchProfile(player){const verified=verifiedPitchers.get(player.name);return {...(verified||{hand:'?',style:'over',pitches:['四縫線','滑球','變速球'],speed:143}),name:player.name,id:player.id,number:player.number,level:player.level,source:verified?.source||player.source,rosterSource:player.source,verified:!!verified};}
function starterFor(index){const candidates=rosterPlayers(index).filter(p=>p.isPitcher);return candidates.find(p=>p.id===rosterState.selectedStarters[index])||candidates.find(p=>p.level===1&&verifiedPitchers.has(p.name))||candidates.find(p=>p.level===1)||candidates[0]}
function lineupFor(index){const players=rosterPlayers(index).filter(p=>!p.isPitcher);const previous=PLAYERS[index];return previous.map(name=>players.find(p=>p.name===name&&p.level===1)).filter(Boolean).concat(players.filter(p=>p.level===1&&!previous.includes(p.name))).concat(players.filter(p=>p.level===2)).filter((p,i,all)=>all.findIndex(x=>x.id===p.id)===i).slice(0,9)}
const rosterStart=startGame;
startGame=function(index){if(!rosterState.data){announce('名單尚未載入');return}const lineups=TEAMS.map((_,i)=>lineupFor(i));lineups.forEach((players,i)=>{PLAYERS[i]=players.map(p=>p.name)});rosterStart(index);rosterState.squads=[rosterPlayers(state.awayIndex).map(p=>({...p})),rosterPlayers(state.homeIndex).map(p=>({...p}))];tv.pitchers=[pitchProfile(starterFor(state.awayIndex)),pitchProfile(starterFor(state.homeIndex))];rosterState.used=tv.pitchers.map(p=>new Set([p.id]));tv.lineupIds=[lineups[state.awayIndex].map(p=>p.id),lineups[state.homeIndex].map(p=>p.id)];render()};
const rosterRender=render;
render=function(){rosterRender();const p=activePitcher();const stats=$('#tvDuel p');if(stats)stats.textContent=tv.pitchCount[fieldingTeam()]+' 球 · '+(p.verified?'公開球種資料':'球種待查證・通用遊戲設定');const title=$('#tvDuel small');if(title)title.textContent='PITCHER · '+(p.hand==='?'?'投打資料待補':p.hand+'HP')+(p.number?' · #'+p.number:'');};
const rosterInfo=document.createElement('div');rosterInfo.className='roster-info';rosterInfo.innerHTML='<span id="rosterStamp"></span><button id="rosterRefresh">↻ 更新名單</button><button id="rosterBrowse">球員名單 / 選先發</button>';
$('.setup-card').append(rosterInfo);
function rosterStamp(message){const data=rosterState.data;$('#rosterStamp').textContent=message||(data?'官網名單 · '+new Date(data.updatedAt).toLocaleString('zh-TW')+' · '+data.teams.reduce((s,t)=>s+t.players.length,0)+' 人':'名單載入中');}
rosterStamp();$('#rosterRefresh').onclick=()=>syncRosters(true);$('#rosterBrowse').onclick=()=>openRoster(+$('#teamSelect').value,'starter');
async function syncRosters(manual=false){if(rosterState.syncing)return;rosterState.syncing=true;if(manual)rosterStamp('正在讀取最新官網名單快照…');try{const base=location.protocol==='file:'?'https://yanlunchen1113.github.io/cpbl-baseball-manager/':'';const response=await fetch(base+'data/rosters.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);const data=await response.json();if(data.schemaVersion!==1||data.teams?.length!==6||data.teams.some(t=>t.players.length<25||!t.players.some(p=>p.isPitcher)))throw Error('名單不完整');const changed=data.updatedAt!==rosterState.data?.updatedAt;rosterState.data=data;rosterStamp();if(manual)rosterStamp((changed?'已讀取新名單':'目前已是最新發布名單')+' · '+new Date(data.updatedAt).toLocaleString('zh-TW'));if(manual&&changed&&!$('#gameScreen').classList.contains('hidden'))announce('新名單將在下一場套用');}catch(error){if(manual)rosterStamp('更新暫時失敗，繼續使用已保存的官網名單。');}finally{rosterState.syncing=false}}
syncRosters();setInterval(()=>syncRosters(),5*60*1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncRosters()});
function openRoster(index,mode='browse',level='all',query=''){tv.selectedMenu=0;const side=mode==='bullpen'?state.playerSide:mode==='pinch'?state.playerSide:null,players=side===null?rosterPlayers(index):rosterState.squads[side];const list=players.filter(p=>(mode==='pinch'?!p.isPitcher:mode==='browse'?true:p.isPitcher)&&(level==='all'||p.level===+level)&&p.name.includes(query));const heading=mode==='starter'?'選擇先發投手':mode==='bullpen'?'牛棚換投':mode==='pinch'?'選擇代打':'球員名單';modal(TEAMS[index].name+' · '+heading,'一、二軍依官網分類。二軍投手可在這個遊戲中啟用；同場已退場投手不能再次登板。','<div class="roster-filters"><select id="rosterLevel"><option value="all">全部軍別</option><option value="1">一軍</option><option value="2">二軍</option></select><input id="rosterQuery" placeholder="搜尋球員姓名" value="'+esc(query)+'"></div><p id="rosterTotal">'+list.length+' 位球員 · 搖桿上下選擇、A 確認</p><div class="full-roster">'+list.map(p=>{const used=mode==='bullpen'&&rosterState.used[state.playerSide].has(p.id),current=mode==='pinch'&&tv.lineupIds[state.playerSide].includes(p.id);return '<button class="roster-option" data-player="'+esc(p.id)+'" '+(used||current?'disabled':'')+'><strong>#'+esc(p.number)+' '+esc(p.name)+'<span>'+p.level+'軍</span></strong><small>'+esc(p.position)+' · '+(p.isPitcher?(verifiedPitchers.has(p.name)?verifiedPitchers.get(p.name).pitches.join(' / '):'球種待查證・通用遊戲設定'):'可用球員')+(used?' · 本場已登板':current?' · 已在打線':'')+'</small></button>'}).join('')+'</div><p><a target="_blank" rel="noopener" href="https://stats.cpbl.com.tw/players">查看中職官網資料</a> · 自動同步每小時執行，實際更新依 GitHub 排程及官網回應。</p>');$('#rosterLevel').value=level;$('#rosterLevel').onchange=e=>openRoster(index,mode,e.target.value,$('#rosterQuery').value);$('#rosterQuery').onchange=e=>openRoster(index,mode,$('#rosterLevel').value,e.target.value);$('.full-roster').querySelectorAll('[data-player]').forEach(button=>button.onclick=()=>{const player=players.find(p=>p.id===button.dataset.player);if(mode==='starter'){rosterState.selectedStarters[index]=player.id;closeModal();rosterStamp('先發投手：'+player.name+' · '+player.level+'軍')}else if(mode==='bullpen'){tv.pitchers[state.playerSide]=pitchProfile(player);rosterState.used[state.playerSide].add(player.id);tv.pitchCount[state.playerSide]=0;tv.pitchIndex=0;closeModal();render();announce('換投 · '+player.name)}else if(mode==='pinch'){const order=state.orders[state.playerSide]%9;PLAYERS[playerTeamIndex()][order]=player.name;tv.lineupIds[state.playerSide][order]=player.id;closeModal();render();announce('代打 · '+player.name)}else window.open(player.source,'_blank','noopener')});}
openCoach=function(){if(tv.phase!=='ready'||state.over)return;tv.selectedMenu=0;const defending=!playerBatting();modal('教練調度','完整球員名單・A 確認 / B 返回','<button class="roster-option" id="fullBullpen" '+(!defending?'disabled':'')+'><strong>牛棚換投</strong><small>'+rosterState.squads[state.playerSide].filter(p=>p.isPitcher).length+' 位投手 · 一、二軍</small></button><button class="roster-option" id="fullPinch" '+(defending?'disabled':'')+'><strong>代打</strong><small>選擇打線以外的球員取代本打席</small></button><button class="roster-option" id="fullSteal" '+(defending?'disabled':'')+'><strong>盜二壘</strong><small>一壘有人、二壘空時可用</small></button><button class="roster-option" id="fullDefense" '+(!defending?'disabled':'')+'><strong>守備佈陣：'+(tv.strategy==='deep'?'外野後退':'標準')+'</strong></button>');$('#fullBullpen').onclick=()=>openRoster(playerTeamIndex(),'bullpen');$('#fullPinch').onclick=()=>openRoster(playerTeamIndex(),'pinch');$('#fullSteal').onclick=()=>{if(!state.bases[0]||state.bases[1]){announce('沒有可盜二壘的跑者');return}closeModal();steal();render()};$('#fullDefense').onclick=()=>{tv.strategy=tv.strategy==='deep'?'normal':'deep';closeModal();announce(tv.strategy==='deep'?'外野後退':'標準守備')};};
$('.rules-note p').textContent='六隊官網一、二軍球員名單，每小時同步。未有來源的球種使用標示過的通用遊戲設定。';

// Official songs selected automatically; no local import or manual bindings.
const CHEER_SONGS=[
 {id:'Rv395b316ic',title:'2022 感動黃潮',team:0,channel:'CTBC Brothers 中信兄弟官方頻道',source:'https://www.youtube.com/watch?v=Rv395b316ic'},
 {id:'0NolTgGUYt8',title:'2022 Rise Up',team:2,channel:'Rakuten Monkeys',source:'https://www.youtube.com/watch?v=0NolTgGUYt8'},
 {id:'rXIBzxbTctk',title:'統一尚勇',team:1,kind:'chance',channel:'統一獅 Uni Lions',source:'https://www.youtube.com/watch?v=rXIBzxbTctk'},
 {id:'po6DnlJZfm8',title:'最強統一獅',team:1,channel:'統一獅 Uni Lions',source:'https://www.youtube.com/watch?v=po6DnlJZfm8'},
 {id:'n5XjIxbSeYE',title:'江坤宇應援曲',team:0,batter:'江坤宇',channel:'CTBC Brothers 中信兄弟棒球隊 - Topic'},
 {id:'ZdAvmv8cXvg',title:'張育成 應援詞曲＆口號 完整版',team:3,batter:'張育成',channel:'Fubon Guardians 富邦悍將'},
 {id:'_OAH-yqZf5c',title:'王柏融應援曲',team:5,batter:'王柏融',channel:'台鋼雄鷹 TSG HAWKS'},
 {id:'FOD9lwtWww4',title:'TEAM FUBON',team:3,channel:'富邦悍將官網應援曲'},
 {id:'1ygsE7hnK_E',title:'藍色力量',team:3,kind:'chance',channel:'富邦悍將官網應援曲'},
 {id:'dramyYZUFGM',title:'藍色力量（另一版本）',team:3,kind:'chance',channel:'富邦悍將官網應援曲'},
 {id:'9VCZoqXNAjg',title:'轟出去',team:3,kind:'chance',channel:'富邦悍將官網應援曲'},
 {id:'-FCUSt4ArDM',title:'戰到底',team:3,kind:'chance',channel:'富邦悍將官網應援曲'},
 {id:'SWOTL2lNdm0',title:'ＫＫＫ',team:3,channel:'富邦悍將官網應援曲'},
 {id:'QREqUSCVdOg',title:'全富舞莊',team:3,channel:'富邦悍將官網應援曲'},
 {id:'gPX0KMG1sfY',title:'謝謝你的保送',team:3,channel:'富邦悍將官網應援曲'},
 {id:'Uph9Iikb0m8',title:'VICTORY',team:3,channel:'富邦悍將官網應援曲'},
 {id:'3kQtY_-nV0I',title:'相信悍將 out版',team:3,channel:'富邦悍將官網應援曲'}
];
CHEER_SONGS.push(...[{"team": 5, "order": 0, "url": "https://www.tsghawks.com/wp-content/uploads/2023/03/01-第一棒-B段二胡.mp3", "title": "第1棒鷹援歌", "source": "https://www.tsghawks.com/fan/download/"}, {"team": 5, "order": 1, "url": "https://www.tsghawks.com/wp-content/uploads/2023/03/02-第二棒-中國笛-.mp3", "title": "第2棒鷹援歌", "source": "https://www.tsghawks.com/fan/download/"}, {"team": 5, "order": 2, "url": "https://www.tsghawks.com/wp-content/uploads/2023/03/03-第三棒-嗩吶.mp3", "title": "第3棒鷹援歌", "source": "https://www.tsghawks.com/fan/download/"}, {"team": 5, "order": 3, "url": "https://www.tsghawks.com/wp-content/uploads/2023/03/04-第四棒-前奏琵琶.mp3", "title": "第4棒鷹援歌", "source": "https://www.tsghawks.com/fan/download/"}, {"team": 5, "order": 4, "url": "https://www.tsghawks.com/wp-content/uploads/2023/03/05-第五棒-琵琶-online-audio-converter.com_.mp3", "title": "第5棒鷹援歌", "source": "https://www.tsghawks.com/fan/download/"}, {"team": 5, "order": 5, "url": "https://www.tsghawks.com/wp-content/uploads/2023/03/06-第六棒-嗩吶.mp3", "title": "第6棒鷹援歌", "source": "https://www.tsghawks.com/fan/download/"}, {"team": 5, "order": 6, "url": "https://www.tsghawks.com/wp-content/uploads/2023/03/07-第七棒-原.mp3", "title": "第7棒鷹援歌", "source": "https://www.tsghawks.com/fan/download/"}, {"team": 5, "order": 7, "url": "https://www.tsghawks.com/wp-content/uploads/2023/03/08-第八棒-二胡楊琴.mp3", "title": "第8棒鷹援歌", "source": "https://www.tsghawks.com/fan/download/"}, {"team": 5, "order": 8, "url": "https://www.tsghawks.com/wp-content/uploads/2023/03/09-第九棒-原.mp3", "title": "第9棒鷹援歌", "source": "https://www.tsghawks.com/fan/download/"}, {"team": 4, "kind": "chance", "id": "4YSO7RTK_4A", "title": "2026 龍之怒吼", "source": "https://www.wdragons.com/年度嗆司曲/"}, {"team": 4, "kind": "chance", "id": "oPKvkNtlg2g", "title": "2025 Let’s Goal！上吧！", "source": "https://www.wdragons.com/年度嗆司曲/"}]);
const videoDock=document.createElement('section');videoDock.className='cheer-player hidden';videoDock.innerHTML='<div><strong id="cheerTitle">官方應援</strong><button id="cheerStop">關閉</button></div><iframe id="cheerFrame" title="官方應援曲播放器" allow="autoplay; encrypted-media; picture-in-picture" referrerpolicy="strict-origin-when-cross-origin"></iframe><small>如未自動播放，點播放器播放鍵。</small>';stage.append(videoDock);
let cheerVideoKey='',cheerAudio=null;
musicStop=function(){cheerVideoKey='';tv.musicKey='';if(cheerAudio){cheerAudio.pause();cheerAudio=null}$('#cheerFrame').removeAttribute('src');videoDock.classList.add('hidden')};
musicUpdate=function(){
 if(!musicEnabled||tv.paused||state.over||$('#gameScreen').classList.contains('hidden')){musicStop();$('#musicInfo').textContent=musicEnabled?'應援待機':'應援關閉';return}
 const team=battingTeam()?state.homeIndex:state.awayIndex,chance=!!(state.bases[1]||state.bases[2]),order=state.orders[battingTeam()]%9;
 const song=(chance?CHEER_SONGS.find(s=>s.team===team&&s.kind==='chance'):null)||CHEER_SONGS.find(s=>s.team===team&&s.batter===batterName())||CHEER_SONGS.find(s=>s.team===team&&s.order===order)||CHEER_SONGS.find(s=>s.team===team&&!s.batter&&s.kind!=='chance'&&s.order===undefined)||CHEER_SONGS.find(s=>s.team===team&&s.kind==='chance');
 if(!song){if(cheerVideoKey)musicStop();$('#musicInfo').textContent='此球隊尚無可播放的已確認音源';return}
 const key=team+':'+(song.url||song.id);if(key===cheerVideoKey)return;musicStop();cheerVideoKey=key;tv.musicKey=key;$('#musicInfo').textContent='應援 · '+song.title;
 if(song.url){cheerAudio=new Audio(song.url);cheerAudio.loop=true;cheerAudio.volume=.3;cheerAudio.play().catch(()=>{$('#musicInfo').textContent='點音樂啟用 · '+song.title});return}
 videoDock.classList.remove('hidden');$('#cheerTitle').textContent=song.title;$('#cheerFrame').src='https://www.youtube.com/embed/'+song.id+'?autoplay=1&loop=1&playlist='+song.id+'&playsinline=1&rel=0';
};
$('#cheerStop').onclick=()=>{musicEnabled=false;musicStop()};
openMusic=function(){audioUnlock();modal('球場聲音','依打者、棒次及得點圈情境自動選曲。官網音檔直接播放；官方影片使用原播放器。', '<label class="music-row"><input type="checkbox" id="musicOn" '+(musicEnabled?'checked':'')+'> 應援曲</label><label class="music-row"><input type="checkbox" id="effectsOn" '+(effectsEnabled?'checked':'')+'> 球棒及手套音效</label><div>'+TEAMS.map((t,i)=>'<p><strong>'+t.name+'</strong> · '+CHEER_SONGS.filter(s=>s.team===i).length+' 首已確認音源</p>').join('')+'</div><p><a href="https://www.tsghawks.com/fan/download/" target="_blank" rel="noopener">台鋼官網應援歌</a> · <a href="https://www.fubonguardians.com/content/info/Songs" target="_blank" rel="noopener">富邦官網應援曲</a> · <a href="https://www.wdragons.com/年度嗆司曲/" target="_blank" rel="noopener">味全龍嗆司曲</a></p>');$('#musicOn').onchange=e=>{musicEnabled=e.target.checked;musicUpdate()};$('#effectsOn').onchange=e=>effectsEnabled=e.target.checked;musicUpdate();};
$('#tvMusic').onclick=openMusic;
