/* Six-team, 120-game balanced regular season and CPBL postseason routes.
   Source: CPBL regulations, chapter 12, article 60. Calendar is generated. */
function blankTable(){return TEAMS.map((_,i)=>({i,w:0,l:0,t:0,rf:0,ra:0}))}
function rate(row){return row.w/(row.w+row.l||1)}
function ranked(table){return [...table].sort((a,b)=>rate(b)-rate(a)||(b.rf-b.ra)-(a.rf-a.ra)||a.i-b.i)}
function seasonSchedule(){let wheel=[0,1,2,3,4,5],five=[];for(let r=0;r<5;r++){five.push([[wheel[0],wheel[5]],[wheel[1],wheel[4]],[wheel[2],wheel[3]]]);wheel=[wheel[0],wheel[5],...wheel.slice(1,5)]}return Array.from({length:120},(_,r)=>five[r%5].map(([a,b])=>Math.floor(r/5)%2?{away:b,home:a}:{away:a,home:b}));}
newSeason=team=>({version:3,team,game:0,total:120,round:0,schedule:seasonSchedule(),standings:blankTable(),halves:[blankTable(),blankTable()],results:[],phase:'regular',halfChampions:[],playoff:null,final:null,champion:null,tiebreaks:[],tieTask:null});
state.season=null;try{const saved=JSON.parse(localStorage.getItem('cpbl-season-v3'));if(saved?.version===3)state.season=saved}catch(e){}
function saveSeason(){localStorage.setItem('cpbl-season-v3',JSON.stringify(state.season))}
function addResult(table,fixture,runs){const a=table[fixture.away],h=table[fixture.home];a.rf+=runs[0];a.ra+=runs[1];h.rf+=runs[1];h.ra+=runs[0];if(runs[0]===runs[1]){a.t++;h.t++}else{(runs[0]>runs[1]?a:h).w++;(runs[0]>runs[1]?h:a).l++}}
function simRuns(draw=true){let a=Math.floor(Math.random()*8),h=Math.floor(Math.random()*8);if(!draw&&a===h)h++;return [a,h]}
function decideChampion(table,callback){const ranks=ranked(table),top=ranks.filter(r=>Math.abs(rate(r)-rate(ranks[0]))<1e-10);if(top.length===1){callback(top[0].i);return}state.season.tieTask={teams:top.map(r=>r.i),winner:top[0].i,opponent:1,callback};state.season.phase='tiebreak';}
function resumeTieCallback(task,winner){const s=state.season;if(task==='first'){s.halfChampions[0]=winner;s.phase='regular'}else if(task==='second'){s.halfChampions[1]=winner;seedPostseason()}else if(task==='direct'){seedWithDirect(winner)}}
function finishHalf(half){const s=state.season,ranks=ranked(s.halves[half]),tied=ranks.filter(r=>Math.abs(rate(r)-rate(ranks[0]))<1e-10);if(tied.length>1){s.tieTask={teams:tied.map(r=>r.i),winner:tied[0].i,opponent:1,callback:half===0?'first':'second'};s.phase='tiebreak'}else{s.halfChampions[half]=ranks[0].i;if(half===1)seedPostseason()}}
function seedWithDirect(direct){const s=state.season,other=s.halfChampions.find(i=>i!==direct),wild=ranked(s.standings).find(r=>!s.halfChampions.includes(r.i)).i;s.direct=direct;s.playoff={teams:[other,wild],wins:[1,0],need:3,games:0};s.phase='playoff';}
function seedPostseason(){const s=state.season,[a,b]=s.halfChampions,r=ranked(s.standings);if(a===b){s.direct=a;s.sweep=true;s.playoff={teams:r.filter(x=>x.i!==a).slice(0,2).map(x=>x.i),wins:[0,0],need:3,games:0};s.phase='playoff'}else if(Math.abs(rate(s.standings[a])-rate(s.standings[b]))<1e-10){s.tieTask={teams:[a,b],winner:a,opponent:1,callback:'direct'};s.phase='tiebreak'}else seedWithDirect(rate(s.standings[a])>rate(s.standings[b])?a:b)}
function nextFixture(){const s=state.season;if(s.phase==='regular')return s.schedule[s.round].find(f=>f.away===s.team||f.home===s.team);if(s.phase==='tiebreak'){return {away:s.tieTask.teams[s.tieTask.opponent],home:s.tieTask.winner}}const series=s.phase==='playoff'?s.playoff:s.final;if(!series||s.phase==='complete')return null;const flip=series.games%2;return {away:series.teams[1-flip],home:series.teams[flip]};}
function recordSeries(fixture,runs){const s=state.season,winner=runs[0]>runs[1]?fixture.away:fixture.home;s.results.push({phase:s.phase,fixture,runs});if(s.phase==='tiebreak'){const task=s.tieTask;task.winner=winner;task.opponent++;if(task.opponent>=task.teams.length){s.tiebreaks.push({teams:task.teams,winner});s.tieTask=null;resumeTieCallback(task.callback,winner)}return}const series=s.phase==='playoff'?s.playoff:s.final;series.wins[series.teams.indexOf(winner)]++;series.games++;if(Math.max(...series.wins)>=series.need){if(s.phase==='playoff'){s.final={teams:[s.direct,winner],wins:[s.sweep?1:0,0],need:4,games:0};s.phase='final'}else{s.champion=winner;s.phase='complete'}}}
recordSeasonGame=function(){if(state.seasonRecorded)return;state.seasonRecorded=true;const s=state.season,fixture={away:state.awayIndex,home:state.homeIndex};if(s.phase==='regular'){const half=s.round<60?0:1;for(const f of s.schedule[s.round]){const runs=f.away===fixture.away&&f.home===fixture.home?state.runs.slice():simRuns();addResult(s.standings,f,runs);addResult(s.halves[half],f,runs);s.results.push({round:s.round,phase:'regular',fixture:f,runs})}s.round++;s.game=s.round;if(s.round===60)finishHalf(0);if(s.round===120)finishHalf(1)}else recordSeries(fixture,state.runs.slice());saveSeason()};
const beforeSeasonStart=startGame;
startGame=function(index){let fixture;if(state.mode==='season')fixture=nextFixture();else{const chosen=$('#opponentSelect').value;fixture={home:index,away:chosen==='random'?[0,1,2,3,4,5].filter(i=>i!==index)[Math.floor(Math.random()*5)]:+chosen}}if(!fixture)return;state.playerSide=1;beforeSeasonStart(index);state.homeIndex=fixture.home;state.awayIndex=fixture.away;state.playerSide=fixture.home===index?1:0;state.seasonRecorded=false;state.postseason=state.mode==='season'&&state.season.phase!=='regular';tv.pitchers=[pitchProfile(starterFor(fixture.away)),pitchProfile(starterFor(fixture.home))];rosterState.squads=[rosterPlayers(fixture.away).map(p=>({...p})),rosterPlayers(fixture.home).map(p=>({...p}))];rosterState.used=tv.pitchers.map(p=>new Set([p.id]));tv.lineupIds=[lineupFor(fixture.away).map(p=>p.id),lineupFor(fixture.home).map(p=>p.id)];$('#stadiumName').textContent=TEAMS[fixture.home].stadium;render();announce(state.postseason?'季後賽 · PLAY BALL':'PLAY BALL');};
const regularEndHalf=endHalf;
endHalf=function(){if(!state.postseason){regularEndHalf();return}resetCount();state.outs=0;state.bases=[null,null,null];if(state.half==='top'){if(state.inning>=9&&state.runs[1]>state.runs[0]){state.over=true;finishGame();return}state.half='bottom'}else{if(state.inning>=9&&state.runs[0]!==state.runs[1]){state.over=true;finishGame();return}state.inning++;state.half='top'}};
const opponentBox=document.createElement('div');opponentBox.className='opponent-chooser';opponentBox.innerHTML='<label for="opponentSelect">單場對手</label><select id="opponentSelect"></select>';$('.opponent-preview').replaceWith(opponentBox);
updateOpponent=function(){const index=+$('#teamSelect').value,selected=$('#opponentSelect').value;$('#opponentSelect').innerHTML='<option value="random">隨機對手 · 每場重新抽選</option>'+TEAMS.map((t,i)=>i!==index?'<option value="'+i+'">'+t.name+'</option>':'').join('');if(selected!==String(index)&&[...$('#opponentSelect').options].some(o=>o.value===selected))$('#opponentSelect').value=selected;$('#teamChoice').textContent=TEAMS[index].name;if(state.mode==='season')refreshSeasonSummary();};updateOpponent();$('#teamSelect').onchange=updateOpponent;
const previousSetMode=setMode;
setMode=function(mode){previousSetMode(mode);$('#seasonLabel').innerHTML='<i></i> 2026 球季・'+(mode==='season'?'賽季模式':'單場模式');$('#setupTitle').textContent=mode==='season'?'120 場・上下半季・季後賽':'自由對戰';$('#setupFoot').textContent=mode==='season'?'對每隊 24 場，主客各 12 場；自動儲存進度':'選擇對手或每場隨機抽選';opponentBox.classList.toggle('hidden',mode==='season')};
refreshSeasonSummary=function(){const team=+$('#teamSelect').value;if(!state.season||state.season.team!==team)state.season=newSeason(team);const s=state.season,me=s.standings[team];$('#seasonSummary').innerHTML='<b>'+TEAMS[team].name+'</b> · '+s.game+'/120 場<br>'+me.w+' 勝 '+me.l+' 敗 '+me.t+' 和 · '+({regular:s.round<60?'上半季':'下半季',tiebreak:'冠軍加賽',playoff:'季後挑戰賽',final:'台灣大賽',complete:'賽季完成'}[s.phase]);};
function advanceSeason(simulate=false){const s=state.season;if(s.phase==='complete')return;const fixture=nextFixture();if(!fixture)return;const included=fixture.away===s.team||fixture.home===s.team;if(!simulate&&included){startGame(s.team);return}if(s.phase==='regular'){const half=s.round<60?0:1;for(const f of s.schedule[s.round]){const runs=simRuns();addResult(s.standings,f,runs);addResult(s.halves[half],f,runs);s.results.push({round:s.round,phase:'regular',fixture:f,runs})}s.round++;s.game=s.round;if(s.round===60)finishHalf(0);if(s.round===120)finishHalf(1)}else recordSeries(fixture,simRuns(false));saveSeason();renderSeason();}
$('#nextSeasonGame').onclick=()=>advanceSeason();const simButton=document.createElement('button');simButton.className='secondary-game-button';simButton.textContent='模擬下一場';simButton.onclick=()=>advanceSeason(true);$('#nextSeasonGame').after(simButton);const simHalf=document.createElement('button');simHalf.className='secondary-game-button';simHalf.textContent='模擬至半季結束';simHalf.onclick=()=>{const s=state.season;if(s.phase!=='regular')return;const limit=s.round<60?60:120;while(s.phase==='regular'&&s.round<limit)advanceSeason(true)};simButton.after(simHalf);
renderSeason=function(){const s=state.season;if(!s)return;const labels={regular:s.round<60?'上半季':'下半季',tiebreak:'冠軍加賽',playoff:'季後挑戰賽 · 五戰三勝',final:'台灣大賽 · 七戰四勝',complete:'年度總冠軍：'+(s.champion===null?'':TEAMS[s.champion].name)};$('#seasonTeamTitle').textContent=TEAMS[s.team].name+' · '+labels[s.phase];const me=s.standings[s.team];$('#seasonProgress').innerHTML='<div class="season-stat"><span>全年戰績</span><strong>'+me.w+'–'+me.l+'–'+me.t+'</strong></div><div class="progress-bar"><i style="width:'+s.round/120*100+'%"></i></div><p>'+s.round+'/120 場 · 每個對手 24 場</p>'+s.halfChampions.map((team,i)=>'<p>'+(i?'下':'上')+'半季冠軍：'+TEAMS[team].name+'</p>').join('');const f=nextFixture();$('#nextSeasonGame').disabled=!f;$('#nextSeasonGame').textContent=f?((f.away===s.team||f.home===s.team)?'進入比賽':'模擬季後賽')+' · '+TEAMS[f.away].mark+' @ '+TEAMS[f.home].mark:'賽季完成';simButton.disabled=!f;simHalf.disabled=s.phase!=='regular';$('#standingsTable').innerHTML='<div class="stand-row"><b>#</b><b>球隊</b><b>勝–敗–和</b><b>勝率</b></div>'+ranked(s.standings).map((r,i)=>'<div class="stand-row '+(r.i===s.team?'me':'')+'"><span>'+(i+1)+'</span><span>'+TEAMS[r.i].name+'</span><span>'+r.w+'–'+r.l+'–'+r.t+'</span><span>'+rate(r).toFixed(3)+'</span></div>').join('')+'<details><summary>上下半季戰績</summary>'+s.halves.map((table,i)=>'<h4>'+(i?'下':'上')+'半季</h4>'+ranked(table).map(r=>'<p>'+TEAMS[r.i].name+' '+r.w+'–'+r.l+'–'+r.t+'</p>').join('')).join('')+'</details>';if(s.phase==='regular')$('#scheduleList').innerHTML=s.schedule.slice(s.round,s.round+6).map((matches,i)=>{const f=matches.find(g=>g.away===s.team||g.home===s.team);return '<div class="schedule-item">第 '+(s.round+i+1)+' 場 <b>'+TEAMS[f.away].name+' @ '+TEAMS[f.home].name+'</b></div>'}).join('');else{$('#scheduleList').innerHTML=[s.playoff,s.final].filter(Boolean).map((series,i)=>'<div class="series-card"><h4>'+(i?'台灣大賽':'季後挑戰賽')+'</h4><b>'+TEAMS[series.teams[0]].name+' '+series.wins[0]+' : '+series.wins[1]+' '+TEAMS[series.teams[1]].name+'</b></div>').join('')+(s.phase==='tiebreak'?'<p>同勝率冠軍加賽</p>':'')}$('#scheduleList').innerHTML+='<p class="league-source"><a href="https://www.cpbl.com.tw/about/structure" target="_blank" rel="noopener">中職賽制來源</a> · 均衡賽程由遊戲產生，非官網實際日期表。</p>';};
const finalSeasonRender=render;render=function(){finalSeasonRender();$('.home-side small').textContent='主場'+(state.playerSide===1?' · 你':'');$('.team-side:not(.home-side) small').textContent='客場'+(state.playerSide===0?' · 你':'');};
// Mobile direct manipulation: drag anywhere on the field to aim; one thumb taps swing.
stage.style.touchAction='none';let dragAim;
stage.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;dragAim={id:e.pointerId,x:e.clientX,y:e.clientY,aim:{...tv.aim}};stage.setPointerCapture(e.pointerId);audioUnlock()});
stage.addEventListener('pointermove',e=>{if(!dragAim||e.pointerId!==dragAim.id)return;const rect=stage.getBoundingClientRect();tv.aim.x=Math.max(-1.6,Math.min(1.6,dragAim.aim.x+(e.clientX-dragAim.x)/rect.width*5));tv.aim.y=Math.max(-1.6,Math.min(1.6,dragAim.aim.y+(e.clientY-dragAim.y)/rect.height*5))});
stage.addEventListener('pointerup',()=>dragAim=null);stage.addEventListener('pointercancel',()=>dragAim=null);canvas.onpointerdown=null;
const mobileHelp=document.createElement('p');mobileHelp.className='mobile-hint';mobileHelp.textContent='拖曳球場瞄準 · 守備時按住投球後放開 · 進攻時準備，球飛來就點揮棒';$('.field-panel').after(mobileHelp);
const mobileRender=render;render=function(){mobileRender();$('#tvAction').textContent=state.over?'返回':tv.phase==='pitch'?(playerBatting()?'揮棒！':'投球中'):tv.phase==='charge'?'放開出手':playerBatting()?'準備打擊':'按住投球';$('#tvPower').textContent=tv.power?'強振 ON':'強振';$('#tvCoach').textContent='調度';$('#tvPause').textContent=tv.paused?'☰ 選單':'☰ 暫停';};
