/* Real WebGL scene, articulated athletes, perspective broadcast cameras.
   Models are original game avatars; no claim of photographic player likeness. */
(function(){
 if(!window.THREE)return;
 const T=window.THREE;let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'default'})}catch(e){return}
 renderer.domElement.className='webgl-canvas';renderer.domElement.setAttribute('aria-label','3D 棒球轉播場景');stage.prepend(renderer.domElement);canvas.style.visibility='hidden';stage.classList.add('has-webgl');
 renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
 const scene=new T.Scene();scene.background=new T.Color('#9aabb8');scene.fog=new T.Fog('#9aabb8',130,260);const camera=new T.PerspectiveCamera(6.5,16/9,.1,400);
 scene.add(new T.HemisphereLight('#d4e7fa','#394721',1.2));const sun=new T.DirectionalLight('#fff0d4',2.8);sun.position.set(-35,55,30);sun.castShadow=true;sun.shadow.mapSize.set(768,768);Object.assign(sun.shadow.camera,{left:-65,right:65,top:100,bottom:-30,near:1,far:160});sun.shadow.bias=-.0015;sun.shadow.normalBias=.045;scene.add(sun);scene.add(sun.target);
 function mat(color,extra={}){return new T.MeshStandardMaterial({color,roughness:.8,...extra})}
 const white=mat('#e9e6d8'),soil=mat('#a88663'),grass=mat('#3e7040'),metal=mat('#627886',{metalness:.6}),skin=mat('#c59370'),dark=mat('#182735');
 function mesh(geometry,material,x=0,y=0,z=0,parent=scene){const o=new T.Mesh(geometry,material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 function box(w,h,d,m,x,y,z,parent){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,parent)}
 function sphere(r,m,x,y,z,parent){return mesh(new T.SphereGeometry(r,16,12),m,x,y,z,parent)}
 function cylinder(r,h,m,x,y,z,parent){return mesh(new T.CylinderGeometry(r,r,h,32),m,x,y,z,parent)}
 const ground=mesh(new T.PlaneGeometry(330,330),grass,0,-.03,70);ground.rotation.x=-Math.PI/2;ground.castShadow=false;
 for(let i=0;i<16;i++){const strip=mesh(new T.PlaneGeometry(8,180),mat(i%2?'#41784a':'#3c7146'),(i-8)*8,.001,75);strip.rotation.x=-Math.PI/2;strip.castShadow=false;}
 const dirtShape=new T.Shape();dirtShape.moveTo(0,0);dirtShape.lineTo(34,-34);dirtShape.absarc(0,0,Math.hypot(34,34),-Math.PI/4,-Math.PI*3/4,true);dirtShape.lineTo(0,0);const diamond=mesh(new T.ShapeGeometry(dirtShape,48),soil,0,.01,0);diamond.rotation.x=-Math.PI/2;diamond.castShadow=false;
 const center=box(24,.03,24,grass,0,.02,19.4);center.rotation.y=Math.PI/4;center.castShadow=false;
 cylinder(2.75,.28,soil,0,.12,18.44).castShadow=false;cylinder(4.7,.04,soil,0,.025,0).castShadow=false;box(.61,.04,.15,white,0,.29,18.44);
 const basePositions=CPBLPhysics.bases.map(p=>new T.Vector3(p.x,0,p.z));basePositions.slice(0,3).forEach(p=>box(.38,.1,.38,white,p.x,.04,p.z));box(.42,.04,.42,white,0,.07,0);
 function segment(a,b,r,m,parent=scene){const direction=new T.Vector3().subVectors(b,a);const o=mesh(new T.CylinderGeometry(r,r,direction.length(),14),m,0,0,0,parent);o.position.copy(a).add(b).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),direction.normalize());return o}
 [-1,1].forEach(side=>{segment(new T.Vector3(0,.02,0),new T.Vector3(side*110,.02,110),.025,white);const outline=[[-.8,0],[.8,0],[.8,1.8],[-.8,1.8],[-.8,0]];for(let i=1;i<outline.length;i++)segment(new T.Vector3(side*1.25+outline[i-1][0]*.4,.065,outline[i-1][1]-.6),new T.Vector3(side*1.25+outline[i][0]*.4,.065,outline[i][1]-.6),.018,white)});
 function labelTexture(text,bg='#142f3d',fg='#eee9d9',size=512){const c=document.createElement('canvas');c.width=size;c.height=128;const q=c.getContext('2d');q.fillStyle=bg;q.fillRect(0,0,size,128);q.fillStyle=fg;q.font='bold 48px system-ui';q.textAlign='center';q.textBaseline='middle';q.fillText(text,size/2,67);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;return texture}
 // Backstop wall, dugouts, layered grandstands and a structural canopy.
 const wall=mat('#203d49');box(86,1.8,.6,wall,0,.9,-9);for(let i=0;i<7;i++){const ad=mesh(new T.PlaneGeometry(11.5,1.25),mat('#ffffff',{map:labelTexture(['CPBL','TAIWAN BASEBALL','PLAY BALL','NEXT PITCH','CPBL','HOME OF BASEBALL','2026'][i])}),-36+i*12,1.1,-8.65);ad.castShadow=false;}
 for(let row=0;row<18;row++){box(110,.34,1.15,mat('#4c6070'),0,1.8+row*.43,-10.5-row*1.2)}
 const seats=new T.InstancedMesh(new T.CapsuleGeometry(.19,.18,3,8),mat('#315a7f'),18*150);const dummy=new T.Object3D();let n=0;for(let row=0;row<18;row++)for(let col=0;col<150;col++){dummy.position.set((col-75)*.7,2.15+row*.43,-10.5-row*1.2);dummy.updateMatrix();seats.setMatrixAt(n,dummy.matrix);seats.setColorAt(n,new T.Color(['#355b81','#365a7d','#315675','#2d5274'][(col*7+row*19)%4]));n++}scene.add(seats);
 const fans=new T.InstancedMesh(new T.SphereGeometry(.105,8,6),mat('#c49b7a'),800),fanShirts=new T.InstancedMesh(new T.CapsuleGeometry(.12,.16,3,6),mat('#b7bac0'),800);
 for(let i=0;i<800;i++){const row=i%18,col=(i*43)%150,x=(col-75)*.7,z=-10.4-row*1.2;dummy.position.set(x,2.75+row*.43,z);dummy.updateMatrix();fans.setMatrixAt(i,dummy.matrix);fans.setColorAt(i,new T.Color(['#ba906f','#d8b497','#a27a5f'][i%3]));dummy.position.set(x,2.43+row*.43,z);dummy.updateMatrix();fanShirts.setMatrixAt(i,dummy.matrix);fanShirts.setColorAt(i,new T.Color(['#f1d055','#e0e5e5','#ab343b','#374b6d','#b1b8b5'][i%5]));}scene.add(fans,fanShirts);
 for(let x=-50;x<=50;x+=10){cylinder(.14,13,metal,x,6.5,-30);segment(new T.Vector3(x,12,-32),new T.Vector3(x,11,-8),.1,metal)}const roof=box(116,.15,27,mat('#e1e4e1',{metalness:.25}),0,12,-22);roof.rotation.x=.035;
 // Continuous outfield seating, wall signage and a scoreboard in the batting view.
 const fenceMaterial=mat('#245343'),capMaterial=mat('#f4ca54');
 for(let i=0;i<48;i++){
  const a=-Math.PI/4+i*Math.PI/96,b=a+Math.PI/96,r=CPBLPhysics.wallDistance(a),r2=CPBLPhysics.wallDistance(b),x=Math.sin(a)*r,z=Math.cos(a)*r,x2=Math.sin(b)*r2,z2=Math.cos(b)*r2,length=Math.hypot(x2-x,z2-z),angle=Math.atan2(-(z2-z),x2-x);
  const panel=box(length+.04,3.4,.45,fenceMaterial,(x+x2)/2,1.7,(z+z2)/2);panel.rotation.y=angle;panel.castShadow=false;
  const cap=box(length+.05,.16,.55,capMaterial,(x+x2)/2,3.45,(z+z2)/2);cap.rotation.y=angle;cap.castShadow=false;
  for(let row=0;row<8;row++){const far=4+row*1.5,stand=box(length*(1+far/r)+.08,.5,1.45,mat(row%2?'#46627a':'#3a556d'),(x+x2)/2*(1+far/r),4+row*.55,(z+z2)/2*(1+far/r));stand.rotation.y=angle;stand.castShadow=false;}
 }
 for(const angle of [-Math.PI/4,0,Math.PI/4]){const r=CPBLPhysics.wallDistance(angle);const sign=mesh(new T.PlaneGeometry(5,1.5),mat('#ffffff',{map:labelTexture(angle===0?'400 FT':'328 FT','#245343'),side:T.DoubleSide}),Math.sin(angle)*(r-.3),1.8,Math.cos(angle)*(r-.3));sign.rotation.y=angle+Math.PI;sign.castShadow=false;}
 for(const side of [-1,1])cylinder(.10,14,capMaterial,side*100/Math.sqrt(2),7,100/Math.sqrt(2));
 const board=box(24,12,1,mat('#182d3d'),0,18,119);board.castShadow=false;
 const boardFace=mesh(new T.PlaneGeometry(22,10),mat('#ffffff',{map:labelTexture('CPBL  •  PLAY BALL','#09212c','#f6d57e'),side:T.DoubleSide}),0,18,118.4);boardFace.castShadow=false;boardFace.rotation.y=Math.PI;
 for(const x of [-11,11])cylinder(.25,12,metal,x,7,119);
 const skyCanvas=document.createElement('canvas');skyCanvas.width=16;skyCanvas.height=256;const skyContext=skyCanvas.getContext('2d'),skyGradient=skyContext.createLinearGradient(0,0,0,256);skyGradient.addColorStop(0,'#5286b4');skyGradient.addColorStop(.6,'#b2cfe0');skyGradient.addColorStop(1,'#d6e2df');skyContext.fillStyle=skyGradient;skyContext.fillRect(0,0,16,256);scene.background=new T.CanvasTexture(skyCanvas);scene.background.colorSpace=T.SRGBColorSpace;scene.fog.color.set('#b2cfe0');
 for(const [x,z] of [[-55,15],[55,15],[-75,90],[75,90]]){cylinder(.35,38,metal,x,19,z);box(10,4,.3,mat('#e3e7d6',{emissive:'#eee6d6',emissiveIntensity:.5}),x,37,z)}
 // Procedural articulated athlete: independent shoulders, elbows, hips and knees.
 function athlete(kind){const group=new T.Group(),uniform=mat('#ad3231'),pants=mat('#ece8dc'),parts={};scene.add(group);const pelvis=new T.Group();pelvis.position.y=1.02;group.add(pelvis);const body=new T.Group();body.position.y=.16;pelvis.add(body);const torso=mesh(new T.CapsuleGeometry(.20,.36,4,14),uniform,0,.18,0,body);torso.scale.set(1,1,.7);sphere(.14,skin,0,.67,0,body);sphere(.045,skin,-.14,.65,0,body);sphere(.045,skin,.14,.65,0,body);sphere(.04,skin,0,.64,.14,body);sphere(.14,uniform,0,.76,-.015,body).scale.y=.43;cylinder(.13,.025,uniform,0,.735,.13,body).scale.z=1.4;box(.33,.07,.25,dark,0,.01,0,pelvis);
 for(const side of [-1,1]){const arm=new T.Group();arm.position.set(side*.23,.34,0);body.add(arm);cylinder(.075,.30,uniform,0,-.15,0,arm);const elbow=new T.Group();elbow.position.y=-.3;arm.add(elbow);cylinder(.055,.30,skin,0,-.15,0,elbow);sphere(.065,skin,0,-.34,0,elbow);parts[side>0?'leftArm':'rightArm']=arm;parts[side>0?'leftElbow':'rightElbow']=elbow;
 const hip=new T.Group();hip.position.set(side*.105,0,0);pelvis.add(hip);cylinder(.085,.45,pants,0,-.23,0,hip);const knee=new T.Group();knee.position.y=-.45;hip.add(knee);cylinder(.070,.43,pants,0,-.20,0,knee);cylinder(.072,.12,uniform,0,-.38,0,knee);sphere(.10,dark,0,-.44,.065,knee).scale.set(.8,.55,1.7);parts[side>0?'leftLeg':'rightLeg']=hip;parts[side>0?'leftKnee':'rightKnee']=knee;}
 const glove=sphere(.14,mat('#906134'),-.02,-.35,.015,parts.leftElbow);glove.scale.set(.8,1.2,.6);glove.visible=['pitch','field','catch'].includes(kind);const bat=new T.Group();body.add(bat);(()=>{const shape=[[.038,0],[.038,.025],[.019,.05],[.019,.24],[.026,.48],[.041,.67],[.047,.85],[.043,.92],[.025,.95],[0,.96]].map(([r,y])=>new T.Vector2(r,y));const wood=mesh(new T.LatheGeometry(shape,20),mat('#cda96d'),0,0,0,bat);wood.rotation.x=Math.PI})();bat.visible=kind==='bat';
 if(kind==='catch'||kind==='ump'){const cageMaterial=mat('#475768',{metalness:.6});for(const y of [.54,.60,.67,.74]){const curve=new T.CatmullRomCurve3([new T.Vector3(-.15,y,.10),new T.Vector3(-.09,y,.205),new T.Vector3(.09,y,.205),new T.Vector3(.15,y,.10)]);mesh(new T.TubeGeometry(curve,12,.006,6,false),cageMaterial,0,0,0,body);}for(const x of [-.09,.09])segment(new T.Vector3(x,.52,.205),new T.Vector3(x,.78,.205),.006,cageMaterial,body);}
 if(kind==='catch'){const pad=mesh(new T.CapsuleGeometry(.13,.20,4,12),mat('#253e55'),0,.16,.16,body);pad.scale.set(1.28,1,.45);for(const side of ['left','right']){const shin=mesh(new T.CapsuleGeometry(.076,.24,4,10),mat('#253e55'),0,-.21,.07,parts[side+'Knee']);shin.scale.z=.45;}}
 const front=mesh(new T.PlaneGeometry(.34,.21),mat('#ffffff',{transparent:true}),0,.16,.148,body);const back=mesh(new T.PlaneGeometry(.35,.31),mat('#ffffff',{transparent:true}),0,.17,-.148,body);back.rotation.y=Math.PI;
 return {group,pelvis,body,uniform,parts,glove,bat,front,back,key:'',kind};
 }
 const pitcher=athlete('pitch'),batter=athlete('bat'),catcher=athlete('catch'),umpire=athlete('ump');const fielders=Array.from({length:7},()=>athlete('field')),runners=Array.from({length:4},()=>athlete('run'));
 pitcher.group.position.set(0,.28,18.44);pitcher.group.rotation.y=Math.PI;catcher.group.position.set(0,0,-.50);umpire.group.position.set(.45,0,-1.65);catcher.uniform.color.set('#273e58');umpire.uniform.color.set('#1c2831');
 const zone=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(.60,.70,.003)),new T.LineBasicMaterial({color:'#dce9ed',transparent:true,opacity:.30,depthWrite:false}));zone.position.set(0,1.1,.25);scene.add(zone);const reticle=mesh(new T.TorusGeometry(.105,.009,8,30),mat('#f5d467',{emissive:'#af9130'}),0,1.05,.22);const ball=sphere(.037,mat('#f6f0da'),0,0,0);
 const seam=new T.LineLoop(new T.BufferGeometry().setFromPoints(Array.from({length:32},(_,i)=>{const t=i*Math.PI/16;return new T.Vector3(.038*Math.cos(t),.038*Math.sin(t),.006*Math.sin(t*2))})),new T.LineBasicMaterial({color:'#b94739'}));ball.add(seam);const landing=mesh(new T.TorusGeometry(1,.06,8,40),mat('#ffd66f',{emissive:'#a67926'}));landing.rotation.x=Math.PI/2;
 function playerData(name){for(const team of rosterState.squads||[]) {const p=team.find(p=>p.name===name);if(p)return p}return {name,height:183,number:''}}
 function nameMap(name,number){const c=document.createElement('canvas');c.width=256;c.height=192;const q=c.getContext('2d');q.fillStyle='#f5f0df';q.textAlign='center';q.font='bold 28px system-ui';q.fillText(name,128,40);q.font='bold 94px system-ui';q.fillText(number||'CPBL',128,143);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
 function dress(actor,name,team){const p=playerData(name),key=name+team.color;if(actor.key===key)return;actor.key=key;actor.uniform.color.set(team.color);actor.group.scale.setScalar((p.height||183)/183);const old=actor.front.material.map;old?.dispose();const texture=nameMap(name,p.number);for(const plane of [actor.front,actor.back]){plane.material.map=texture;plane.material.needsUpdate=true}}
 function resetPose(a){Object.values(a.parts).forEach(p=>{p.rotation.set(0,0,0);if(p===a.parts.leftLeg||p===a.parts.rightLeg)p.position.z=0;});a.pelvis.position.set(0,1.02,0);a.pelvis.rotation.set(0,0,0);a.body.position.set(0,.16,0);a.body.rotation.set(0,0,0)}
 function catcherPose(a,flight,progress){const p=flight?CPBLPhysics.pitchPoint(flight,1):{x:0,y:.99};a.group.position.set(p.x*.80,0,-.50);a.pelvis.position.y=.48+Math.max(0,p.y-.95)*.65;a.body.rotation.x=.20;const local=(x,z)=>a.group.localToWorld(new T.Vector3(x,.08,z));legTo(a,'left',local(.28,.02));legTo(a,'right',local(-.28,.02));a.group.updateMatrixWorld(true);const ready=new T.Vector3(-.06,1.00,.02),target=new T.Vector3(p.x,p.y,.12);ready.lerp(target,CPBLPhysics.smooth((progress-.45)/.40));armTo(a,'left',a.body.worldToLocal(ready));a.parts.rightArm.rotation.x=.22;a.parts.rightElbow.rotation.x=-.50;}
 function umpirePose(a,left){a.group.position.set(left?-.43:.43,0,-1.65);a.pelvis.position.y=.76;a.body.rotation.x=.20;const local=(x,z)=>a.group.localToWorld(new T.Vector3(x,.08,z));legTo(a,'left',local(.22,.08));legTo(a,'right',local(-.22,-.02));a.parts.leftArm.rotation.x=-.30;a.parts.rightArm.rotation.x=-.30;a.parts.leftElbow.rotation.x=-.40;a.parts.rightElbow.rotation.x=-.40;}
 function runningPose(a,travelled,speed){if(speed<.1)return;const phase=travelled/2.35*Math.PI*2,wave=Math.sin(phase),effort=Math.min(1,speed/8);a.pelvis.position.y=.98+.028*Math.cos(phase*2)*effort;a.pelvis.rotation.y=wave*.06;a.body.rotation.y=-wave*.10;a.body.rotation.x=.12*effort;a.parts.leftLeg.rotation.x=-wave*.70*effort;a.parts.rightLeg.rotation.x=wave*.70*effort;a.parts.leftKnee.rotation.x=.18+Math.max(0,-wave)*.95*effort;a.parts.rightKnee.rotation.x=.18+Math.max(0,wave)*.95*effort;a.parts.leftArm.rotation.x=wave*.55*effort;a.parts.rightArm.rotation.x=-wave*.55*effort;a.parts.leftElbow.rotation.x=a.parts.rightElbow.rotation.x=-1.05;}
 function moveRunner(a,from,steps,t,duration=4300){a.group.visible=t>0;resetPose(a);const distance=27.436*steps,seconds=t*duration/1000,total=CPBLPhysics.runDistance(duration/1000),progress=CPBLPhysics.clamp(CPBLPhysics.runDistance(seconds)/Math.max(.01,total)),p=progress*steps,i=Math.min(steps-1,Math.floor(p)),f=p-i,start=basePositions[(from+i)%4],end=basePositions[(from+i+1)%4];a.group.position.copy(start).lerp(end,f);const heading=Math.atan2(end.x-start.x,end.z-start.z);let turnHeading=heading;const blendAngle=(a,b,t)=>a+Math.atan2(Math.sin(b-a),Math.cos(b-a))*t;if(f>.92&&i+1<steps){const next=basePositions[(from+i+2)%4];turnHeading=blendAngle(heading,Math.atan2(next.x-end.x,next.z-end.z),(f-.92)/.16);}else if(f<.08&&i>0){const prev=basePositions[(from+i-1)%4];turnHeading=blendAngle(Math.atan2(start.x-prev.x,start.z-prev.z),heading,.5+f/.16);}a.group.rotation.y=turnHeading;runningPose(a,progress*distance,t<1?Math.min(8.1,seconds*5)*distance/Math.max(.01,total):0);}
 function fieldingPose(a,point,ground,blend){const target=new T.Vector3(point.x,Math.max(.20,point.y),point.z);a.pelvis.position.y=1.02-(ground?.56:0)*blend;a.body.rotation.x=(ground?1.0:.12)*blend;a.group.updateMatrixWorld(true);if(ground){const local=(x,z)=>a.group.localToWorld(new T.Vector3(x,.08,z));legTo(a,'left',local(.25,.12));legTo(a,'right',local(-.25,-.12));}armTo(a,'left',a.body.worldToLocal(target));a.parts.rightArm.rotation.x=-.45*blend;a.parts.rightElbow.rotation.x=-.7*blend;}
 const ballMarker=document.createElement('div');ballMarker.className='ball-marker hidden';ballMarker.innerHTML='<b></b><span>球</span>';stage.append(ballMarker);
 const trailGeometry=new T.BufferGeometry(),trailArray=new Float32Array(32*3);trailGeometry.setAttribute('position',new T.BufferAttribute(trailArray,3));const trail=new T.Line(trailGeometry,new T.LineBasicMaterial({color:'#fff2ac',transparent:true,opacity:.8,depthTest:false}));trail.frustumCulled=false;scene.add(trail);
 let cssWidth=0,cssHeight=0,contextLost=false,lastPaint=0,frameCount=0,slowFrames=0;
 const sceneError={count:0};window.CPBL_RENDER_STATS={frames:0,contextLosses:0,recoveries:0,errors:0};
 // A translucent bat-shaped contact cursor; the player's actual bat stays in the animation.
 const outline=[[-.48,-.018],[-.30,-.018],[-.12,-.027],[.12,-.050],[.40,-.058],[.47,-.035],[.49,0],[.47,.035],[.40,.058],[.12,.050],[-.12,.027],[-.30,.018],[-.48,.018]];
 const cursorShape=new T.Shape();outline.forEach(([x,y],i)=>i?cursorShape.lineTo(x,y):cursorShape.moveTo(x,y));cursorShape.closePath();
 const aimBat=new T.Group();scene.add(aimBat);const cursorFill=new T.Mesh(new T.ShapeGeometry(cursorShape),new T.MeshBasicMaterial({color:'#8edaf5',transparent:true,opacity:.15,side:T.DoubleSide,depthTest:false,depthWrite:false}));aimBat.add(cursorFill);
 const contour=new T.LineLoop(new T.BufferGeometry().setFromPoints(outline.map(([x,y])=>new T.Vector3(x,y,0))),new T.LineBasicMaterial({color:'#a5e8ff',transparent:true,opacity:.95,depthTest:false}));aimBat.add(contour);aimBat.renderOrder=10;
 const swingTrail=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:'#c4ecff',transparent:true,opacity:.7,depthTest:false}));swingTrail.frustumCulled=false;scene.add(swingTrail);const swingTrailPoints=new Float32Array(24*3);swingTrail.geometry.setAttribute('position',new T.BufferAttribute(swingTrailPoints,3));
 const projected=new T.Vector3(),cameraTarget=new T.Vector3(),lookTarget=new T.Vector3(),gloveWorld=new T.Vector3();
 const ballShadow=mesh(new T.CircleGeometry(.10,20),new T.MeshBasicMaterial({color:'#17251b',transparent:true,opacity:.4,depthWrite:false}),0,.05,0);ballShadow.rotation.x=-Math.PI/2;ballShadow.castShadow=false;
 const fieldActors=[...fielders,pitcher],positions=['一壘手','二壘手','游擊手','三壘手','左外野手','中外野手','右外野手'];
 function fieldName(i,side){const players=rosterState.squads?.[side]||[];return players.find(p=>p.position===positions[i]&&tv.lineupIds?.[side]?.includes(p.id))?.name||PLAYERS[side?state.homeIndex:state.awayIndex][i]||'守備員'}
 // Anatomical left is +X when the avatar faces its local +Z.
 const down=new T.Vector3(0,-1,0);
 function armTo(actor,side,target){const arm=actor.parts[side+'Arm'],elbow=actor.parts[side+'Elbow'],shoulder=arm.position,delta=target.clone().sub(shoulder),d=Math.min(.635,Math.max(.04,delta.length())),unit=delta.normalize(),along=(d*d+.30*.30-.34*.34)/(2*d),bend=Math.sqrt(Math.max(0,.30*.30-along*along));const normal=new T.Vector3(side==='left'?.35:-.35,-.6,-.6);normal.addScaledVector(unit,-normal.dot(unit)).normalize();const joint=shoulder.clone().addScaledVector(unit,along).addScaledVector(normal,bend);arm.quaternion.setFromUnitVectors(down,joint.clone().sub(shoulder).normalize());const fore=new T.Quaternion().setFromUnitVectors(down,target.clone().sub(joint).normalize());elbow.quaternion.copy(arm.quaternion).invert().multiply(fore);}
 // Interpolate complete poses, retaining the finish instead of snapping back at contact.
 function motionKey(keys,time){let i=0;while(i<keys.length-2&&time>keys[i+1][0])i++;const a=keys[i],b=keys[i+1],span=b[0]-a[0],t=CPBLPhysics.clamp((time-a[0])/span);const slope=(index,col)=>{if(index===0||index===keys.length-1)return 0;const prev=keys[index-1],cur=keys[index],next=keys[index+1],before=(cur[col]-prev[col])/(cur[0]-prev[0]),after=(next[col]-cur[col])/(next[0]-cur[0]);return before*after<=0?0:2*before*after/(before+after);};return a.slice(1).map((v,c)=>{const col=c+1,m0=slope(i,col)*span,m1=slope(i+1,col)*span;return (2*t*t*t-3*t*t+1)*v+(t*t*t-2*t*t+t)*m0+(-2*t*t*t+3*t*t)*b[col]+(t*t*t-t*t)*m1;});}
 function legTo(actor,side,world){actor.group.updateMatrixWorld(true);const target=actor.pelvis.worldToLocal(world.clone()),hip=actor.parts[side+'Leg'],knee=actor.parts[side+'Knee'],delta=target.sub(hip.position),d=Math.min(.889,Math.max(.08,delta.length())),unit=delta.normalize(),along=(d*d+.45*.45-.44*.44)/(2*d),bend=Math.sqrt(Math.max(0,.45*.45-along*along)),normal=new T.Vector3(0,0,1);normal.addScaledVector(unit,-normal.dot(unit)).normalize();const joint=unit.clone().multiplyScalar(along).addScaledVector(normal,bend);hip.quaternion.setFromUnitVectors(down,joint.clone().normalize());const lower=new T.Quaternion().setFromUnitVectors(down,unit.multiplyScalar(d).sub(joint).normalize());knee.quaternion.copy(hip.quaternion).invert().multiply(lower);}
 function battingPose(actor,left,stamp){const sign=left?-1:1,age=tv.swung?Math.max(0,stamp-(tv.swingStart||stamp)):0;
  const m=motionKey([[0,-.22,-.18,0,.10,.44,.13,.24,1.24,-.30],[80,-.35,-.22,-.035,.12,.43,.10,.35,1.20,-.36],[140,.38,-.08,-.07,.04,.21,.38,.10,.33,1.30],[340,.85,.45,-.02,-.05,.20,.48,-.72,.55,.92],[480,1.10,.68,0,-.14,.50,.16,-.80,1.05,-.12],[1050,1.10,.68,0,-.14,.50,.16,-.80,1.05,-.12]],age);
  actor.pelvis.rotation.y=sign*m[0];actor.pelvis.position.y+=m[2];actor.body.rotation.y=sign*m[1];actor.body.rotation.x=.09;
  actor.group.updateMatrixWorld(true);const front=left?'right':'left',back=left?'left':'right';const foot=(side,z)=>actor.group.localToWorld(new T.Vector3(side==='left'?.24:-.24,.08,z));legTo(actor,front,foot(front,.18));legTo(actor,back,foot(back,-.16));
  const grip=new T.Vector3(sign*m[3],m[4],m[5]),tip=new T.Vector3(sign*m[6],m[7],m[8]),direction=tip.clone().sub(grip).normalize();actor.bat.position.copy(grip);actor.bat.quaternion.setFromUnitVectors(down,direction);actor.glove.visible=false;armTo(actor,'left',grip.clone().addScaledVector(direction,left?.035:-.025));armTo(actor,'right',grip.clone().addScaledVector(direction,left?-.025:.035));
 }
 function actorHand(actor,side){actor.group.updateMatrixWorld(true);return actor.parts[side+'Elbow'].localToWorld(new T.Vector3(0,-.34,0));}
 function applyDelivery(actor,profile,stamp){const left=profile.hand==='L',throwing=left?'left':'right',glove=left?'right':'left',sign=left?-1:1;
  if(actor.glove.parent!==actor.parts[glove+'Elbow'])actor.parts[glove+'Elbow'].add(actor.glove);
  const elapsed=tv.phase==='pitch'?1100+stamp-tv.start:tv.deliveryAt?stamp-tv.deliveryAt:2400;
  // Pelvis opens before shoulders; weight travels into the planted stride foot.
  const m=motionKey([[0,0,0,0,0,0,0],[380,.38,.10,.02,.06,0,.62],[700,.52,.22,.04,-.02,.22,.45],[940,-.30,.62,.18,-.18,.35,.08],[1100,-.60,.12,.32,-.22,.48,0],[1450,-.82,-.16,.78,-.26,.50,0],[1850,-.45,-.14,.35,-.10,.42,0],[2400,0,0,0,0,0,0]],elapsed);
  actor.group.position.z=18.44-m[4];actor.pelvis.position.y+=m[3];actor.pelvis.rotation.y=-sign*m[0];actor.body.rotation.y=-sign*m[1];actor.body.rotation.x=m[2];actor.body.rotation.z=sign*(profile.style==='side'?-.20:-.05)*Math.sin(Math.PI*CPBLPhysics.clamp(elapsed/1900));
  const footX=throwing==='left'?.12:-.12,scale=actor.group.scale.x;
  legTo(actor,throwing,new T.Vector3(-footX*scale,.34,18.44+(elapsed>1100?CPBLPhysics.smooth((elapsed-1100)/700)*-.65:0)));
  legTo(actor,glove,new T.Vector3(footX*scale,.34+m[5]*scale,18.44-m[4]-.50*CPBLPhysics.smooth((elapsed-650)/300)));
  actor.group.updateMatrixWorld(true);
  const release=CPBLPhysics.releasePoint(profile),path=motionKey([[0,sign*.08,1.47,18.25],[420,sign*.04,1.57,18.30],[720,sign*.56,2.02,18.75],[900,release.x+sign*.08,release.y+.12,release.z+.25],[1100,release.x,release.y,release.z],[1320,release.x-sign*.34,release.y-.80,release.z-.38],[1600,-sign*.30,1.08,17.62],[2400,sign*.08,1.47,18.25]],elapsed);
  armTo(actor,throwing,actor.body.worldToLocal(new T.Vector3(...path)));
  const gloveTarget=new T.Vector3(-sign*(elapsed<800?.18:.10),elapsed<800?1.55:1.35,18.15-m[4]);actor.group.updateMatrixWorld(true);armTo(actor,glove,actor.body.worldToLocal(gloveTarget));actor.group.updateMatrixWorld(true);const throwingShoulder=actor.parts[throwing+'Arm'].getWorldPosition(new T.Vector3()),gloveShoulder=actor.parts[glove+'Arm'].getWorldPosition(new T.Vector3()),separation=throwingShoulder.z-gloveShoulder.z;if(elapsed>=500&&elapsed<=720)window.CPBL_RENDER_STATS.shoulderLoadError=Math.max(window.CPBL_RENDER_STATS.shoulderLoadError||0,-separation);if(elapsed>=1090&&elapsed<=1120)window.CPBL_RENDER_STATS.shoulderReleaseError=Math.max(window.CPBL_RENDER_STATS.shoulderReleaseError||0,separation);
 }
 // Camera-attached bat and two gripping hands: an actual first-person swing.
 const viewBat=new T.Group();camera.add(viewBat);scene.add(camera);const viewWood=batter.bat.children[0].clone();viewBat.add(viewWood);const viewHands=new T.Group();viewBat.add(viewHands);const battingGlove=mat('#eee9dc');for(const y of [-.075,-.155]){const palm=mesh(new T.CapsuleGeometry(.040,.045,4,10),battingGlove,0,y,.005,viewHands);palm.rotation.z=Math.PI/2;palm.scale.z=.65;for(let i=0;i<4;i++)sphere(.012,battingGlove,-.030+i*.020,y+.024,.026,viewHands);}viewBat.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=false;}});
 const viewForearms=[cylinder(.043,.30,skin,0,0,0,camera),cylinder(.043,.30,skin,0,0,0,camera)];
 function firstPersonSwing(left,age){const sign=left?-1:1,m=motionKey([[0,.38,-.34,-.72,.66,.60,-.92],[80,.45,-.34,-.70,.76,.52,-.92],[140,.15,-.26,-.86,-.66,-.08,-1.34],[340,-.32,-.18,-.73,-.98,.14,-.88],[740,-.38,.04,-.54,-.56,.85,-.48],[1050,-.38,.04,-.54,-.56,.85,-.48]],age),grip=new T.Vector3(sign*m[0],m[1],m[2]),tip=new T.Vector3(sign*m[3],m[4],m[5]);viewBat.position.copy(grip);viewBat.quaternion.setFromUnitVectors(down,tip.sub(grip).normalize());for(let i=0;i<2;i++){const wrist=new T.Vector3(0,-.075-i*.08,.025).applyQuaternion(viewBat.quaternion).add(grip),elbow=grip.clone().add(new T.Vector3(sign*(.10+i*.055),-.38,.08)),d=wrist.clone().sub(elbow);viewForearms[i].position.copy(wrist).add(elbow).multiplyScalar(.5);viewForearms[i].scale.y=d.length()/.30;viewForearms[i].quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());}}
 function render3d(now){requestAnimationFrame(render3d);if(contextLost||document.hidden||$('#gameScreen').classList.contains('hidden')||now-lastPaint<1000/30)return;
  const paintStart=performance.now();lastPaint=now;try{const stamp=tv.paused?tv.pauseAt:now,elapsed=stamp-tv.start,width=stage.clientWidth,height=stage.clientHeight;if(!width||!height)return;
  if(width!==cssWidth||height!==cssHeight){cssWidth=width;cssHeight=height;renderer.setSize(width,height,false);}camera.aspect=width/height;
  const h=tv.hit,tracking=!!h&&(tv.phase==='hit'||tv.phase==='result'),fs=tracking?1-h.batSide:fieldingTeam(),bs=1-fs,profile=tv.pitchers[fs]||activePitcher();
  dress(pitcher,profile.name,teamFor(fs));dress(batter,tracking?h.batter:batterName(),teamFor(bs));resetPose(pitcher);resetPose(batter);resetPose(catcher);resetPose(umpire);
  pitcher.group.rotation.y=Math.PI;pitcher.group.position.set(0,.28,18.44);applyDelivery(pitcher,profile,stamp);
  const battingLeft=playerTraits.get(tv.lineupIds?.[bs]?.[state.orders[bs]%9])?.batHand==='L';batter.group.position.set(battingLeft?-1.1:1.1,0,.15);batter.group.rotation.y=battingLeft?Math.PI/2:-Math.PI/2;
  catcherPose(catcher,tv.flight,tv.phase==='pitch'?Math.min(1,elapsed/(tv.flight?.duration||1)):tv.phase==='result'?1:0);umpirePose(umpire,battingLeft);
  const swing=tv.swung?CPBLPhysics.smooth((stamp-(tv.swingStart||stamp))/520):0;battingPose(batter,battingLeft,stamp);
  stage.dataset.ballPhase='none';ball.visible=false;landing.visible=false;trail.visible=false;ballShadow.visible=false;ballMarker.classList.add('hidden');batter.group.visible=!playerBatting()&&(!tracking||stamp-h.start<350);catcher.group.visible=umpire.group.visible=!playerBatting()||tracking;
  zone.visible=!tracking&&tv.phase!=='result';reticle.visible=zone.visible&&(!playerBatting()||tv.power);reticle.position.set((playerBatting()?-1:1)*tv.aim.x*.3,1.1-tv.aim.y*.35,.22);
  fielders.forEach((a,i)=>{a.group.visible=true;dress(a,fieldName(i,fs),teamFor(fs));resetPose(a);const p=CPBLPhysics.fielders[i];a.group.position.set(p.x,0,p.z);a.group.rotation.y=Math.PI;});runners.forEach(a=>a.group.visible=false);if(!tracking){for(let i=0;i<3;i++)if(state.bases[i]){const a=runners[i+1];dress(a,state.bases[i],teamFor(bs));resetPose(a);a.group.visible=true;a.group.position.copy(basePositions[i]);a.group.rotation.y=Math.PI;a.pelvis.position.y=.98;a.body.rotation.x=.10;a.parts.leftKnee.rotation.x=a.parts.rightKnee.rotation.x=.15;}}
  if(tv.phase==='pitch'&&tv.flight){const f=tv.flight,t=Math.min(1,elapsed/f.duration),p=CPBLPhysics.pitchPoint(f,t);ball.visible=true;ball.position.set(p.x,p.y,p.z);if(t<.04){const side=f.hand==='L'?'left':'right',hand=actorHand(pitcher,side);stage.dataset.releaseHand=f.hand;stage.dataset.releaseX=String(p.x);stage.dataset.handX=String(hand.x);if(t===0){const error=hand.distanceTo(ball.position);window.CPBL_RENDER_STATS.releaseError=Math.max(window.CPBL_RENDER_STATS.releaseError||0,error);}}}
  if(tv.phase==='result'&&!tracking&&tv.flight&&elapsed<450&&!tv.call.includes('FOUL')){ball.visible=true;catcher.group.updateMatrixWorld(true);ball.position.copy(catcher.glove.getWorldPosition(gloveWorld));}
  if(tracking){const playElapsed=Math.min(stamp-h.start,h.durationMs),p=CPBLPhysics.playPoint(h,playElapsed),defender=fieldActors[h.fielder],fp=CPBLPhysics.fielderPoint(h,playElapsed);
   stage.dataset.ballPhase=p.phase;ball.visible=true;ball.position.set(p.x,p.y,p.z);landing.visible=false;landing.position.set(h.land.x,.08,h.land.z);
   defender.group.position.set(fp.x,0,fp.z);const original=CPBLPhysics.fielders[h.fielder];defender.group.rotation.y=Math.atan2(h.fieldTarget.x-original.x,h.fieldTarget.z-original.z);
   if(fp.moving)runningPose(defender,Math.hypot(fp.x-original.x,fp.z-original.z),fp.speed||7);
   const fieldTime=h.caught?h.flightMs:h.fieldAtMs||h.pickupMs,approach=CPBLPhysics.smooth((playElapsed-(fieldTime-420))/420);
   if(approach>0&&playElapsed<h.pickupMs){const target=h.caught?{...h.land,y:1.15}:{...h.pickup,y:.20};defender.group.position.addScaledVector(new T.Vector3(Math.sin(defender.group.rotation.y),0,Math.cos(defender.group.rotation.y)),-.25*approach);fieldingPose(defender,target,!h.caught,approach);if(['caught','fielded'].includes(p.phase)){defender.group.updateMatrixWorld(true);ball.position.copy(defender.glove.getWorldPosition(gloveWorld));}}
   const legs=h.throwLegs||[];for(const leg of legs){const index=leg.receiver,receiver=index===8?catcher:fieldActors[index],initial=index===8?{x:0,z:-.50}:CPBLPhysics.fielders[index];if(receiver===defender)continue;const coverTarget=leg.receiverPosition||leg.to,distance=Math.hypot(coverTarget.x-initial.x,coverTarget.z-initial.z),seconds=Math.max(0,playElapsed/1000-.22),covered=CPBLPhysics.runDistance(seconds,7.7),cover=CPBLPhysics.clamp(covered/Math.max(.01,distance));receiver.group.position.set(initial.x+(coverTarget.x-initial.x)*cover,0,initial.z+(coverTarget.z-initial.z)*cover);receiver.group.rotation.y=cover<.96?Math.atan2(coverTarget.x-initial.x,coverTarget.z-initial.z):Math.atan2(leg.from.x-leg.to.x,leg.from.z-leg.to.z);if(cover<1&&index!==8)runningPose(receiver,distance*cover,Math.min(7.7,seconds*5));}
   for(let k=0;k<legs.length;k++){const leg=legs[k],previous=legs[k-1],thrower=previous?(previous.receiver===8?catcher:fieldActors[previous.receiver]):defender,age=playElapsed-leg.start;if(age<-(k?220:h.transferMs||420)||age>480)continue;
    thrower.group.rotation.y=Math.atan2(leg.to.x-leg.from.x,leg.to.z-leg.from.z);const wind=CPBLPhysics.smooth((age+420)/420),finish=CPBLPhysics.smooth(age/480);thrower.pelvis.rotation.y=-.35*(1-CPBLPhysics.smooth((age+420)/300))+.45*finish;thrower.body.rotation.y=-.40*(1-wind)+.15*wind+.32*finish;const groundTransfer=k===0&&h.kind==='ground';thrower.body.rotation.x=groundTransfer?1.0*(1-wind)+.12*wind+.25*finish:.12+.25*finish;thrower.pelvis.position.y=groundTransfer?.46+.48*wind:.94;
    const target=new T.Vector3(leg.from.x,groundTransfer?.25+1.10*wind+.20*Math.sin(Math.PI*wind):leg.from.y||1.35,leg.from.z);thrower.group.updateMatrixWorld(true);const local=thrower.body.worldToLocal(target);local.z-=.30*(1-wind);local.y+=(groundTransfer?0:.25*(1-wind))-.40*finish;armTo(thrower,'right',local);if(groundTransfer&&age<0){thrower.group.updateMatrixWorld(true);const chest=thrower.body.localToWorld(new T.Vector3(.13,.18,.24)),mittTarget=new T.Vector3(h.pickup.x,.20,h.pickup.z).lerp(chest,wind);armTo(thrower,'left',thrower.body.worldToLocal(mittTarget));}else armTo(thrower,'left',new T.Vector3(.13,.18,.24));
    if(age<0&&['fielded','relay'].includes(p.phase)){const hand=actorHand(thrower,'right'),blend=CPBLPhysics.smooth((age+250)/250);thrower.group.updateMatrixWorld(true);ball.position.copy(thrower.glove.getWorldPosition(gloveWorld)).lerp(hand,blend);}
    if(p.phase==='throw'&&playElapsed>leg.end-350){const receiver=leg.receiver===8?catcher:fieldActors[leg.receiver];fieldingPose(receiver,{...leg.to,y:leg.to.y||1.15},false,1);}
   }
   if(p.phase==='relay'||p.phase==='received'){const receiver=p.receiver===8?catcher:fieldActors[p.receiver];if(receiver){fieldingPose(receiver,{x:p.x,y:p.y,z:p.z},false,1);receiver.group.updateMatrixWorld(true);ball.position.copy(receiver.glove.getWorldPosition(gloveWorld));}}
   dress(runners[0],h.batter,teamFor(h.batSide));for(let i=0;i<3;i++)if(h.runners[i]){dress(runners[i+1],h.runners[i],teamFor(h.batSide));resetPose(runners[i+1]);runners[i+1].group.visible=true;runners[i+1].group.position.copy(basePositions[i]);}
   for(const plan of h.runnerPlans||[]){const actor=runners[plan.index+1],t=CPBLPhysics.clamp((playElapsed-plan.start)/plan.duration);moveRunner(actor,plan.from,plan.steps,t,plan.duration);if(plan.outAt&&playElapsed>plan.outAt+250)actor.group.visible=false;}

   camera.fov=camera.aspect<1?54:43;cameraTarget.set(ball.position.x+8,Math.max(13,ball.position.y+11),ball.position.z-29);camera.position.lerp(cameraTarget,.18);lookTarget.copy(ball.position);camera.lookAt(lookTarget);
   trail.visible=!['caught','fielded','received','relay'].includes(p.phase);for(let j=0;j<32;j++){const q=CPBLPhysics.playPoint(h,Math.max(0,playElapsed-j*25));trailArray[j*3]=q.x;trailArray[j*3+1]=q.y;trailArray[j*3+2]=q.z;}trailGeometry.attributes.position.needsUpdate=true;
   ballMarker.querySelector('span').textContent='';
   if(p.phase==='rolling'){const roll=CPBLPhysics.playPoint(h,playElapsed-25),distance=Math.hypot(p.x-roll.x,p.z-roll.z);ball.rotateOnWorldAxis(new T.Vector3(Math.cos(h.angle),0,-Math.sin(h.angle)),distance/.037);}
  }else if(playerBatting()){camera.fov=camera.aspect<1?52:43;camera.position.set(0,1.65,-2.6);camera.lookAt(0,1.2,18.44);}else{camera.fov=camera.aspect<1?13:10;camera.position.set(2.3,3.3,49);camera.lookAt(0,1,7);}
  const swingAge=stamp-(tv.swingStart||0);viewBat.visible=playerBatting()&&tv.swung&&swingAge<1050;viewForearms.forEach(a=>a.visible=viewBat.visible);if(viewBat.visible){firstPersonSwing(battingLeft,swingAge);if(tracking){camera.fov=camera.aspect<1?52:43;camera.position.set(0,1.65,-2.6);camera.lookAt(0,1.2,18.44);}}
  const swingActive=tv.swung&&stamp-(tv.swingStart||0)<350,aim=tv.swung?(tv.swingAim||tv.aim):tv.aim;
  aimBat.visible=playerBatting()&&!tv.power&&!tracking&&!tv.swung;aimBat.position.set(-aim.x*.3,1.1-aim.y*.35,.22);aimBat.rotation.z=swingActive?-.55+swing*1.1:0;
  swingTrail.visible=aimBat.visible&&swingActive;if(swingTrail.visible){for(let j=0;j<24;j++){const angle=-.6+Math.max(0,swing-j*.025)*1.2;swingTrailPoints[j*3]=-aim.x*.3+Math.cos(angle)*.48;swingTrailPoints[j*3+1]=1.1-aim.y*.35+Math.sin(angle)*.48;swingTrailPoints[j*3+2]=.23;}swingTrail.geometry.attributes.position.needsUpdate=true;}
  if(ball.visible){ballShadow.visible=true;ballShadow.position.set(ball.position.x,.06,ball.position.z);ballShadow.scale.setScalar(1+Math.min(3,ball.position.y*.13));ballShadow.material.opacity=Math.max(.15,.55-ball.position.y*.012);}
  camera.updateProjectionMatrix();renderer.shadowMap.needsUpdate=frameCount++%3===0;renderer.render(scene,camera);window.CPBL_RENDER_STATS.frames++;if(frameCount%30===0){stage.dataset.frames=String(window.CPBL_RENDER_STATS.frames);stage.dataset.errors=String(window.CPBL_RENDER_STATS.errors);stage.dataset.contextLosses=String(window.CPBL_RENDER_STATS.contextLosses)}
  if(ball.visible&&tracking){projected.copy(ball.position).project(camera);if(projected.z<1){ballMarker.classList.remove('hidden');ballMarker.style.left=((projected.x+1)*width/2)+'px';ballMarker.style.top=((1-projected.y)*height/2)+'px';ballMarker.classList.toggle('in-flight',tracking);}}
  if(performance.now()-paintStart>45)slowFrames++;else slowFrames=Math.max(0,slowFrames-1);if(slowFrames>30){renderer.setPixelRatio(1);renderer.shadowMap.enabled=false;slowFrames=0;}
  }catch(error){console.error('3D frame',error);window.CPBL_RENDER_STATS.errors++;if(++sceneError.count===1){if(!tv.paused)pause();announce('畫面暫停 · 請繼續');}}
 }
 const badge=document.createElement('span');badge.className='skin-badge';badge.textContent='3D LIVE · WEBGL';stage.append(badge);
 const meter=document.createElement('div');meter.className='pitch-meter hidden';meter.innerHTML='<span>在金色區域放開</span><div><b></b><i></i></div>';stage.append(meter);
 const fallbackPitch=drawPitchScene,fallbackHit=drawHitScene;drawPitchScene=function(){meter.classList.toggle('hidden',tv.phase!=='charge');if(tv.phase==='charge'){const stamp=tv.paused?tv.pauseAt:performance.now();meter.querySelector('i').style.left=((stamp-tv.start)/1000%1.5)/1.5*100+'%'}};drawHitScene=function(){};
 requestAnimationFrame(render3d);
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;window.CPBL_RENDER_STATS.contextLosses++;ballMarker.classList.add('hidden');if(!tv.paused)pause();badge.textContent='3D 畫面恢復中';renderer.setPixelRatio(1);renderer.shadowMap.enabled=false;try{const extension=renderer.getContext().getExtension('WEBGL_lose_context');setTimeout(()=>extension?.restoreContext(),1500)}catch(error){console.warn('Waiting for WebGL restore',error)}});
 renderer.domElement.addEventListener('webglcontextrestored',()=>{contextLost=false;cssWidth=cssHeight=0;sceneError.count=0;window.CPBL_RENDER_STATS.recoveries++;badge.textContent='3D LIVE · WEBGL';announce('3D 已恢復 · 點此繼續');});
})();
