/* Real WebGL scene, articulated athletes, perspective broadcast cameras.
   Models are original game avatars; no claim of photographic player likeness. */
(function(){
 if(!window.THREE)return;
 const T=window.THREE;let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'default'})}catch(e){return}
 renderer.domElement.className='webgl-canvas';renderer.domElement.setAttribute('aria-label','3D 棒球轉播場景');stage.prepend(renderer.domElement);canvas.style.visibility='hidden';stage.classList.add('has-webgl');
 renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
 const scene=new T.Scene();scene.background=new T.Color('#9aabb8');scene.fog=new T.Fog('#9aabb8',130,260);const camera=new T.PerspectiveCamera(6.5,16/9,.1,400);
 scene.add(new T.HemisphereLight('#d4e7fa','#394721',1.2));const sun=new T.DirectionalLight('#fff0d4',2.8);sun.position.set(-35,55,30);sun.castShadow=true;sun.shadow.mapSize.set(768,768);Object.assign(sun.shadow.camera,{left:-65,right:65,top:100,bottom:-30,near:1,far:160});sun.shadow.bias=-.0015;sun.shadow.normalBias=.045;scene.add(sun);scene.add(sun.target);
 function mat(color,extra={}){return new T.MeshStandardMaterial({color,roughness:.8,...extra})}
 const white=mat('#e9e6d8'),soil=mat('#a88663'),grass=mat('#3e7040'),metal=mat('#627886',{metalness:.6}),skin=mat('#c59370'),dark=mat('#182735');
 function mesh(geometry,material,x=0,y=0,z=0,parent=scene){const o=new T.Mesh(geometry,material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 function box(w,h,d,m,x,y,z,parent){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,parent)}
 function sphere(r,m,x,y,z,parent){return mesh(new T.SphereGeometry(r,16,12),m,x,y,z,parent)}
 function cylinder(r,h,m,x,y,z,parent){return mesh(new T.CylinderGeometry(r,r,h,32),m,x,y,z,parent)}
 const ground=mesh(new T.PlaneGeometry(330,330),grass,0,-.03,70);ground.rotation.x=-Math.PI/2;ground.castShadow=false;
 for(let i=0;i<16;i++){const strip=mesh(new T.PlaneGeometry(8,180),mat(i%2?'#41784a':'#3c7146'),(i-8)*8,.001,75);strip.rotation.x=-Math.PI/2;strip.castShadow=false;}
 const dirtShape=new T.Shape();dirtShape.moveTo(0,0);dirtShape.lineTo(34,-34);dirtShape.absarc(0,0,Math.hypot(34,34),-Math.PI/4,-Math.PI*3/4,true);dirtShape.lineTo(0,0);const diamond=mesh(new T.ShapeGeometry(dirtShape,48),soil,0,.01,0);diamond.rotation.x=-Math.PI/2;diamond.castShadow=false;
 const center=box(24,.03,24,grass,0,.02,19.4);center.rotation.y=Math.PI/4;center.castShadow=false;
 cylinder(2.75,.28,soil,0,.12,18.44).castShadow=false;cylinder(4.7,.04,soil,0,.025,0).castShadow=false;box(.61,.04,.15,white,0,.29,18.44);
 const basePositions=CPBLPhysics.bases.map(p=>new T.Vector3(p.x,0,p.z));basePositions.slice(0,3).forEach(p=>box(.38,.1,.38,white,p.x,.04,p.z));box(.42,.04,.42,white,0,.07,0);
 function segment(a,b,r,m,parent=scene){const direction=new T.Vector3().subVectors(b,a);const o=mesh(new T.CylinderGeometry(r,r,direction.length(),14),m,0,0,0,parent);o.position.copy(a).add(b).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),direction.normalize());return o}
 [-1,1].forEach(side=>{segment(new T.Vector3(0,.02,0),new T.Vector3(side*110,.02,110),.025,white);const outline=[[-.8,0],[.8,0],[.8,1.8],[-.8,1.8],[-.8,0]];for(let i=1;i<outline.length;i++)segment(new T.Vector3(side*1.25+outline[i-1][0]*.4,.065,outline[i-1][1]-.6),new T.Vector3(side*1.25+outline[i][0]*.4,.065,outline[i][1]-.6),.018,white)});
 function labelTexture(text,bg='#142f3d',fg='#eee9d9',size=512){const c=document.createElement('canvas');c.width=size;c.height=128;const q=c.getContext('2d');q.fillStyle=bg;q.fillRect(0,0,size,128);q.fillStyle=fg;q.font='bold 48px system-ui';q.textAlign='center';q.textBaseline='middle';q.fillText(text,size/2,67);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;return texture}
 // Backstop wall, dugouts, layered grandstands and a structural canopy.
 const wall=mat('#203d49');box(86,1.8,.6,wall,0,.9,-9);for(let i=0;i<7;i++){const ad=mesh(new T.PlaneGeometry(11.5,1.25),mat('#ffffff',{map:labelTexture(['CPBL','TAIWAN BASEBALL','PLAY BALL','NEXT PITCH','CPBL','HOME OF BASEBALL','2026'][i])}),-36+i*12,1.1,-8.65);ad.castShadow=false;}
 for(let row=0;row<18;row++){box(110,.34,1.15,mat('#4c6070'),0,1.8+row*.43,-10.5-row*1.2)}
 const seats=new T.InstancedMesh(new T.CapsuleGeometry(.19,.18,3,8),mat('#315a7f'),18*150);const dummy=new T.Object3D();let n=0;for(let row=0;row<18;row++)for(let col=0;col<150;col++){dummy.position.set((col-75)*.7,2.15+row*.43,-10.5-row*1.2);dummy.updateMatrix();seats.setMatrixAt(n,dummy.matrix);seats.setColorAt(n,new T.Color(['#355b81','#365a7d','#315675','#2d5274'][(col*7+row*19)%4]));n++}scene.add(seats);
 const fans=new T.InstancedMesh(new T.SphereGeometry(.105,8,6),mat('#c49b7a'),800),fanShirts=new T.InstancedMesh(new T.CapsuleGeometry(.12,.16,3,6),mat('#b7bac0'),800);
 for(let i=0;i<800;i++){const row=i%18,col=(i*43)%150,x=(col-75)*.7,z=-10.4-row*1.2;dummy.position.set(x,2.75+row*.43,z);dummy.updateMatrix();fans.setMatrixAt(i,dummy.matrix);fans.setColorAt(i,new T.Color(['#ba906f','#d8b497','#a27a5f'][i%3]));dummy.position.set(x,2.43+row*.43,z);dummy.updateMatrix();fanShirts.setMatrixAt(i,dummy.matrix);fanShirts.setColorAt(i,new T.Color(['#f1d055','#e0e5e5','#ab343b','#374b6d','#b1b8b5'][i%5]));}scene.add(fans,fanShirts);
 for(let x=-50;x<=50;x+=10){cylinder(.14,13,metal,x,6.5,-30);segment(new T.Vector3(x,12,-32),new T.Vector3(x,11,-8),.1,metal)}const roof=box(116,.15,27,mat('#e1e4e1',{metalness:.25}),0,12,-22);roof.rotation.x=.035;
 // Continuous outfield seating, wall signage and a scoreboard in the batting view.
 const fenceMaterial=mat('#245343'),capMaterial=mat('#f4ca54');
 for(let i=0;i<48;i++){
  const a=-Math.PI/4+i*Math.PI/96,b=a+Math.PI/96,r=CPBLPhysics.wallDistance(a),r2=CPBLPhysics.wallDistance(b),x=Math.sin(a)*r,z=Math.cos(a)*r,x2=Math.sin(b)*r2,z2=Math.cos(b)*r2,length=Math.hypot(x2-x,z2-z),angle=Math.atan2(-(z2-z),x2-x);
  const panel=box(length+.04,3.4,.45,fenceMaterial,(x+x2)/2,1.7,(z+z2)/2);panel.rotation.y=angle;panel.castShadow=false;
  const cap=box(length+.05,.16,.55,capMaterial,(x+x2)/2,3.45,(z+z2)/2);cap.rotation.y=angle;cap.castShadow=false;
  for(let row=0;row<8;row++){const far=4+row*1.5,stand=box(length*(1+far/r)+.08,.5,1.45,mat(row%2?'#46627a':'#3a556d'),(x+x2)/2*(1+far/r),4+row*.55,(z+z2)/2*(1+far/r));stand.rotation.y=angle;stand.castShadow=false;}
 }
 for(const angle of [-Math.PI/4,0,Math.PI/4]){const r=CPBLPhysics.wallDistance(angle);const sign=mesh(new T.PlaneGeometry(5,1.5),mat('#ffffff',{map:labelTexture(angle===0?'400 FT':'328 FT','#245343'),side:T.DoubleSide}),Math.sin(angle)*(r-.3),1.8,Math.cos(angle)*(r-.3));sign.rotation.y=angle+Math.PI;sign.castShadow=false;}
 for(const side of [-1,1])cylinder(.10,14,capMaterial,side*100/Math.sqrt(2),7,100/Math.sqrt(2));
 const board=box(24,12,1,mat('#182d3d'),0,18,119);board.castShadow=false;
 const boardFace=mesh(new T.PlaneGeometry(22,10),mat('#ffffff',{map:labelTexture('CPBL  •  PLAY BALL','#09212c','#f6d57e'),side:T.DoubleSide}),0,18,118.4);boardFace.castShadow=false;boardFace.rotation.y=Math.PI;
 for(const x of [-11,11])cylinder(.25,12,metal,x,7,119);
 const skyCanvas=document.createElement('canvas');skyCanvas.width=16;skyCanvas.height=256;const skyContext=skyCanvas.getContext('2d'),skyGradient=skyContext.createLinearGradient(0,0,0,256);skyGradient.addColorStop(0,'#5286b4');skyGradient.addColorStop(.6,'#b2cfe0');skyGradient.addColorStop(1,'#d6e2df');skyContext.fillStyle=skyGradient;skyContext.fillRect(0,0,16,256);scene.background=new T.CanvasTexture(skyCanvas);scene.background.colorSpace=T.SRGBColorSpace;scene.fog.color.set('#b2cfe0');
 for(const [x,z] of [[-55,15],[55,15],[-75,90],[75,90]]){cylinder(.35,38,metal,x,19,z);box(10,4,.3,mat('#e3e7d6',{emissive:'#eee6d6',emissiveIntensity:.5}),x,37,z)}
 // Procedural articulated athlete: independent shoulders, elbows, hips and knees.
 function athlete(kind){const group=new T.Group(),uniform=mat('#ad3231'),pants=mat('#ece8dc'),parts={};scene.add(group);const body=new T.Group();body.position.y=1.18;group.add(body);const torso=mesh(new T.CapsuleGeometry(.20,.36,4,14),uniform,0,.18,0,body);torso.scale.set(1,1,.7);sphere(.14,skin,0,.67,0,body);sphere(.045,skin,-.14,.65,0,body);sphere(.045,skin,.14,.65,0,body);sphere(.04,skin,0,.64,.14,body);sphere(.14,uniform,0,.76,-.015,body).scale.y=.43;cylinder(.13,.025,uniform,0,.735,.13,body).scale.z=1.4;box(.33,.07,.25,dark,0,-.15,0,body);
 for(const side of [-1,1]){const arm=new T.Group();arm.position.set(side*.23,.34,0);body.add(arm);cylinder(.075,.30,uniform,0,-.15,0,arm);const elbow=new T.Group();elbow.position.y=-.3;arm.add(elbow);cylinder(.055,.30,skin,0,-.15,0,elbow);sphere(.065,skin,0,-.34,0,elbow);parts[side>0?'leftArm':'rightArm']=arm;parts[side>0?'leftElbow':'rightElbow']=elbow;
 const hip=new T.Group();hip.position.set(side*.105,1.02,0);group.add(hip);cylinder(.085,.45,pants,0,-.23,0,hip);const knee=new T.Group();knee.position.y=-.45;hip.add(knee);cylinder(.070,.43,pants,0,-.20,0,knee);cylinder(.072,.12,uniform,0,-.38,0,knee);sphere(.10,dark,0,-.44,.065,knee).scale.set(.8,.55,1.7);parts[side>0?'leftLeg':'rightLeg']=hip;parts[side>0?'leftKnee':'rightKnee']=knee;}
 const glove=sphere(.14,mat('#906134'),-.02,-.35,.015,parts.leftElbow);glove.scale.set(.8,1.2,.6);const bat=new T.Group();body.add(bat);(()=>{const shape=[[.038,0],[.038,.025],[.019,.05],[.019,.24],[.026,.48],[.041,.67],[.047,.85],[.043,.92],[.025,.95],[0,.96]].map(([r,y])=>new T.Vector2(r,y));const wood=mesh(new T.LatheGeometry(shape,20),mat('#cda96d'),0,0,0,bat);wood.rotation.x=Math.PI})();bat.visible=kind==='bat';
 if(kind==='catch'){const mask=sphere(.15,mat('#354c60',{wireframe:true}),0,.66,.045,body);box(.3,.34,.14,mat('#253e55'),0,.17,.18,body)}
 const front=mesh(new T.PlaneGeometry(.34,.21),mat('#ffffff',{transparent:true}),0,.16,.148,body);const back=mesh(new T.PlaneGeometry(.35,.31),mat('#ffffff',{transparent:true}),0,.17,-.148,body);back.rotation.y=Math.PI;
 return {group,body,uniform,parts,glove,bat,front,back,key:'',kind};
 }
 const pitcher=athlete('pitch'),batter=athlete('bat'),catcher=athlete('catch'),umpire=athlete('ump');const fielders=Array.from({length:7},()=>athlete('field')),runners=Array.from({length:4},()=>athlete('run'));
 pitcher.group.position.set(0,.28,18.44);pitcher.group.rotation.y=Math.PI;catcher.group.position.set(0,0,-1.25);umpire.group.position.set(.5,0,-2.2);catcher.uniform.color.set('#273e58');umpire.uniform.color.set('#1c2831');
 const zone=box(.72,.84,.005,mat('#ffffff',{transparent:true,opacity:.08,depthWrite:false}),0,1.05,.2);zone.castShadow=false;const reticle=mesh(new T.TorusGeometry(.105,.009,8,30),mat('#f5d467',{emissive:'#af9130'}),0,1.05,.22);const ball=sphere(.075,mat('#f6f0da'),0,0,0);
 const seam=new T.LineLoop(new T.BufferGeometry().setFromPoints(Array.from({length:32},(_,i)=>{const t=i*Math.PI/16;return new T.Vector3(.076*Math.cos(t),.076*Math.sin(t),.013*Math.sin(t*2))})),new T.LineBasicMaterial({color:'#b94739'}));ball.add(seam);const landing=mesh(new T.TorusGeometry(1,.06,8,40),mat('#ffd66f',{emissive:'#a67926'}));landing.rotation.x=Math.PI/2;
 function playerData(name){for(const team of rosterState.squads||[]) {const p=team.find(p=>p.name===name);if(p)return p}return {name,height:183,number:''}}
 function nameMap(name,number){const c=document.createElement('canvas');c.width=256;c.height=192;const q=c.getContext('2d');q.fillStyle='#f5f0df';q.textAlign='center';q.font='bold 28px system-ui';q.fillText(name,128,40);q.font='bold 94px system-ui';q.fillText(number||'CPBL',128,143);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
 function dress(actor,name,team){const p=playerData(name),key=name+team.color;if(actor.key===key)return;actor.key=key;actor.uniform.color.set(team.color);actor.group.scale.setScalar((p.height||183)/183);const old=actor.front.material.map;old?.dispose();const texture=nameMap(name,p.number);for(const plane of [actor.front,actor.back]){plane.material.map=texture;plane.material.needsUpdate=true}}
 function resetPose(a){Object.values(a.parts).forEach(p=>p.rotation.set(0,0,0));a.body.rotation.set(0,0,0)}
 function crouch(a){a.body.position.y=.68;a.parts.leftLeg.rotation.z=.65;a.parts.rightLeg.rotation.z=-.65;a.parts.leftKnee.rotation.x=-1.3;a.parts.rightKnee.rotation.x=-1.3;a.parts.leftArm.rotation.x=-.7;a.parts.rightArm.rotation.x=-.7;}
 function moveRunner(a,from,steps,t){a.group.visible=true;const p=Math.min(steps,t*steps),i=Math.floor(p),f=p-i;const start=basePositions[(from+i)%4],end=basePositions[(from+i+1)%4];a.group.position.copy(start).lerp(end,f);a.group.rotation.y=Math.atan2(end.x-start.x,end.z-start.z);a.parts.leftLeg.rotation.x=Math.sin(t*35)*.7;a.parts.rightLeg.rotation.x=-Math.sin(t*35)*.7;a.parts.leftArm.rotation.x=-Math.sin(t*35)*.6;a.parts.rightArm.rotation.x=Math.sin(t*35)*.6;}
 const ballMarker=document.createElement('div');ballMarker.className='ball-marker hidden';ballMarker.innerHTML='<b></b><span>球</span>';stage.append(ballMarker);
 const trailGeometry=new T.BufferGeometry(),trailArray=new Float32Array(32*3);trailGeometry.setAttribute('position',new T.BufferAttribute(trailArray,3));const trail=new T.Line(trailGeometry,new T.LineBasicMaterial({color:'#fff2ac',transparent:true,opacity:.8,depthTest:false}));trail.frustumCulled=false;scene.add(trail);
 let cssWidth=0,cssHeight=0,contextLost=false,lastPaint=0,frameCount=0,slowFrames=0;
 const sceneError={count:0};window.CPBL_RENDER_STATS={frames:0,contextLosses:0,recoveries:0,errors:0};
 // A translucent bat-shaped contact cursor; the player's actual bat stays in the animation.
 const outline=[[-.48,-.018],[-.30,-.018],[-.12,-.027],[.12,-.050],[.40,-.058],[.47,-.035],[.49,0],[.47,.035],[.40,.058],[.12,.050],[-.12,.027],[-.30,.018],[-.48,.018]];
 const cursorShape=new T.Shape();outline.forEach(([x,y],i)=>i?cursorShape.lineTo(x,y):cursorShape.moveTo(x,y));cursorShape.closePath();
 const aimBat=new T.Group();scene.add(aimBat);const cursorFill=new T.Mesh(new T.ShapeGeometry(cursorShape),new T.MeshBasicMaterial({color:'#8edaf5',transparent:true,opacity:.15,side:T.DoubleSide,depthTest:false,depthWrite:false}));aimBat.add(cursorFill);
 const contour=new T.LineLoop(new T.BufferGeometry().setFromPoints(outline.map(([x,y])=>new T.Vector3(x,y,0))),new T.LineBasicMaterial({color:'#a5e8ff',transparent:true,opacity:.95,depthTest:false}));aimBat.add(contour);aimBat.renderOrder=10;
 const swingTrail=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:'#c4ecff',transparent:true,opacity:.7,depthTest:false}));swingTrail.frustumCulled=false;scene.add(swingTrail);const swingTrailPoints=new Float32Array(24*3);swingTrail.geometry.setAttribute('position',new T.BufferAttribute(swingTrailPoints,3));
 const projected=new T.Vector3(),cameraTarget=new T.Vector3(),lookTarget=new T.Vector3(),gloveWorld=new T.Vector3();
 const ballShadow=mesh(new T.CircleGeometry(.18,20),new T.MeshBasicMaterial({color:'#17251b',transparent:true,opacity:.4,depthWrite:false}),0,.05,0);ballShadow.rotation.x=-Math.PI/2;ballShadow.castShadow=false;
 const fieldActors=[...fielders,pitcher],positions=['一壘手','二壘手','游擊手','三壘手','左外野手','中外野手','右外野手'];
 function fieldName(i,side){const players=rosterState.squads?.[side]||[];return players.find(p=>p.position===positions[i]&&tv.lineupIds?.[side]?.includes(p.id))?.name||PLAYERS[side?state.homeIndex:state.awayIndex][i]||'守備員'}
 // Anatomical left is +X when the avatar faces its local +Z.
 const down=new T.Vector3(0,-1,0);
 function armTo(actor,side,target){const arm=actor.parts[side+'Arm'],elbow=actor.parts[side+'Elbow'],shoulder=arm.position,delta=target.clone().sub(shoulder),d=Math.min(.635,Math.max(.04,delta.length())),unit=delta.normalize(),along=(d*d+.30*.30-.34*.34)/(2*d),bend=Math.sqrt(Math.max(0,.30*.30-along*along));const normal=new T.Vector3(side==='left'?.35:-.35,-.6,-.6);normal.addScaledVector(unit,-normal.dot(unit)).normalize();const joint=shoulder.clone().addScaledVector(unit,along).addScaledVector(normal,bend);arm.quaternion.setFromUnitVectors(down,joint.clone().sub(shoulder).normalize());const fore=new T.Quaternion().setFromUnitVectors(down,target.clone().sub(joint).normalize());elbow.quaternion.copy(arm.quaternion).invert().multiply(fore);}
 function battingPose(actor,left,stamp){const sign=left?-1:1,u=tv.swung?Math.min(1,Math.max(0,(stamp-(tv.swingStart||stamp))/520)):0,contact=CPBLPhysics.smooth(Math.min(1,u/.48)),follow=CPBLPhysics.smooth(Math.max(0,(u-.48)/.52));actor.body.rotation.y=sign*(-.20+contact*.42+follow*.65);actor.body.rotation.x=.06;actor.parts.leftLeg.rotation.z=.12;actor.parts.rightLeg.rotation.z=-.12;actor.parts.leftKnee.rotation.x=-.12;actor.parts.rightKnee.rotation.x=-.12;
  const grip=new T.Vector3(sign*(.10-contact*.06-follow*.16),.44-contact*.30+follow*.26,.13+contact*.25-follow*.14),tip=new T.Vector3(sign*(.24-contact*.20-follow*.85),1.24-contact*1.12+follow*.65,-.30+contact*1.6-follow*.92),direction=tip.clone().sub(grip).normalize();actor.bat.position.copy(grip);actor.bat.quaternion.setFromUnitVectors(down,direction);actor.glove.visible=false;armTo(actor,'left',grip.clone().addScaledVector(direction,left?.035:-.025));armTo(actor,'right',grip.clone().addScaledVector(direction,left?-.025:.035));
 }
 function applyDelivery(actor,profile,stamp){const left=profile.hand==='L',throwing=left?'left':'right',glove=left?'right':'left',sign=left?-1:1;
  if(actor.glove.parent!==actor.parts[glove+'Elbow'])actor.parts[glove+'Elbow'].add(actor.glove);
  const elapsed=tv.deliveryAt?stamp-tv.deliveryAt:2000,pose=CPBLPhysics.delivery(elapsed);
  actor.parts[glove+'Leg'].rotation.x=pose[0];actor.parts[glove+'Knee'].rotation.x=pose[1];actor.parts[throwing+'Arm'].rotation.x=pose[2];actor.parts[throwing+'Elbow'].rotation.x=pose[3];actor.parts[glove+'Arm'].rotation.x=pose[4];actor.body.rotation.y=sign*pose[5];actor.body.rotation.x=pose[6];actor.group.position.z=18.44-pose[7];
  actor.parts[throwing+'Leg'].rotation.x=-pose[6]*.7;actor.parts[throwing+'Knee'].rotation.x=-pose[6]*.7;
  actor.parts[glove+'Leg'].position.z=-pose[7]*.25;
  if(profile.style==='side')actor.parts[throwing+'Arm'].rotation.z=sign*.9*Math.sin(Math.PI*Math.min(1,elapsed/1500));
 }
 function render3d(now){requestAnimationFrame(render3d);if(contextLost||document.hidden||$('#gameScreen').classList.contains('hidden')||now-lastPaint<1000/30)return;
  const paintStart=performance.now();lastPaint=now;try{const stamp=tv.paused?tv.pauseAt:now,elapsed=stamp-tv.start,width=stage.clientWidth,height=stage.clientHeight;if(!width||!height)return;
  if(width!==cssWidth||height!==cssHeight){cssWidth=width;cssHeight=height;renderer.setSize(width,height,false);}camera.aspect=width/height;
  const h=tv.hit,tracking=!!h&&(tv.phase==='hit'||tv.phase==='result'),fs=tracking?1-h.batSide:fieldingTeam(),bs=1-fs,profile=tv.pitchers[fs]||activePitcher();
  dress(pitcher,profile.name,teamFor(fs));dress(batter,tracking?h.batter:batterName(),teamFor(bs));resetPose(pitcher);resetPose(batter);resetPose(catcher);resetPose(umpire);crouch(catcher);umpire.body.position.y=1.1;umpire.parts.leftLeg.rotation.x=.12;umpire.parts.rightLeg.rotation.x=.12;
  pitcher.group.rotation.y=Math.PI;pitcher.group.position.set(0,.28,18.44);applyDelivery(pitcher,profile,stamp);
  const battingLeft=playerTraits.get(tv.lineupIds?.[bs]?.[state.orders[bs]%9])?.batHand==='L';batter.group.position.set(battingLeft?-1.1:1.1,0,.15);batter.group.rotation.y=battingLeft?Math.PI/2:-Math.PI/2;
  const swing=tv.swung?CPBLPhysics.smooth((stamp-(tv.swingStart||stamp))/520):0;battingPose(batter,battingLeft,stamp);
  stage.dataset.ballPhase='none';ball.visible=false;landing.visible=false;trail.visible=false;ballShadow.visible=false;ballMarker.classList.add('hidden');batter.group.visible=!playerBatting()&&!tracking;catcher.group.visible=umpire.group.visible=!playerBatting()||tracking;
  zone.visible=!tracking;reticle.visible=zone.visible&&(!playerBatting()||tv.power);reticle.position.set((playerBatting()?-1:1)*tv.aim.x*.3,1.1-tv.aim.y*.35,.22);
  fielders.forEach((a,i)=>{a.group.visible=true;dress(a,fieldName(i,fs),teamFor(fs));resetPose(a);const p=CPBLPhysics.fielders[i];a.group.position.set(p.x,0,p.z);a.group.rotation.y=Math.PI;});runners.forEach(a=>a.group.visible=false);
  if(tv.phase==='pitch'&&tv.flight){const f=tv.flight,t=Math.min(1,elapsed/f.duration),p=CPBLPhysics.pitchPoint(f,t);ball.visible=true;ball.position.set(p.x,p.y,p.z);}
  if(tracking){const playElapsed=Math.min(stamp-h.start,h.durationMs),p=CPBLPhysics.playPoint(h,playElapsed),defender=fieldActors[h.fielder],fp=CPBLPhysics.fielderPoint(h,playElapsed);
   stage.dataset.ballPhase=p.phase;ball.visible=true;ball.position.set(p.x,p.y,p.z);landing.visible=false;landing.position.set(h.land.x,.08,h.land.z);
   defender.group.position.set(fp.x,0,fp.z);const original=CPBLPhysics.fielders[h.fielder];defender.group.rotation.y=Math.atan2(h.fieldTarget.x-original.x,h.fieldTarget.z-original.z);
   if(fp.moving){defender.parts.leftLeg.rotation.x=Math.sin(playElapsed/95)*.6;defender.parts.rightLeg.rotation.x=-Math.sin(playElapsed/95)*.6;defender.parts.leftArm.rotation.x=-Math.sin(playElapsed/95)*.4;defender.parts.rightArm.rotation.x=Math.sin(playElapsed/95)*.4;}
   if(p.phase==='caught'){defender.parts.leftArm.rotation.x=-1.2;defender.parts.leftElbow.rotation.x=-.7;defender.group.updateMatrixWorld(true);ball.position.copy(defender.glove.getWorldPosition(gloveWorld));}
   if(h.event!=='catch'&&h.event!=='homer'){const baseIndex=h.throwBase??0,target=basePositions[baseIndex],receiverIndex=baseIndex===2?(h.fielder===3?2:3):baseIndex===1?(h.fielder===1?2:1):0,receiver=baseIndex===3?catcher:h.fielder===0&&baseIndex===0?pitcher:fielders[receiverIndex],initial=baseIndex===3?{x:0,z:-1.25}:receiver===pitcher?CPBLPhysics.fielders[7]:CPBLPhysics.fielders[receiverIndex],cover=CPBLPhysics.smooth(Math.max(0,playElapsed-150)/Math.max(600,Math.hypot(target.x-initial.x,target.z-initial.z)/7*1000));receiver.group.position.set(initial.x+(target.x-initial.x)*cover,0,initial.z+(target.z-initial.z)*cover);receiver.group.rotation.y=Math.atan2(h.pickup.x-target.x,h.pickup.z-target.z);if(h.relay){const cutoff=fielders[2],from=CPBLPhysics.fielders[2],t=CPBLPhysics.smooth(playElapsed/Math.max(800,Math.hypot(h.relay.x-from.x,h.relay.z-from.z)/7*1000));cutoff.group.position.set(from.x+(h.relay.x-from.x)*t,0,from.z+(h.relay.z-from.z)*t);cutoff.group.rotation.y=Math.atan2(h.pickup.x-h.relay.x,h.pickup.z-h.relay.z);if(p.phase==='relay')cutoff.parts.leftArm.rotation.x=-1.1;}if(p.phase==='received'){receiver.group.updateMatrixWorld(true);ball.position.copy(receiver.glove.getWorldPosition(gloveWorld));}if(p.phase==='throw'||p.phase==='received'){const direction=h.relay||target;defender.group.rotation.y=Math.atan2(direction.x-h.pickup.x,direction.z-h.pickup.z);if(h.relay&&playElapsed>h.pickupMs+h.relayMs+220){const cutoff=fielders[2];cutoff.group.rotation.y=Math.atan2(target.x-h.relay.x,target.z-h.relay.z);cutoff.parts.rightArm.rotation.x=-1.4+Math.min(1,(playElapsed-h.pickupMs-h.relayMs-220)/350)*2.1;}receiver.parts.leftArm.rotation.x=-.9;defender.parts.rightArm.rotation.x=-1.7+Math.min(1,(playElapsed-h.pickupMs)/350)*2.3;}}

   const steps=h.type==='HR'?4:h.type==='2B'?2:h.type==='OUT'?1:1,runT=Math.min(1,playElapsed/h.runnerDurationMs);runners.forEach(a=>a.uniform.color.set(teamFor(h.batSide).color));moveRunner(runners[0],3,steps,runT);h.runners.forEach((r,i)=>{if(r&&h.event!=='catch')moveRunner(runners[i+1],i,Math.min(steps,3-i),Math.min(1,playElapsed/(h.runnerMs*Math.min(steps,3-i))))});
   camera.fov=camera.aspect<1?54:43;cameraTarget.set(ball.position.x+8,Math.max(13,ball.position.y+11),ball.position.z-29);camera.position.lerp(cameraTarget,.18);lookTarget.copy(ball.position);camera.lookAt(lookTarget);
   trail.visible=p.phase!=='caught'&&p.phase!=='received';for(let j=0;j<32;j++){const q=CPBLPhysics.playPoint(h,Math.max(0,playElapsed-j*25));trailArray[j*3]=q.x;trailArray[j*3+1]=q.y;trailArray[j*3+2]=q.z;}trailGeometry.attributes.position.needsUpdate=true;
   ballMarker.querySelector('span').textContent='';
   if(p.phase==='rolling'){ball.rotation.x=playElapsed*.012;ball.rotation.z=playElapsed*.007;}
  }else if(playerBatting()){camera.fov=camera.aspect<1?52:43;camera.position.set(0,1.65,-2.6);camera.lookAt(0,1.2,18.44);}else{camera.fov=camera.aspect<1?13:10;camera.position.set(2.3,3.3,49);camera.lookAt(0,1,7);}
  const swingActive=tv.swung&&stamp-(tv.swingStart||0)<350,aim=tv.swung?(tv.swingAim||tv.aim):tv.aim;
  aimBat.visible=playerBatting()&&!tv.power&&!tracking;aimBat.position.set(-aim.x*.3,1.1-aim.y*.35,.22);aimBat.rotation.z=swingActive?-.55+swing*1.1:0;
  swingTrail.visible=aimBat.visible&&swingActive;if(swingTrail.visible){for(let j=0;j<24;j++){const angle=-.6+Math.max(0,swing-j*.025)*1.2;swingTrailPoints[j*3]=-aim.x*.3+Math.cos(angle)*.48;swingTrailPoints[j*3+1]=1.1-aim.y*.35+Math.sin(angle)*.48;swingTrailPoints[j*3+2]=.23;}swingTrail.geometry.attributes.position.needsUpdate=true;}
  if(ball.visible){ballShadow.visible=true;ballShadow.position.set(ball.position.x,.06,ball.position.z);ballShadow.scale.setScalar(1+Math.min(3,ball.position.y*.13));ballShadow.material.opacity=Math.max(.15,.55-ball.position.y*.012);}
  camera.updateProjectionMatrix();renderer.shadowMap.needsUpdate=frameCount++%3===0;renderer.render(scene,camera);window.CPBL_RENDER_STATS.frames++;if(frameCount%30===0){stage.dataset.frames=String(window.CPBL_RENDER_STATS.frames);stage.dataset.errors=String(window.CPBL_RENDER_STATS.errors);stage.dataset.contextLosses=String(window.CPBL_RENDER_STATS.contextLosses)}
  if(ball.visible&&tracking){projected.copy(ball.position).project(camera);if(projected.z<1){ballMarker.classList.remove('hidden');ballMarker.style.left=((projected.x+1)*width/2)+'px';ballMarker.style.top=((1-projected.y)*height/2)+'px';ballMarker.classList.toggle('in-flight',tracking);}}
  if(performance.now()-paintStart>45)slowFrames++;else slowFrames=Math.max(0,slowFrames-1);if(slowFrames>30){renderer.setPixelRatio(1);renderer.shadowMap.enabled=false;slowFrames=0;}
  }catch(error){console.error('3D frame',error);window.CPBL_RENDER_STATS.errors++;if(++sceneError.count===1){if(!tv.paused)pause();announce('畫面暫停 · 請繼續');}}
 }
 const badge=document.createElement('span');badge.className='skin-badge';badge.textContent='3D LIVE · WEBGL';stage.append(badge);
 const meter=document.createElement('div');meter.className='pitch-meter hidden';meter.innerHTML='<span>在金色區域放開</span><div><b></b><i></i></div>';stage.append(meter);
 const fallbackPitch=drawPitchScene,fallbackHit=drawHitScene;drawPitchScene=function(){meter.classList.toggle('hidden',tv.phase!=='charge');if(tv.phase==='charge'){const stamp=tv.paused?tv.pauseAt:performance.now();meter.querySelector('i').style.left=((stamp-tv.start)/1000%1.5)/1.5*100+'%'}};drawHitScene=function(){};
 requestAnimationFrame(render3d);
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;window.CPBL_RENDER_STATS.contextLosses++;ballMarker.classList.add('hidden');if(!tv.paused)pause();badge.textContent='3D 畫面恢復中';renderer.setPixelRatio(1);renderer.shadowMap.enabled=false;try{const extension=renderer.getContext().getExtension('WEBGL_lose_context');setTimeout(()=>extension?.restoreContext(),1500)}catch(error){console.warn('Waiting for WebGL restore',error)}});
 renderer.domElement.addEventListener('webglcontextrestored',()=>{contextLost=false;cssWidth=cssHeight=0;sceneError.count=0;window.CPBL_RENDER_STATS.recoveries++;badge.textContent='3D LIVE · WEBGL';announce('3D 已恢復 · 點此繼續');});
})();
