/* Real WebGL scene, articulated athletes, perspective broadcast cameras.
   Models are original game avatars; no claim of photographic player likeness. */
(function(){
 if(!window.THREE)return;
 const T=window.THREE;let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'})}catch(e){return}
 renderer.domElement.className='webgl-canvas';renderer.domElement.setAttribute('aria-label','3D 棒球轉播場景');stage.prepend(renderer.domElement);canvas.style.visibility='hidden';
 renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
 const scene=new T.Scene();scene.background=new T.Color('#9aabb8');scene.fog=new T.Fog('#9aabb8',130,260);const camera=new T.PerspectiveCamera(6.5,16/9,.1,400);
 scene.add(new T.HemisphereLight('#d4e7fa','#394721',2.4));const sun=new T.DirectionalLight('#fff0d4',3.5);sun.position.set(-35,55,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:100,bottom:-30,near:1,far:160});sun.shadow.bias=-.0005;scene.add(sun);scene.add(sun.target);
 function mat(color,extra={}){return new T.MeshStandardMaterial({color,roughness:.8,...extra})}
 const white=mat('#e9e6d8'),soil=mat('#a88663'),grass=mat('#3e7040'),metal=mat('#627886',{metalness:.6}),skin=mat('#c59370'),dark=mat('#182735');
 function mesh(geometry,material,x=0,y=0,z=0,parent=scene){const o=new T.Mesh(geometry,material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 function box(w,h,d,m,x,y,z,parent){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,parent)}
 function sphere(r,m,x,y,z,parent){return mesh(new T.SphereGeometry(r,16,12),m,x,y,z,parent)}
 function cylinder(r,h,m,x,y,z,parent){return mesh(new T.CylinderGeometry(r,r,h,16),m,x,y,z,parent)}
 const ground=mesh(new T.PlaneGeometry(330,330),grass,0,-.03,70);ground.rotation.x=-Math.PI/2;
 for(let i=0;i<16;i++){const strip=mesh(new T.PlaneGeometry(8,180),mat(i%2?'#447746':'#3b6d3f'),(i-8)*8,.001,75);strip.rotation.x=-Math.PI/2;strip.castShadow=false;}
 const diamond=box(29,.025,29,soil,0,0,19.4);diamond.rotation.y=Math.PI/4;
 const center=box(24,.03,24,grass,0,.02,19.4);center.rotation.y=Math.PI/4;
 cylinder(2.75,.28,soil,0,.12,18.44);cylinder(4.7,.04,soil,0,.025,0);box(.61,.04,.15,white,0,.29,18.44);
 const basePositions=[new T.Vector3(19.4,0,19.4),new T.Vector3(0,0,38.8),new T.Vector3(-19.4,0,19.4),new T.Vector3(0,0,0)];basePositions.slice(0,3).forEach(p=>box(.38,.1,.38,white,p.x,.04,p.z));box(.42,.04,.42,white,0,.07,0);
 function segment(a,b,r,m,parent=scene){const direction=new T.Vector3().subVectors(b,a);const o=mesh(new T.CylinderGeometry(r,r,direction.length(),8),m,0,0,0,parent);o.position.copy(a).add(b).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),direction.normalize());return o}
 [-1,1].forEach(side=>{segment(new T.Vector3(0,.02,0),new T.Vector3(side*110,.02,110),.025,white);const outline=[[-.8,0],[.8,0],[.8,1.8],[-.8,1.8],[-.8,0]];for(let i=1;i<outline.length;i++)segment(new T.Vector3(side*1.25+outline[i-1][0]*.4,.065,outline[i-1][1]-.6),new T.Vector3(side*1.25+outline[i][0]*.4,.065,outline[i][1]-.6),.018,white)});
 function labelTexture(text,bg='#142f3d',fg='#eee9d9',size=512){const c=document.createElement('canvas');c.width=size;c.height=128;const q=c.getContext('2d');q.fillStyle=bg;q.fillRect(0,0,size,128);q.fillStyle=fg;q.font='bold 48px system-ui';q.textAlign='center';q.textBaseline='middle';q.fillText(text,size/2,67);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;return texture}
 // Backstop wall, dugouts, layered grandstands and a structural canopy.
 const wall=mat('#203d49');box(86,1.8,.6,wall,0,.9,-9);for(let i=0;i<7;i++){const ad=mesh(new T.PlaneGeometry(11.5,1.25),mat('#ffffff',{map:labelTexture(['CPBL','TAIWAN BASEBALL','PLAY BALL','NEXT PITCH','CPBL','HOME OF BASEBALL','2026'][i])}),-36+i*12,1.1,-8.65);ad.castShadow=false;}
 for(let row=0;row<18;row++){box(110,.34,1.15,mat('#4c6070'),0,1.8+row*.43,-10.5-row*1.2)}
 const seats=new T.InstancedMesh(new T.BoxGeometry(.42,.5,.48),mat('#315a7f'),18*150);const dummy=new T.Object3D();let n=0;for(let row=0;row<18;row++)for(let col=0;col<150;col++){dummy.position.set((col-75)*.7,2.15+row*.43,-10.5-row*1.2);dummy.updateMatrix();seats.setMatrixAt(n,dummy.matrix);seats.setColorAt(n,new T.Color(['#355b81','#99a8b3','#dab789','#1e445f'][(col*7+row*19)%4]));n++}scene.add(seats);
 const fans=new T.InstancedMesh(new T.SphereGeometry(.13,6,5),mat('#9b9c91'),800);for(let i=0;i<800;i++){const row=i%18,col=(i*43)%150;dummy.position.set((col-75)*.7,2.7+row*.43,-10.4-row*1.2);dummy.updateMatrix();fans.setMatrixAt(i,dummy.matrix);fans.setColorAt(i,new T.Color(['#b89778','#d6bda0','#d9d5c4','#335672','#a64443'][i%5]))}scene.add(fans);
 for(let x=-50;x<=50;x+=10){cylinder(.14,13,metal,x,6.5,-30);segment(new T.Vector3(x,12,-32),new T.Vector3(x,11,-8),.1,metal)}const roof=box(116,.15,27,mat('#e1e4e1',{metalness:.25}),0,12,-22);roof.rotation.x=.035;
 for(let i=0;i<70;i++){const a=i/70*Math.PI*2;const x=Math.cos(a)*132,z=57+Math.sin(a)*132;const section=box(12,7,7,mat('#324f60'),x,3.5,z);section.rotation.y=-a;}
 for(const [x,z] of [[-55,15],[55,15],[-75,90],[75,90]]){cylinder(.35,38,metal,x,19,z);box(10,4,.3,mat('#e3e7d6',{emissive:'#eee6d6',emissiveIntensity:.5}),x,37,z)}
 // Procedural articulated athlete: independent shoulders, elbows, hips and knees.
 function athlete(kind){const group=new T.Group(),uniform=mat('#ad3231'),pants=mat('#ece8dc'),parts={};scene.add(group);const body=new T.Group();body.position.y=1.18;group.add(body);const torso=mesh(new T.CapsuleGeometry(.20,.36,4,14),uniform,0,.18,0,body);torso.scale.set(1,1,.7);sphere(.14,skin,0,.67,0,body);sphere(.045,skin,-.14,.65,0,body);sphere(.045,skin,.14,.65,0,body);box(.07,.07,.09,skin,0,.64,.14,body);sphere(.14,uniform,0,.76,-.015,body).scale.y=.43;box(.21,.025,.22,uniform,0,.735,.13,body);box(.33,.07,.25,dark,0,-.15,0,body);
 for(const side of [-1,1]){const arm=new T.Group();arm.position.set(side*.23,.34,0);body.add(arm);cylinder(.075,.30,uniform,0,-.15,0,arm);const elbow=new T.Group();elbow.position.y=-.3;arm.add(elbow);cylinder(.055,.30,skin,0,-.15,0,elbow);sphere(.065,skin,0,-.34,0,elbow);parts[side<0?'leftArm':'rightArm']=arm;parts[side<0?'leftElbow':'rightElbow']=elbow;
 const hip=new T.Group();hip.position.set(side*.105,1.02,0);group.add(hip);cylinder(.085,.45,pants,0,-.23,0,hip);const knee=new T.Group();knee.position.y=-.45;hip.add(knee);cylinder(.070,.43,pants,0,-.20,0,knee);cylinder(.072,.12,uniform,0,-.38,0,knee);box(.14,.1,.29,dark,0,-.44,.065,knee);parts[side<0?'leftLeg':'rightLeg']=hip;parts[side<0?'leftKnee':'rightKnee']=knee;}
 const glove=sphere(.1,mat('#906134'),-.02,-.35,.015,parts.leftElbow);glove.scale.set(.8,1.2,.6);const bat=new T.Group();parts.rightElbow.add(bat);segment(new T.Vector3(0,-.3,0),new T.Vector3(0,-1.2,0),.033,mat('#cfae76'),bat);bat.visible=kind==='bat';
 if(kind==='catch'){const mask=sphere(.15,mat('#354c60',{wireframe:true}),0,.66,.045,body);box(.3,.34,.14,mat('#253e55'),0,.17,.18,body)}
 const front=mesh(new T.PlaneGeometry(.34,.21),mat('#ffffff',{transparent:true}),0,.16,.148,body);const back=mesh(new T.PlaneGeometry(.35,.31),mat('#ffffff',{transparent:true}),0,.17,-.148,body);back.rotation.y=Math.PI;
 return {group,body,uniform,parts,bat,front,back,key:'',kind};
 }
 const pitcher=athlete('pitch'),batter=athlete('bat'),catcher=athlete('catch'),umpire=athlete('ump');const fielders=Array.from({length:7},()=>athlete('field')),runners=Array.from({length:4},()=>athlete('run'));
 pitcher.group.position.set(0,.28,18.44);pitcher.group.rotation.y=Math.PI;catcher.group.position.set(0,0,-1.25);umpire.group.position.set(.5,0,-2.2);catcher.uniform.color.set('#273e58');umpire.uniform.color.set('#1c2831');
 const zone=box(.72,.84,.005,mat('#ffffff',{transparent:true,opacity:.08,depthWrite:false}),0,1.05,.2);zone.castShadow=false;const reticle=mesh(new T.TorusGeometry(.105,.009,8,30),mat('#f5d467',{emissive:'#af9130'}),0,1.05,.22);const ball=sphere(.055,mat('#f6f0da'),0,0,0);const landing=mesh(new T.TorusGeometry(1,.06,8,40),mat('#ffd66f',{emissive:'#a67926'}));landing.rotation.x=Math.PI/2;
 function playerData(name){for(const team of rosterState.squads||[]) {const p=team.find(p=>p.name===name);if(p)return p}return {name,height:183,number:''}}
 function nameMap(name,number){const c=document.createElement('canvas');c.width=256;c.height=192;const q=c.getContext('2d');q.fillStyle='#f5f0df';q.textAlign='center';q.font='bold 28px system-ui';q.fillText(name,128,40);q.font='bold 94px system-ui';q.fillText(number||'CPBL',128,143);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
 function dress(actor,name,team){const p=playerData(name),key=name+team.color;if(actor.key===key)return;actor.key=key;actor.uniform.color.set(team.color);actor.group.scale.setScalar((p.height||183)/183);const texture=nameMap(name,p.number);for(const plane of [actor.front,actor.back]){plane.material.map?.dispose();plane.material.map=texture;plane.material.needsUpdate=true}}
 function resetPose(a){Object.values(a.parts).forEach(p=>p.rotation.set(0,0,0));a.body.rotation.set(0,0,0)}
 function crouch(a){a.body.position.y=.68;a.parts.leftLeg.rotation.z=.65;a.parts.rightLeg.rotation.z=-.65;a.parts.leftKnee.rotation.x=-1.3;a.parts.rightKnee.rotation.x=-1.3;a.parts.leftArm.rotation.x=-.7;a.parts.rightArm.rotation.x=-.7;}
 function moveRunner(a,from,steps,t){a.group.visible=true;const p=Math.min(steps,t*steps),i=Math.floor(p),f=p-i;const start=basePositions[(from+i)%4],end=basePositions[(from+i+1)%4];a.group.position.copy(start).lerp(end,f);a.group.rotation.y=Math.atan2(end.x-start.x,end.z-start.z);a.parts.leftLeg.rotation.x=Math.sin(t*35)*.7;a.parts.rightLeg.rotation.x=-Math.sin(t*35)*.7;a.parts.leftArm.rotation.x=-Math.sin(t*35)*.6;a.parts.rightArm.rotation.x=Math.sin(t*35)*.6;}
 function render3d(now){if($('#gameScreen').classList.contains('hidden')){requestAnimationFrame(render3d);return}const stamp=tv.paused?tv.pauseAt:now,elapsed=stamp-tv.start;const width=stage.clientWidth,height=stage.clientHeight;if(renderer.domElement.width!==Math.round(width*renderer.getPixelRatio())||renderer.domElement.height!==Math.round(height*renderer.getPixelRatio()))renderer.setSize(width,height,false);camera.aspect=width/height;const fs=tv.phase==='hit'?tv.pitchActor:fieldingTeam(),bs=1-fs;dress(pitcher,activePitcher().name,teamFor(fs));dress(batter,tv.phase==='hit'?tv.hit.batter:batterName(),teamFor(bs));resetPose(pitcher);resetPose(batter);resetPose(catcher);resetPose(umpire);crouch(catcher);umpire.body.position.y=1.1;umpire.parts.leftLeg.rotation.x=.12;umpire.parts.rightLeg.rotation.x=.12;catcher.parts.leftElbow.rotation.x=-1.2;
 const left=activePitcher().hand==='L';pitcher.group.rotation.y=Math.PI;const wind=tv.phase==='windup'?elapsed/900:tv.phase==='charge'?Math.min(.8,elapsed/1000):tv.phase==='pitch'?1+Math.min(1,elapsed/230):0;const throwing=left?'left':'right',glove=left?'right':'left';if(wind<=1){pitcher.parts[throwing+'Arm'].rotation.x=-wind*1.9;pitcher.parts[throwing+'Elbow'].rotation.x=-wind*1.1;pitcher.parts[glove+'Leg'].rotation.x=wind*1.1;pitcher.parts[glove+'Knee'].rotation.x=-wind*1.2;}else{pitcher.parts[throwing+'Arm'].rotation.x=-2.8+(wind-1)*2.5;pitcher.parts[glove+'Leg'].rotation.x=.45;pitcher.body.rotation.x=(wind-1)*.4}if(activePitcher().style==='side')pitcher.parts[throwing+'Arm'].rotation.z=-1.1;
 const battingLeft=['王柏融','陳傑憲','林立','朱育賢','廖健富','陳子豪','陳文杰','陳晨威'].includes(batterName());batter.group.position.set(battingLeft?1.1:-1.1,0,.15);batter.group.rotation.y=battingLeft?-Math.PI/2:Math.PI/2;const swing=tv.swung?Math.min(1,(stamp-(tv.swingStart||stamp))/250):0;batter.body.rotation.y=-.4+swing*1.8;batter.parts.rightArm.rotation.x=-1.9+swing*.9;batter.parts.leftArm.rotation.x=-1.6+swing*.6;batter.parts.rightElbow.rotation.x=-.8;batter.parts.leftElbow.rotation.x=-1;batter.bat.rotation.z=.5+swing*1.1;
 ball.visible=false;landing.visible=false;zone.visible=reticle.visible=tv.phase!=='hit';reticle.position.set(tv.aim.x*.3,1.1-tv.aim.y*.35,.22);
 fielders.forEach((a,i)=>{a.group.visible=tv.phase==='hit';a.uniform.color.set(teamFor(fs).color);a.group.position.set([20,-20,-8,8,-40,0,40][i],0,[20,20,31,31,72,95,72][i]);a.group.rotation.y=Math.PI});runners.forEach(a=>a.group.visible=false);
 if(tv.phase==='pitch'){const f=tv.flight,t=Math.min(1,elapsed/f.duration),dx={'滑球':.6,'伸卡球':-.32,'卡特球':.2,'變速球':-.15,'指叉球':.04,'四縫線':0}[f.type]||0;ball.visible=true;ball.position.set(.42*(1-t)+f.x*.3*t+Math.sin(t*Math.PI)*dx,1.78*(1-t)+(1.1-f.y*.35)*t-Math.sin(t*Math.PI)*.12,18.3*(1-t));}
 if(tv.phase==='hit'&&tv.hit){const h=tv.hit,t=Math.min(1,elapsed/2000),target=new T.Vector3((h.x-640)/440*70,0,h.type==='HR'?195:45+(460-h.y)/230*50);ball.visible=true;ball.position.set(target.x*t,1.1*(1-t)+Math.sin(t*Math.PI)*(h.type==='HR'?32:19),target.z*t);landing.visible=true;landing.position.set(target.x,.15,target.z);const nearest=fielders[h.x<640?4:6];nearest.group.position.lerpVectors(new T.Vector3(h.x<640?-40:40,0,72),target,Math.min(1,t*1.12));nearest.parts.leftLeg.rotation.x=Math.sin(t*30)*.6;nearest.parts.rightLeg.rotation.x=-Math.sin(t*30)*.6;const steps=h.type==='HR'?4:h.type==='2B'?2:h.type==='OUT'?0:1;runners.forEach(a=>a.uniform.color.set(teamFor(h.batSide).color));moveRunner(runners[0],3,steps,t);h.runners.forEach((r,i)=>{if(r)moveRunner(runners[i+1],i,Math.min(steps,3-i),t)});camera.fov=48;camera.position.set(ball.position.x*.24,48,ball.position.z+75);camera.lookAt(ball.position.x*.4,ball.position.y*.2,Math.max(20,ball.position.z*.9));}else{camera.fov=camera.aspect<1?8:6.5;camera.position.set(3.1,4.5,85);camera.lookAt(.15,1.1,6);}
 camera.updateProjectionMatrix();renderer.render(scene,camera);requestAnimationFrame(render3d);
 }
 const badge=document.createElement('span');badge.className='skin-badge';badge.textContent='3D LIVE · WEBGL';stage.append(badge);
 const meter=document.createElement('div');meter.className='pitch-meter hidden';meter.innerHTML='<span>在金色區域放開</span><div><b></b><i></i></div>';stage.append(meter);
 const fallbackPitch=drawPitchScene,fallbackHit=drawHitScene;drawPitchScene=function(){meter.classList.toggle('hidden',tv.phase!=='charge');if(tv.phase==='charge'){const stamp=tv.paused?tv.pauseAt:performance.now();meter.querySelector('i').style.left=((stamp-tv.start)/1000%1.5)/1.5*100+'%'}};drawHitScene=function(){};
 requestAnimationFrame(render3d);
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();renderer.domElement.style.display='none';canvas.style.visibility='visible';drawPitchScene=fallbackPitch;drawHitScene=fallbackHit;badge.textContent='2D 相容模式'});
})();
