const assert=require('node:assert/strict');require('../baseball-engine.js');require('../baseball-rules.js');const P=CPBLPhysics,R=CPBLRules;
const h={kind:'ground',event:'groundout',type:'OUT',fielder:0,pickup:{x:-15,z:22},land:{x:-15,z:22},fieldTarget:{x:-15,z:22},flightMs:650,fieldAtMs:950,pickupMs:1800,runnerMs:4500,relay:null};R.plan(h,{bases:[null,null,null],outs:0,batter:'打者',inning:1,runDifference:0});assert(h.throwLegs.some(l=>l.base===0&&l.receiver===7));const first=h.throwLegs.find(l=>l.receiver===7&&l.base===0);assert(first.end>=(P.runTime(Math.hypot(P.bases[0].x,P.bases[0].z-18.44),6.4)+.32)*1000,'Pitcher receives before reaching first base');const cover=P.supportPoint(h,7,6000);assert.equal(cover.role,'cover-first');assert(Math.hypot(cover.x-P.bases[0].x,cover.z-P.bases[0].z)<.001);
for(const base of [1,2,3]){const play={kind:'ground',event:'hit',fielder:5,fieldTarget:{x:0,z:90},pickup:{x:0,z:90},throwBase:base,throwLegs:[{receiver:base===3?8:base,base,from:{x:0,z:55},to:P.bases[base]}]};const at=P.supportPoint(play,7,15000);assert.equal(at.role,base===1?'backup-second':base===2?'backup-third':'backup-home');const b=P.bases[base],v={x:b.x,z:b.z-55};assert((at.x-b.x)*v.x+(at.z-b.z)*v.z>0,'Pitcher must back up beyond target, not approach the ball');assert(Math.abs(Math.hypot(at.x-b.x,at.z-b.z)-7)<.001);}
let seed=823,checked=0,attempts=0;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32};
for(let n=0;n<2500;n++){const h=P.createPlay(.8,false,{x:0},rand);if(h.kind!=='ground'||h.event==='homer')continue;checked++;for(const a of h.fieldingAttempts)if(a)attempts++;
 // No legal glove interception may exist significantly earlier than the selected pickup.
 for(let ms=25;ms<h.fieldAtMs-25&&ms<(h.trajectory.length-1)*25;ms+=25){const p=h.trajectory[ms/25];if(ms<h.flightMs||p.y>1.25)continue;const x=Math.sin(h.angle)*p.distance,z=Math.cos(h.angle)*p.distance;h.defenseStarts.forEach((f,i)=>{const d=Math.hypot(x-f.x,z-f.z),reaction=i===7?.32:.22;if(i===7&&(d>12||z>30)||ms/1000<reaction)return;assert(d>P.runDistance(ms/1000-reaction,i===7?6.4:7.7)+.65-1e-8,'A defender could intercept this ground ball earlier');});}
 const at=P.fielderPoint(h,h.fieldAtMs);assert(Math.hypot(at.x-h.pickup.x,at.z-h.pickup.z)<=.65+1e-7);assert(h.fielder!==7||Math.hypot(h.pickup.x,h.pickup.z-17.65)<=12.001,'Pitcher must not retrieve deep outfield balls');}
assert(checked>500&&attempts>10);console.log({grounders:checked,interceptionAttempts:attempts,pitcherCoverAndBackups:'passed'});

let overlap=0;seed=313;for(let n=0;n<1000;n++){const h=R.plan(P.createPlay(.9,false,{x:0,y:0},rand,['跑者',null,null]),{bases:['跑者',null,null],outs:0,batter:'打者',inning:1,runDifference:0});for(const leg of h.throwLegs){const a=h.fieldingAttempts[leg.receiver];if(!a)continue;const before=P.supportPoint(h,leg.receiver,a.at-100);assert.equal(before.role,'intercept-attempt');const after=P.supportPoint(h,leg.receiver,a.end+1);assert(Math.hypot(after.x-a.target.x,after.z-a.target.z)<.001,'Coverage transition teleports');assert(leg.end>=P.coverArrival(h,leg.receiver,leg.receiverPosition),'Throw arrives before receiver finishes pursuit and reaches bag');overlap++;}}assert(overlap>20);console.log({receiversWhoPursueBeforeCoverage:overlap});
