/* Full state + CPU Three.js scene regression. Does not emulate a real GPU. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),elements=new Map();let time=1000,frames=[];
class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this._html='';this.textContent='';this.value='';this.options=[];this.dataset={};this.style={setProperty(k,v){this[k]=v}};this.hidden=false;this.clientWidth=390;this.clientHeight=780;this.events={};const classes=new Set();this.classList={add:(...xs)=>xs.forEach(x=>classes.add(x)),remove:(...xs)=>xs.forEach(x=>classes.delete(x)),contains:x=>classes.has(x),toggle:(x,on)=>{on=on===undefined?!classes.has(x):on;on?classes.add(x):classes.delete(x);return on}};}
 set innerHTML(html){this._html=html;for(const m of html.matchAll(/id="([^"]+)"/g)){if(!elements.has('#'+m[1]))elements.set('#'+m[1],new Element())}this.options=[...html.matchAll(/<option value="([^"]+)"/g)].map(m=>({value:m[1]}));}
 get innerHTML(){return this._html}
 append(...xs){for(const x of xs)x.parent=this}prepend(x){this.append(x)}after(){}replaceWith(){}
 querySelector(selector){return get(selector)}querySelectorAll(){return []}
 setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]}
 addEventListener(k,fn){(this.events[k]??=[]).push(fn)}setPointerCapture(){}
 getBoundingClientRect(){return {width:this.clientWidth,height:this.clientHeight,left:0,top:0}}
 getContext(){return canvasContext}
}
const canvasContext=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})}, {get:(o,k)=>k in o?o[k]:(()=>{})});
function get(selector){if(!elements.has(selector)){const element=new Element(selector.includes('Canvas')?'canvas':'div');if(['#gameScreen','#seasonScreen'].includes(selector))element.classList.add('hidden');if(selector==='#opponentSelect')element.value='random';if(selector==='#stadiumSelect')element.value='home';elements.set(selector,element)}return elements.get(selector)}
const events={},storage=new Map(),errors=[];
const sandbox={console:{log(){},warn(){},error:(...a)=>errors.push(a.join(' '))},document:{hidden:false,querySelector:get,querySelectorAll:()=>[],createElement:t=>new Element(t),addEventListener:(k,fn)=>(events[k]??=[]).push(fn)},performance:{now:()=>time},navigator:{getGamepads:()=>[]},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},location:{protocol:'https:'},requestAnimationFrame:fn=>frames.push(fn),setInterval(){},setTimeout(){},fetch:async()=>({ok:false,status:503}),Audio:class{constructor(){this.paused=true}pause(){this.paused=true}play(){this.paused=false;return Promise.resolve()}load(){}removeAttribute(){}},AudioContext:class{constructor(){this.state='running'}},Float32Array,Uint8Array,Set,Map,Math,Date,JSON};
sandbox.window=sandbox;sandbox.addEventListener=(k,fn)=>(events[k]??=[]).push(fn);sandbox.CPBLMusic={stop(){},play(){}};
const THREE={...require('../vendor/three.min.js')};
THREE.WebGLRenderer=class{constructor(){this.domElement=new Element('canvas');this.shadowMap={};this.pixelRatio=1}setPixelRatio(n){this.pixelRatio=n}setSize(){}setViewport(){}setScissor(){}setScissorTest(){}render(scene,camera){scene.updateMatrixWorld();camera.updateMatrixWorld()}getContext(){return {getExtension:()=>({restoreContext(){}})}}};sandbox.THREE=THREE;
sandbox.assertRig=(condition,message)=>assert(condition,message);
const context=vm.createContext(sandbox),run=code=>vm.runInContext(code,context);
for(const file of ['game.js','motion-calibration.js','stadium-data.js','baseball-engine.js','baseball-rules.js','broadcast.js','rosters-data.js','pitch-profiles.js','player-traits.js','roster.js','season.js','stadium-setup.js','xinzhuang-model.js','broadcast-camera.js','stadium3d.js']){let source=fs.readFileSync(path.join(root,file),'utf8');if(file==='stadium3d.js')source=source.replace(/\}\)\(\);\s*$/,"window.RIG_TEST={pitcher,batter,catcher,resetPose,armTo,runningPose,battingPose,actorBatGrip,catcherPose,catcherReturnPose,applyDelivery,actorHand,groundActor,fielders,baseUmpires,umpire,fieldReadyPose,divePose,throwPose,render3d,fieldActors,chalkMarks,homeCircleChalk,ground,rebuildFieldGeometry,officialStart,officialPoint,clearBroadcastEye,parkGroup,glovePocket,ballGrip,closeGlove};})();");run(source);}
run('musicEnabled=false;effectsEnabled=false;');

function tick(ms=100){time+=ms;const current=frames;frames=[];for(const fn of current)fn(time)}

sandbox.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(root,'assets/players/human.json'),'utf8')),arrayBuffer:async()=>{const b=fs.readFileSync(path.join(root,'assets/players/human.bin'));return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}});
THREE.TextureLoader=class{load(url,onLoad){const texture=new THREE.Texture();if(onLoad)Promise.resolve().then(()=>onLoad(texture));return texture;}};
run(fs.readFileSync(path.join(root,'human-assets.js'),'utf8'));run('CPBLHuman.load(THREE)');
(async()=>{await new Promise(setImmediate);await new Promise(setImmediate);assert(run('CPBLHuman.ready'),'Human mesh should load');
 for(const side of [0,1]){run(`state.mode='single';startGame(0);state.playerSide=${side};state.half='top';`);tick(100);assert.equal(run('stage.dataset.characterModel'),'makehuman-skinned');
  run('state.strikes=2;beginPitch();tv.flight.x=0;tv.flight.y=0;tv.flight.cpuSwing=false;tv.swung=false;');tick(100);run('finishPitch()');tick(1600);tick(800);assert.equal(run('tv.phase'),'return');
  assert.equal(run('stage.dataset.firstPersonReturn'),String(side===0));
  if(side===0){assert.equal(run('stage.dataset.ballPhase'),'catcher-transfer');}
  tick(1000);assert.equal(run('stage.dataset.ballPhase'),'return-throw');tick(1600);assert.equal(run('tv.phase'),'return');tick(1100);assert.equal(run('tv.phase'),'ready');
 }
 run(`const rig=RIG_TEST;assertRig(rig.chalkMarks.every(m=>m.geometry.type==='BufferGeometry'&&!m.castShadow),'Chalk must be flat mesh without pipe shadow');assertRig(rig.homeCircleChalk.geometry.type==='RingGeometry','Home circle must be flat');for(const a of [rig.pitcher,rig.batter,rig.catcher]){
  assertRig(a.human,'Missing skinned actor');assertRig(a.capMeshes.every(m=>m.visible),'Cap was hidden with helper head meshes');
  for(const side of ['left','right']){
   const elbow=a.parts[side+'Elbow'],palm=a.human.hands[side];assertRig(Math.abs(palm.x)<1e-8&&Math.abs(palm.z)<1e-8,'Palm must share anatomical forearm axis');
   for(const target of [[0,.1,.1],[.6,.4,.2],[-.4,.7,.3],[.1,-.2,.3]]){
    rig.resetPose(a);rig.armTo(a,side,new THREE.Vector3(...target));assertRig(Math.abs(elbow.rotation.y)<1e-8&&Math.abs(elbow.rotation.z)<1e-8,'Elbow must remain a hinge');assertRig(elbow.rotation.x>=.20&&elbow.rotation.x<=2.357,'Anatomical flexion limits');
   }
  }
 }
 for(const actor of [...rig.fielders,...rig.baseUmpires,rig.umpire]){rig.resetPose(actor);actor.group.updateMatrixWorld(true);for(const side of ['left','right']){const shoulder=actor.parts[side+'Arm'].position,palm=actor.body.worldToLocal(rig.actorHand(actor,side));assertRig(palm.y<shoulder.y-.50,'Relaxed hand must hang beside thigh');assertRig(actor.parts[side+'Elbow'].rotation.x<.65,'Resting elbow folds inward');assertRig((side==='left'?1:-1)*palm.x>.20,'Relaxed hand crosses torso');}}
 for(const hand of ['R','L']){let previous=null;tv.phase='windup';tv.deliveryAt=1000;for(let age=0;age<=3400;age+=20){rig.resetPose(rig.pitcher);rig.pitcher.group.rotation.y=Math.PI;rig.applyDelivery(rig.pitcher,{hand,style:'over'},1000+age);const side=hand==='L'?'left':'right',elbow=rig.pitcher.parts[side+'Elbow'];assertRig(Math.abs(elbow.rotation.y)<1e-8&&Math.abs(elbow.rotation.z)<1e-8,'Delivery elbow twists');const point=rig.actorHand(rig.pitcher,side);assertRig(Number.isFinite(point.y),'Invalid pitch hand');if(age===0){const direction=new THREE.Vector3(0,0,1).transformDirection(rig.pitcher.body.matrixWorld);assertRig(Math.abs(direction.z)<.01,'Pitcher must begin sideways');}if(age===1100){const release=CPBLPhysics.releasePoint({hand,style:'over'});assertRig(point.distanceTo(new THREE.Vector3(release.x,release.y,release.z))<.08,'Release detached '+hand+' '+point.distanceTo(new THREE.Vector3(release.x,release.y,release.z)));}if(age>=1200)assertRig(rig.pitcher.body.rotation.x<.45,'Pitcher torso falls excessively');if(previous)assertRig(point.distanceTo(previous)<.30,'Pitch hand jumps '+hand+' '+age+' '+point.distanceTo(previous));previous=point;}}
 for(const left of [false,true])for(const aimY of [-1,0,1]){tv.aim={x:0,y:aimY};tv.swingAim={...tv.aim};tv.swung=true;tv.swingStart=1000;for(let age=0;age<=1050;age+=10){rig.resetPose(rig.batter);rig.batter.group.position.set(left?-1.1:1.1,0,.15);rig.batter.group.rotation.y=left?Math.PI/2:-Math.PI/2;rig.battingPose(rig.batter,left,1000+age);assertRig(Math.abs(rig.batter.pelvis.position.y-.98)<1e-8,'Batting pelvis must not bob with low aim');if(age===0)assertRig(Math.abs(rig.batter.pelvis.position.x-(left?.075:-.075))<1e-8,'Load must stay over rear foot');if(age===80)assertRig(Math.abs(rig.batter.pelvis.position.x)>.125,'Visible rearward load is missing');if(age===220){const back=left?'left':'right';assertRig(rig.batter.parts[back+'Knee'].quaternion.angleTo(new THREE.Quaternion())>.45,'Rear knee must flex through hip rotation');}if(age===140){const front=left?'right':'left';assertRig(rig.batter.parts[front+'Knee'].quaternion.angleTo(new THREE.Quaternion())<.45,'Front leg must brace at contact '+rig.batter.parts[front+'Knee'].quaternion.angleTo(new THREE.Quaternion()));}for(const side of ['left','right']){assertRig(Math.abs(rig.batter.parts[side+'Elbow'].rotation.z)<1e-8,'Batting elbow twists');const grip=rig.batter.bat.position.clone(),direction=new THREE.Vector3(0,-1,0).applyQuaternion(rig.batter.bat.quaternion);grip.addScaledVector(direction,.14);grip.addScaledVector(direction,left?(side==='left'?.055:-.045):(side==='left'?-.045:.055));const palm=rig.batter.body.worldToLocal(rig.actorBatGrip(rig.batter,side));if(age<=CPBLSwingTiming.release||side===(left?'right':'left'))assertRig(palm.distanceTo(grip)<.018,'Batting wrist cannot reach bat grip: '+age+' '+side+' '+palm.distanceTo(grip)+' aim '+aimY+' grip '+grip.toArray()+' shoulder '+rig.batter.parts[side+'Arm'].position.toArray());}}}
 for(const hand of ['R','L']){tv.phase='windup';tv.deliveryAt=1000;const rear=hand==='L'?'left':'right',lead=hand==='L'?'right':'left';let previous=null;for(let age=2100;age<=3100;age+=20){rig.resetPose(rig.pitcher);rig.pitcher.group.rotation.y=Math.PI;rig.applyDelivery(rig.pitcher,{hand,style:'over'},1000+age);rig.pitcher.group.updateMatrixWorld(true);const side=age<=2600?rear:lead,leg=rig.pitcher.human.legs[side],foot=rig.pitcher.parts[side+'Knee'].localToWorld(new THREE.Vector3(0,-leg.lower,0));if(previous&&previous.side===side)assertRig(Math.abs(foot.z-previous.z)<.012,'Recovery support foot slides '+hand+' '+age+' '+foot.toArray()+' prev '+previous.z+' root '+rig.pitcher.group.position.toArray()+' pelvis '+rig.pitcher.pelvis.position.toArray());previous={side,z:foot.z};}assertRig(Math.abs(rig.pitcher.group.position.z-18.32)<.001,'Pitcher recovery position');}
 for(let frame=0;frame<60;frame++){rig.resetPose(rig.batter);rig.runningPose(rig.batter,frame*.12,6);for(const side of ['left','right'])assertRig(Math.abs(rig.batter.parts[side+'Elbow'].rotation.z)<1e-8,'Running elbow twists');}`);
  run(`const z=window.CPBL_BATTER_ZONE;assertRig(z.top>z.bottom&&z.bottom<.65&&z.top<1.4,'Zone must extend below waist to knees');
 const zoneFrame={type:'四縫線',hand:'R',x:0,y:0,zone:z};assertRig(CPBLPhysics.isStrike(zoneFrame),'Centre must be a strike');
 for(const height of [165,183,198]){const zone=CPBLPhysics.batterZone({height});const f={...zoneFrame,zone};
  f.y=1;assertRig(Math.abs(CPBLPhysics.pitchPoint(f,1).y-zone.bottom)<1e-8,'Aim bottom must equal zone bottom');assertRig(CPBLPhysics.isStrike(f),'Knee edge must be strike');
  f.y=-1;assertRig(Math.abs(CPBLPhysics.pitchPoint(f,1).y-zone.top)<1e-8,'Aim top must equal zone top');
  f.y=-1-.08/zone.halfHeight;assertRig(!CPBLPhysics.isStrike(f),'Above upper edge must be ball');
  f.y=1+.08/zone.halfHeight;assertRig(!CPBLPhysics.isStrike(f),'Below knee edge must be ball');
  f.y=0;f.x=1+.036/zone.halfWidth;assertRig(CPBLPhysics.isStrike(f),'Ball radius touching plate must count');f.x=1+.04/zone.halfWidth;assertRig(!CPBLPhysics.isStrike(f),'Entire ball beyond plate must be ball');
 }
 assertRig(CPBLPhysics.batterZone({height:165}).top<CPBLPhysics.batterZone({height:198}).top,'Height must affect zone');`);
 run(`state.mode='single';startGame(3);state.outs=0;state.bases=['跑者',null,null];let auditSeed=313;const auditRandom=()=>{auditSeed=(Math.imul(auditSeed,1664525)+1013904223)>>>0;return auditSeed/2**32};let auditCount=0;
 for(let n=0;n<500&&auditCount<12;n++){const h=CPBLRules.plan(CPBLPhysics.createPlay(.9,false,{x:0,y:0},auditRandom,state.bases),{bases:state.bases,outs:0,batter:batterName(),inning:1,runDifference:0});const receiver=h.throwLegs.find(l=>h.fieldingAttempts[l.receiver]);if(!receiver)continue;const index=receiver.receiver,attempt=h.fieldingAttempts[index],age=attempt.at-100,expected=CPBLPhysics.supportPoint(h,index,age);assertRig(['intercept-attempt','dive-attempt'].includes(expected.role),'Receiver abandons live ball');tv.start=0;tv.hit={...h,runners:state.bases.slice(),batter:batterName(),batSide:battingTeam(),start:0,applied:false};tv.phase='hit';tv.paused=true;tv.pauseAt=age;RIG_TEST.render3d(100000+n*100);const actor=RIG_TEST.fieldActors[index];assertRig(Math.hypot(actor.group.position.x-expected.x,actor.group.position.z-expected.z)<.001,'Renderer overwrote interception with coverage');auditCount++;}
 assertRig(auditCount>=6,'Not enough intercepting receivers audited');`);
 run(`const diveActor=RIG_TEST.fielders[2];for(const direction of [-1,1]){const d=CPBLPhysics.makeDive({x:0,z:25},{x:direction*4,y:.20,z:26},1250);let prev=null;for(let t=d.begin;t<=d.end;t+=25){RIG_TEST.resetPose(diveActor);RIG_TEST.divePose(diveActor,d,t);diveActor.group.updateMatrixWorld(true);const palm=RIG_TEST.actorHand(diveActor,'left');assertRig(Number.isFinite(palm.y),'Invalid dive hand');if(prev)assertRig(palm.distanceTo(prev)<.40,'Dive hand jumps '+t);prev=palm;if(t>=d.slideEnd+300){const feet=['left','right'].map(s=>diveActor.parts[s+'Knee'].localToWorld(new THREE.Vector3(0,-diveActor.human.legs[s].lower,.065)).y);assertRig(Math.min(...feet)<.12,'Recovery feet hover '+t);}if(t===d.at+175)assertRig(diveActor.body.rotation.x>1.3,'Dive must finish prone');}}`);
 run(`for(const hand of ['right','left'])for(const heading of [0,Math.PI/2,Math.PI,-Math.PI/2]){const a=RIG_TEST.fielders[2];a.throwHand=hand;const d=CPBLPhysics.makeDive({x:0,z:25},{x:Math.sin(heading)*4,y:.2,z:25+Math.cos(heading)*4},1250);let support=null,foot=null;for(let r=180;r<=1200;r+=20){RIG_TEST.resetPose(a);RIG_TEST.divePose(a,d,d.slideEnd+r);const palm=RIG_TEST.actorHand(a,hand);if(r<=460){assertRig(palm.y>.035&&palm.y<.085,'Support palm must touch turf '+hand+' '+r);if(support)assertRig(palm.distanceTo(support)<.005,'Support palm slides '+r);support=palm.clone();}if(r>=460){const side=hand==='right'?'left':'right',ankle=a.parts[side+'Knee'].localToWorld(new THREE.Vector3(0,-a.human.legs[side].lower,0));assertRig(ankle.y<.09&&ankle.y>.035,'Lead sole contact lost '+r);if(foot)assertRig(ankle.distanceTo(foot)<.005,'Planted lead foot slides '+r);foot=ankle.clone();}}}`);
 run(`for(const throwing of ['left','right'])for(const ground of [false,true]){const a=RIG_TEST.fielders[2];a.throwHand=throwing;const leg={from:{x:0,y:1.35,z:25},to:{x:-19.4,y:1.15,z:19.4},start:1000,end:1700,receiveTarget:{x:0,y:ground?.2:1.15,z:25}};for(let u=.40;u<=.50;u+=.02){RIG_TEST.resetPose(a);a.group.position.set(0,0,25);const pose=RIG_TEST.throwPose(a,leg,u*1000,0,ground);assertRig(pose.contactError<.015,'Throwing palm must reach mitt '+throwing+' '+ground+' '+u+' error '+pose.contactError);assertRig(pose.owner===(u<.42?'glove':'hand'),'Possession switches before contact');}}`);
 run(`const transferCatcher=RIG_TEST.catcher;tv.flight={hand:'R',type:'四縫線',x:0,y:0,zone:CPBLPhysics.batterZone({height:180})};for(let t=420;t<=520;t+=20){RIG_TEST.resetPose(transferCatcher);RIG_TEST.catcherReturnPose(transferCatcher,{x:0},t);const mitt=RIG_TEST.glovePocket(transferCatcher,new THREE.Vector3()),hand=RIG_TEST.ballGrip(transferCatcher,'right');assertRig(hand.distanceTo(mitt)<.015,'Catcher must take ball from mitt '+t+' '+hand.distanceTo(mitt));}`);
 run(`for(const t of [320,370,420,520,575,630]){const a=RIG_TEST.catcher;RIG_TEST.resetPose(a);RIG_TEST.catcherReturnPose(a,{x:0},t);a.group.updateMatrixWorld(true);const grip=a.glove.worldToLocal(RIG_TEST.ballGrip(a,'right'));assertRig(Math.abs(grip.x-.018)<.015&&Math.abs(grip.y-.035)<.015,'Transfer must stay inside open palm corridor '+t+' '+JSON.stringify(grip));assertRig(grip.z>=.075,'Transfer crosses leather palm '+t);if(t===320||t===630)assertRig(grip.z>.19,'Hand must approach and exit through mouth '+t+' '+JSON.stringify(grip));}
 for(const side of ['left','right'])for(const u of [.30,.35,.4,.5,.575,.65]){const a=RIG_TEST.fielders[2];a.throwHand=side;RIG_TEST.resetPose(a);a.group.position.set(0,0,25);RIG_TEST.throwPose(a,{from:{x:0,y:1.35,z:25},to:{x:-19.4,y:1.15,z:19.4},start:1000,end:1700,receiveTarget:{x:0,y:1.15,z:25}},u*1000,0,false);a.group.updateMatrixWorld(true);const grip=a.glove.worldToLocal(RIG_TEST.ballGrip(a,side));assertRig(Math.abs(grip.x-.018)<.04&&Math.abs(grip.y-.035)<.04&&grip.z>.07,'Field transfer must use open palm '+side+' '+u+' '+JSON.stringify(grip));}`);
 run(`for(const t of [950,1200,1400]){const a=RIG_TEST.catcher;RIG_TEST.resetPose(a);RIG_TEST.catcherReturnPose(a,{x:0},t);const palm=RIG_TEST.actorHand(a,'right'),shoulder=a.parts.rightArm.getWorldPosition(new THREE.Vector3());if(t===950)assertRig(palm.z>shoulder.z+.35,'Catcher release must extend forward');else assertRig(palm.x>shoulder.x+.25,'Catcher follow-through must cross toward opposite side');}const field=RIG_TEST.ground;assertRig(field.geometry.groups.length>=2,'Field materials must share a single geometry');assertRig(field.position.y===0&&field.rotation.x===0,'Shared field must have no raised layer');for(let i=0;i<field.geometry.attributes.position.count;i++)assertRig(field.geometry.attributes.position.getY(i)===0,'Home soil must be flat');field.updateMatrixWorld(true);for(const z of [-2,2]){const ray=new THREE.Raycaster(new THREE.Vector3(.4,10,z),new THREE.Vector3(0,-1,0)),hits=ray.intersectObject(field);assertRig(hits.length===1&&hits[0].face.materialIndex===1,'Home must have one clay surface, without overlapping turf '+z+' '+hits.length);}`);
 run(`for(const park of CPBLStadiums.parks){RIG_TEST.rebuildFieldGeometry(park);const field=RIG_TEST.ground;field.updateMatrixWorld(true);for(const [x,z] of [[.4,-2],[.4,2],[6,-2],[.5,20],[22,20]]){const ray=new THREE.Raycaster(new THREE.Vector3(x,10,z),new THREE.Vector3(0,-1,0)),hits=ray.intersectObject(field);assertRig(hits.length===1,'Field must have exactly one surface '+park.id+' '+x+','+z+' '+hits.length);if(Math.hypot(x,z)<4.7)assertRig(hits[0].face.materialIndex===1,'Home must be clay '+park.id);}}for(let t=300;t<=1500;t+=20){const a=RIG_TEST.catcher;RIG_TEST.resetPose(a);RIG_TEST.catcherReturnPose(a,{x:0},t);const mitt=a.body.worldToLocal(a.glove.getWorldPosition(new THREE.Vector3()));assertRig(mitt.z-.047>.28,'Leather back must clear chest '+t+' '+mitt.z);}`);
 run(`for(let f=0;f<80;f++){const a=RIG_TEST.batter;RIG_TEST.resetPose(a);RIG_TEST.runningPose(a,f*.06,7);a.group.updateMatrixWorld(true);for(const side of ['left','right']){const elbow=a.body.worldToLocal(a.parts[side+'Elbow'].getWorldPosition(new THREE.Vector3()));assertRig(Math.abs(elbow.x)<.38,'Running elbow flares sideways '+side+' '+elbow.x);assertRig(elbow.y<.25,'Running upper arm too high '+elbow.y);}}const a=RIG_TEST.fielders[2],d=CPBLPhysics.makeDive({x:0,z:25},{x:4,y:.2,z:26},1250);let previous=null;for(let r=460;r<=1200;r+=20){RIG_TEST.resetPose(a);RIG_TEST.divePose(a,d,d.slideEnd+r);const palm=RIG_TEST.actorHand(a,a.throwHand==='left'?'right':'left');if(previous)assertRig(palm.distanceTo(previous)<.08,'Recovering glove hand jumps '+r);previous=palm.clone();if(r===1200)assertRig(palm.y>1.05,'Glove hand must rise with chest');}`);
 run(`for(const hand of ['right','left']){const a=RIG_TEST.fielders[2],leg={from:{x:0,y:1.35,z:25},to:{x:-19.4,y:1.15,z:19.4},start:1000,end:1700};a.throwHand=hand;RIG_TEST.resetPose(a);a.group.position.set(0,0,25);RIG_TEST.throwPose(a,leg,1650,0,false);a.group.updateMatrixWorld(true);const local=a.body.worldToLocal(RIG_TEST.actorHand(a,hand));assertRig((hand==='right'?1:-1)*local.x>.18,'Follow-through must finish on glove side '+hand+' '+local.x);}`);

run(`for(const left of [false,true]){const a=RIG_TEST.batter;RIG_TEST.resetPose(a);RIG_TEST.battingPose(a,left,0);assertRig(a.headwearMaterial!==a.uniform&&a.headwearMaterial.clearcoat>.5,'Batter must have distinct rigid helmet');assertRig(Math.sign(a.earFlap.position.x)===(left?-1:1),'Ear flap must face pitcher for each stance');assertRig(a.capMeshes.every(m=>m.visible),'Helmet components must remain visible');}const c=RIG_TEST.catcher;assertRig(c.headwearMaterial!==c.uniform&&c.capMeshes[1].scale.z<0,'Catcher needs rigid skull cap with rear bill');`);

run(`{const a=RIG_TEST.batter,h=a.human;assertRig(h.skeleton.bones.length===12,'Independent palm bones missing');for(const g of [h.meshes[0].geometry,...Object.values(h.handMeshes).map(m=>m.geometry)]){assertRig(g.morphAttributes.position.length===2,'Both hand morphs must cross wrist seams');const weights=g.attributes.skinWeight;for(let i=0;i<weights.count;i++){let sum=0;for(let k=0;k<4;k++)sum+=weights.getComponent(i,k);assertRig(Math.abs(sum-1)<.00001,'Skin weights must sum to one');}}for(const side of ['left','right']){assertRig(h.handMeshes[side].visible,'Do not hide glove hands');assertRig(h.wrists[side].quaternion.angleTo(new THREE.Quaternion())<1.6,'Excessive wrist rotation');}assertRig(RIG_TEST.catcher.glove.children.some(m=>m.userData?.wristOpening),'Glove needs physical wrist opening');}`);

run(`{for(const hand of ['R','L']){const a=RIG_TEST.pitcher;let previous=null;tv.returnBall=null;tv.phase='windup';tv.deliveryAt=1000;for(let age=1100;age<=2100;age+=20){RIG_TEST.resetPose(a);a.group.position.set(0,.28,18.44);a.group.rotation.y=Math.PI;RIG_TEST.applyDelivery(a,{hand,style:'over'},1000+age);RIG_TEST.groundActor(a);const hip=a.pelvis.getWorldPosition(new THREE.Vector3());assertRig(hip.y>.80,'Pitcher sinks into seated pose '+hand+' '+age+' '+hip.y);if(previous)assertRig(a.group.position.z<=previous.z+.002,'Momentum reverses after release '+age);previous=a.group.position.clone();}}assertRig(CPBLSwingTiming.extension===440&&CPBLSwingTiming.turn===300,'Follow-through must rise later');}`);
run(`{for(const style of ['one-hand','two-hand'])for(const left of [false,true]){window.CPBL_PREVIEW_SWING_STYLE=style;const a=RIG_TEST.batter;tv.swung=true;tv.swingStart=1000;for(const age of [300,440,600,780,1000,1300]){RIG_TEST.resetPose(a);a.group.position.set(left?-1.1:1.1,0,.15);a.group.rotation.y=left?Math.PI/2:-Math.PI/2;RIG_TEST.battingPose(a,left,1000+age);if(age<=780)assertRig(a.swingRelease===0,'Top hand releases before raised two-hand follow-through');if(age>=440)assertRig(Math.abs(a.pelvis.rotation.y)>1,'Hips must rotate before full extension');if(age>=1000)assertRig(a.swingRelease===(style==='one-hand'?1:0),'Finish style must preserve correct grip');if(style==='two-hand'){const axis=new THREE.Vector3(0,-1,0).applyQuaternion(a.bat.quaternion);for(const side of ['left','right']){const target=a.bat.position.clone().addScaledVector(axis,.14+(side==='left'?(left?.055:-.045):(left?-.045:.055)));assertRig(RIG_TEST.actorBatGrip(a,side).distanceTo(a.body.localToWorld(target))<.018,'Two-hand finish loses bat '+age);}}}}delete window.CPBL_PREVIEW_SWING_STYLE;}`);
 run(`{window.CPBL_PREVIEW_SWING_STYLE='one-hand';const a=RIG_TEST.batter;tv.swung=true;tv.swingStart=1000;tv.pendingPitch=null;let maxBat=0,maxHand=0,maxAngle=0;for(const left of [false,true]){let prev=null;for(let age=740;age<=1200;age+=5){RIG_TEST.resetPose(a);a.group.position.set(left?-1.1:1.1,0,.15);a.group.rotation.y=left?Math.PI/2:-Math.PI/2;RIG_TEST.battingPose(a,left,1000+age);a.group.updateMatrixWorld(true);const pose={bat:a.bat.getWorldPosition(new THREE.Vector3()),hand:RIG_TEST.actorHand(a,left?'left':'right'),q:a.bat.getWorldQuaternion(new THREE.Quaternion())};if(prev){maxBat=Math.max(maxBat,pose.bat.distanceTo(prev.bat));maxHand=Math.max(maxHand,pose.hand.distanceTo(prev.hand));maxAngle=Math.max(maxAngle,pose.q.angleTo(prev.q));}prev=pose;}}window.releaseMetrics={maxBatStep5ms:maxBat,maxHandStep5ms:maxHand,maxBatAngle5ms:maxAngle};assertRig(maxBat<.025,'Bat jumps when grip releases');assertRig(maxHand<.04,'Released hand jumps');delete window.CPBL_PREVIEW_SWING_STYLE;}`);
 run(`{const h={event:'doubleplay',land:{x:-10,y:.1,z:32},fielder:2,kind:'ground',fieldAtMs:1200,throwLegs:[{base:1,receiver:1,start:1700,end:2200,to:{x:0,z:38.8}},{base:0,receiver:0,start:2700,end:3200,to:{x:-19.4,z:19.4}}],basePlays:[{base:1,time:2250,contact:{x:0,z:38.8}},{base:0,time:3250,contact:{x:-19.4,z:19.4}}],runners:['runner',null,null]};for(const replay of [false,true]){h.replay=replay;let camera=null;for(let t=0;t<=4200;t+=50){const p=CPBLCamera.plan(h,t,{x:0,y:1,z:30},[],'throw','xinzhuang');assertRig(p.shot==='double-play','Double play must stay on one shot');if(camera)assertRig(p.cameraId===camera,'Double play camera cuts');camera=p.cameraId;}}for(let i=0;i<4;i++){const start=RIG_TEST.officialStart(i,h.runners,false);if(i===0)assertRig(-start.x>start.z,'First-base umpire must start in foul territory');if(i===2)assertRig(start.x>start.z,'Third-base umpire must start in foul territory');let prev=null;for(let t=0;t<=4500;t+=20){const q=RIG_TEST.officialPoint(h,i,t,false);if(prev)assertRig(Math.hypot(q.x-prev.x,q.z-prev.z)<.10,'Umpire teleports or exceeds running speed');prev=q;if(h.basePlays.find(p=>p.base===i)?.time<=t)assertRig(!q.moving,'Umpire must be set before call');}}const eye=RIG_TEST.clearBroadcastEye({x:20,y:10,z:-5},[{x:0,y:1,z:38.8},{x:-19.4,y:1,z:19.4},{x:-10,y:.1,z:32}]);const blocks=[];RIG_TEST.parkGroup.traverse(o=>{if(o.isMesh&&o.userData.staticOccluder)blocks.push(o);});for(const point of [{x:0,y:1,z:38.8},{x:-19.4,y:1,z:19.4},{x:-10,y:.1,z:32}]){const origin=new THREE.Vector3(eye.x,eye.y,eye.z),direction=new THREE.Vector3(point.x,point.y,point.z).sub(origin),length=direction.length();assertRig(new THREE.Raycaster(origin,direction.normalize(),.1,length-.5).intersectObjects(blocks).length===0,'Replay view blocked by stadium');}}`);
 run(`for(const a of [RIG_TEST.catcher,RIG_TEST.fielders[2]]){const wingWidth=()=>{let lo=Infinity,hi=-Infinity;for(const o of a.glove.userData.foldMeshes){const g=o.geometry,b=g.attributes.position,m=g.morphAttributes.position;for(let i=0;i<b.count;i++){const p=new THREE.Vector3().fromBufferAttribute(b,i);for(let j=0;j<2;j++)p.add(new THREE.Vector3().fromBufferAttribute(m[j],i).sub(new THREE.Vector3().fromBufferAttribute(b,i)).multiplyScalar(o.morphTargetInfluences[j]));p.applyMatrix4(o.matrix);if(p.y>.12&&p.z>.08){lo=Math.min(lo,p.x);hi=Math.max(hi,p.x);}}}return hi-lo;};RIG_TEST.closeGlove(a,0);const open=wingWidth(),pocket=RIG_TEST.glovePocket(a,new THREE.Vector3());RIG_TEST.closeGlove(a,.95);assertRig(wingWidth()<open*.72,'Glove wings must actually close '+a.kind+' '+wingWidth()+'/'+open);assertRig(pocket.distanceTo(RIG_TEST.glovePocket(a,new THREE.Vector3()))<.00001,'Glove closure must not teleport ball');RIG_TEST.closeGlove(a,0);}
 for(const t of [0,140,280,420]){const a=RIG_TEST.catcher;RIG_TEST.resetPose(a);RIG_TEST.catcherReturnPose(a,{x:0},t);assertRig(t<200?a.gloveClosure>.9:a.gloveClosure<.01,'Mitt must close before opening for transfer '+t);}
 for(const throwing of ['left','right']){const a=RIG_TEST.fielders[2];a.throwHand=throwing;for(const u of [0,.3]){RIG_TEST.resetPose(a);a.group.position.set(0,0,25);RIG_TEST.throwPose(a,{from:{x:0,y:1.35,z:25},to:{x:-19.4,y:1.15,z:19.4},start:1000,end:1700,receiveTarget:{x:0,y:1.15,z:25}},u*1000,0,false);assertRig(u===0?a.gloveClosure>.9:a.gloveClosure<.01,'Field glove must reopen before hand enters');}}`);
 console.log(run('JSON.stringify(window.releaseMetrics)'));
 assert.equal(errors.length,0,errors.join('\n'));console.log('Skinned human mesh, both player views and first-person return passed; anatomical arm binding, hinge limits and running poses passed; zero scene errors.');
})().catch(error=>{console.error(error);process.exitCode=1});
