const assert=require('node:assert/strict');require('../baseball-engine.js');require('../baseball-rules.js');const P=CPBLPhysics,R=CPBLRules;
function fixture(fielder,pickup,attempt){const h={kind:'ground',event:'groundout',type:'OUT',fielder,pickup,land:pickup,fieldTarget:pickup,flightMs:650,fieldAtMs:950,pickupMs:1800,runnerMs:4500,relay:null,fieldingAttempts:[]};if(attempt)h.fieldingAttempts[0]=attempt;R.plan(h,{bases:[null,null,null],outs:0,batter:'打者',inning:1,runDifference:0});return h;}
const own=fixture(0,{x:-20,z:20});assert(own.carryFirst&&own.throwLegs[0].self,'Nearby first baseman carries ball to bag');
const far=fixture(0,{x:-1,z:35});assert(far.throwLegs.some(l=>l.base===0&&l.receiver===7),'Pitcher receives when first baseman cannot return promptly');
const ordinary=fixture(2,{x:9,z:33});assert(ordinary.throwLegs.some(l=>l.base===0&&l.receiver===0),'First baseman receives ordinary infield throw');
const delayed=fixture(2,{x:9,z:33},{end:4000,target:{x:-7,z:32}});assert(delayed.throwLegs.some(l=>l.base===0&&l.receiver===7),'Pitcher receives when first baseman is delayed');
for(const h of [far,ordinary,delayed]){const l=h.throwLegs.find(l=>l.base===0);assert(l.end>=P.coverArrival(h,l.receiver,P.bases[0]),'Receiver must reach bag before throw');}
for(const base of [1,2,3]){const play={kind:'ground',event:'hit',fielder:5,fieldTarget:{x:0,z:90},pickup:{x:0,z:90},throwBase:base,throwLegs:[{receiver:base===3?8:base,base,from:{x:0,z:55},to:P.bases[base]}]};const at=P.supportPoint(play,7,15000);assert.equal(at.role,base===1?'backup-second':base===2?'backup-third':'backup-home');const b=P.bases[base],v={x:b.x,z:b.z-55};assert((at.x-b.x)*v.x+(at.z-b.z)*v.z>0,'Pitcher must back up beyond target, not approach the ball');assert(Math.abs(Math.hypot(at.x-b.x,at.z-b.z)-7)<.001);}
let seed=823,checked=0,attempts=0;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32};
for(let n=0;n<2500;n++){const h=P.createPlay(.8,false,{x:0},rand);if(h.kind!=='ground'||h.event==='homer')continue;checked++;for(const a of h.fieldingAttempts)if(a)attempts++;
 // No legal glove interception may exist significantly earlier than the selected pickup.
 for(let ms=25;ms<h.fieldAtMs-25&&ms<(h.trajectory.length-1)*25;ms+=25){const p=h.trajectory[ms/25];if(ms<h.flightMs||p.y>1.25)continue;const x=Math.sin(h.angle)*p.distance,z=Math.cos(h.angle)*p.distance;h.defenseStarts.forEach((f,i)=>{const d=Math.hypot(x-f.x,z-f.z),reaction=i===7?.32:.22;if(i===7&&(d>12||z>30)||ms/1000<reaction)return;assert(d>P.runDistance(ms/1000-reaction,i===7?6.4:7.7)+.65-1e-8,'A defender could intercept this ground ball earlier');});}
 const at=P.fielderPoint(h,h.fieldAtMs);assert(Math.hypot(at.x-h.pickup.x,at.z-h.pickup.z)<=(h.dive?.standOff||.65)+1e-7);assert(h.fielder!==7||Math.hypot(h.pickup.x,h.pickup.z-17.65)<=12.001,'Pitcher must not retrieve deep outfield balls');}
assert(checked>500&&attempts>10);console.log({grounders:checked,interceptionAttempts:attempts,pitcherCoverAndBackups:'passed'});

let overlap=0;seed=313;for(let n=0;n<1000;n++){const h=R.plan(P.createPlay(.9,false,{x:0,y:0},rand,['跑者',null,null]),{bases:['跑者',null,null],outs:0,batter:'打者',inning:1,runDifference:0});for(const leg of h.throwLegs){const a=h.fieldingAttempts[leg.receiver];if(!a)continue;const before=P.supportPoint(h,leg.receiver,a.at-100);assert(['intercept-attempt','dive-attempt'].includes(before.role));const after=P.supportPoint(h,leg.receiver,a.end+1);assert(Math.hypot(after.x-a.target.x,after.z-a.target.z)<.001,'Coverage transition teleports');assert(leg.end>=P.coverArrival(h,leg.receiver,leg.receiverPosition),'Throw arrives before receiver finishes pursuit and reaches bag');overlap++;}}assert(overlap>20);console.log({receiversWhoPursueBeforeCoverage:overlap});

let dives=0,ground=0;seed=153;for(let n=0;n<3000;n++){const h=P.createPlay(.9,false,{x:0},rand);if(h.kind!=='ground')continue;ground++;if(!h.dive)continue;dives++;const d=h.dive;assert(h.pickupMs>d.end,'Transfer must wait for recovery');let last=null;for(let t=d.begin-25;t<=d.end+25;t+=25){const p=P.fielderPoint(h,t);if(last)assert(Math.hypot(p.x-last.x,p.z-last.z)<.6,'Dive path teleports');last=p;}assert.equal(P.divePoint(d,d.slideEnd+50).phase,'brace');assert.equal(P.divePoint(d,d.end).phase,'ready');}assert(dives>0&&dives/ground<.10,'Dives must remain uncommon');console.log({dives,ground,diveFraction:dives/ground});

for(const h of [own]){const c=h.carryFirst,early=P.fielderPoint(h,c.start+100);assert(Math.hypot(early.x-c.from.x,early.z-c.from.z)<1e-8,'Turn before run');const p=P.fielderPoint(h,c.start+800),heading=Math.atan2(c.to.x-c.from.x,c.to.z-c.from.z);assert(Math.abs(Math.sin(p.heading-heading))<1e-8,'Run must face first base');const end=P.fielderPoint(h,c.end);assert(Math.hypot(end.x-c.to.x,end.z-c.to.z)<1e-7,'Carry must reach bag');}
