/* Editable reference shell, generated from the same builder as the game.
   glTF 2.0 linked meshes keep geometry shared in standard editors. No video
   pixels or third-party photographs are included in the model textures. */
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),T=require('../vendor/three.min.js');
const root=path.resolve(__dirname,'..'),parent=new T.Group(),materials=new Map();
const scope={window:{CPBL_LIGHTING:'day'}};vm.runInNewContext(fs.readFileSync(path.join(root,'xinzhuang-model.js'),'utf8'),scope);
function mat(color,extra={}){return new T.MeshStandardMaterial({color,roughness:.8,...extra});}
function mesh(g,m,x=0,y=0,z=0,p=parent){const o=new T.Mesh(g,m);o.position.set(x,y,z);p.add(o);return o;}
function box(w,h,d,m,x,y,z,p){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,p);}
function segment(a,b,r,m,p=parent){const d=new T.Vector3().subVectors(b,a),o=mesh(new T.CylinderGeometry(r,r,d.length(),14),m,0,0,0,p);o.position.copy(a).add(b).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());return o;}
const shape=new T.Shape();shape.moveTo(-.16,-.18);shape.lineTo(.16,-.18);shape.quadraticCurveTo(.21,-.18,.21,-.13);shape.lineTo(.19,.13);shape.quadraticCurveTo(.19,.19,.12,.19);shape.lineTo(-.12,.19);shape.quadraticCurveTo(-.19,.19,-.19,.13);shape.lineTo(-.21,-.13);shape.quadraticCurveTo(-.21,-.18,-.16,-.18);
const chairBack=new T.ExtrudeGeometry(shape,{depth:.018,bevelEnabled:true,bevelThickness:.006,bevelSize:.008,bevelSegments:1,steps:1,curveSegments:3});for(let i=0;i<chairBack.attributes.position.count;i++){const a=chairBack.attributes.position;a.setZ(i,a.getZ(i)+.035*(1-Math.pow(a.getX(i)/.22,2)));}chairBack.computeVertexNormals();const chairPan=chairBack.clone();chairPan.rotateX(-Math.PI/2);
function chairRows(points,color,p){for(const [geometry,dy] of [[chairBack,.23],[chairPan,0]]){if(!points.length)return;const o=new T.InstancedMesh(geometry,mat('#ffffff',{roughness:.45,side:T.DoubleSide}),points.length),pose=new T.Object3D();points.forEach((v,i)=>{pose.position.set(v.x,v.y+dy,v.z);pose.rotation.y=v.a;pose.updateMatrix();o.setMatrixAt(i,pose.matrix);o.setColorAt(i,new T.Color(v.color||color));});p.add(o);}}
const wallDistance=a=>Math.abs(a)<=Math.PI/4?121.92+(99.06-121.92)*Math.pow(Math.abs(a)/(Math.PI/4),1.5):99.06;
const profile=scope.window.CPBLXinzhuang.build({T,parent,p:{seat:'#2875a5'},mesh,box,segment,mat,chairRows,labelTexture:()=>null,wallDistance});
// Field boundary for scale/reference. Same published foul/CF distances.
const ground=mesh(scope.window.CPBLXinzhuang.groundGeometry(T,profile.groundHoles),mat('#46713a'),0,-.03,70);ground.rotation.x=-Math.PI/2;
for(let i=0;i<48;i++){const a=-Math.PI/4+i*Math.PI/96,b=a+Math.PI/96,r=wallDistance(a),rr=wallDistance(b);const start=new T.Vector3(Math.sin(a)*r,1.7,Math.cos(a)*r),end=new T.Vector3(Math.sin(b)*rr,1.7,Math.cos(b)*rr),m=new T.Vector3().addVectors(start,end).multiplyScalar(.5),o=box(start.distanceTo(end)+.05,3.4,.45,mat('#273c55'),m.x,1.7,m.z);o.rotation.y=Math.atan2(-(end.z-start.z),end.x-start.x);}
// Same four visible floodlight fixtures as the live Xinzhuang scene.
for(const [x,z] of [[-55,15],[55,15],[-48,141],[48,141]]){mesh(new T.CylinderGeometry(.35,.35,38,14),mat('#788d89'),x,19,z);const rack=new T.Group();rack.position.set(x,37,z);rack.rotation.y=Math.atan2(-x,48-z);parent.add(rack);box(9,2.7,.35,mat('#788d89'),0,0,0,rack);for(let row=0;row<3;row++)for(let col=0;col<8;col++)box(.68,.48,.05,mat('#e3e7d6'),(col-3.5)*1.05,(row-1)*.83,.38,rack);}
parent.updateMatrixWorld(true);
const gltf={asset:{version:'2.0',generator:'CPBL Xinzhuang reference builder v31',extras:{reference:'data/xinzhuang-reconstruction.json',estimated:true,omitted:'Crowd sprites, text textures and dynamic players'}},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:[],accessors:[],bufferViews:[],buffers:[{byteLength:0}]},chunks=[];let bytes=0;const geometryCache=new Map(),materialCache=new Map();
function accessor(array,type,target){const bin=Buffer.from(array.buffer,array.byteOffset,array.byteLength),view=gltf.bufferViews.length;gltf.bufferViews.push({buffer:0,byteOffset:bytes,byteLength:bin.length,...(target?{target}:{})});chunks.push(bin);bytes+=bin.length;const pad=(4-bytes%4)%4;if(pad){chunks.push(Buffer.alloc(pad));bytes+=pad;}const components={SCALAR:1,VEC2:2,VEC3:3,VEC4:4}[type],count=array.length/components,min=Array(components).fill(Infinity),max=Array(components).fill(-Infinity);for(let i=0;i<array.length;i++){const k=i%components;min[k]=Math.min(min[k],array[i]);max[k]=Math.max(max[k],array[i]);}const index=gltf.accessors.length;gltf.accessors.push({bufferView:view,componentType:array instanceof Float32Array?5126:array instanceof Uint16Array?5123:5125,count,type,min,max});return index;}
function geometry(g){if(geometryCache.has(g))return geometryCache.get(g);const a={POSITION:accessor(new Float32Array(g.attributes.position.array),'VEC3',34962),NORMAL:accessor(new Float32Array(g.attributes.normal.array),'VEC3',34962)};const result={attributes:a,...(g.index?{indices:accessor(new Uint32Array(g.index.array),'SCALAR',34963)}:{})};geometryCache.set(g,result);return result;}
function material(m,color){const c=color||m.color,key=m.uuid+':'+c.getHexString();if(materialCache.has(key))return materialCache.get(key);const index=gltf.materials.length;gltf.materials.push({name:'material-'+index,pbrMetallicRoughness:{baseColorFactor:[c.r,c.g,c.b,1],metallicFactor:m.metalness,roughnessFactor:m.roughness},doubleSided:m.side===T.DoubleSide});materialCache.set(key,index);return index;}
const meshCache=new Map();
function add(o,instances,color){const materialIndex=material(o.material,color),key=o.geometry.uuid+':'+materialIndex;let meshIndex=meshCache.get(key);if(meshIndex===undefined){meshIndex=gltf.meshes.length;gltf.meshes.push({primitives:[{...geometry(o.geometry),material:materialIndex}]});meshCache.set(key,meshIndex);}const matrices=[];if(instances){for(const i of instances){const instance=new T.Matrix4();o.getMatrixAt(i,instance);matrices.push(new T.Matrix4().multiplyMatrices(o.matrixWorld,instance));}}else matrices.push(o.matrixWorld);for(const matrix of matrices){gltf.scenes[0].nodes.push(gltf.nodes.length);gltf.nodes.push({mesh:meshIndex,matrix:matrix.toArray().map(x=>Math.round(x*1e6)/1e6)});}}
parent.traverse(o=>{if(!o.isMesh)return;if(o.isInstancedMesh){const groups=new Map(),c=new T.Color();for(let i=0;i<o.count;i++){if(o.instanceColor)o.getColorAt(i,c);else c.copy(o.material.color);const key=c.getHexString();if(!groups.has(key))groups.set(key,[]);groups.get(key).push(i);}for(const [key,instances] of groups)add(o,instances,new T.Color('#'+key));}else add(o);});
gltf.buffers[0].byteLength=bytes;const json=Buffer.from(JSON.stringify(gltf)),jsonPad=(4-json.length%4)%4,jsonChunk=Buffer.concat([json,Buffer.alloc(jsonPad,32)]),binary=Buffer.concat(chunks),head=Buffer.alloc(12),jh=Buffer.alloc(8),bh=Buffer.alloc(8);head.writeUInt32LE(0x46546c67);head.writeUInt32LE(2,4);head.writeUInt32LE(12+8+jsonChunk.length+8+binary.length,8);jh.writeUInt32LE(jsonChunk.length);jh.writeUInt32LE(0x4e4f534a,4);bh.writeUInt32LE(binary.length);bh.writeUInt32LE(0x004e4942,4);const out=path.join(root,'assets/stadiums/xinzhuang-v31.glb');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,Buffer.concat([head,jh,jsonChunk,bh,binary]));console.log(JSON.stringify({file:out,bytes:fs.statSync(out).size,nodes:gltf.nodes.length,...profile}));
